"use client";

import { useMutation } from "@tanstack/react-query";
import { BookOpen } from "lucide-react";
import { useEffect, useMemo } from "react";
import { TextReader } from "@/components/reader/text-reader";
import { Button } from "@/components/ui/button";
import {
  useProfile,
  useReadTexts,
  useTextsForLevel,
} from "@/lib/queries/hooks";

export default function ReadPage() {
  const { data: profile } = useProfile();
  const { data: texts, isLoading, refetch } = useTextsForLevel(profile?.level_estimate);
  const { data: readRows, refetch: refetchRead } = useReadTexts();

  const readIds = useMemo(() => new Set((readRows ?? []).map((r) => r.text_id)), [readRows]);

  const unread = useMemo(() => {
    if (!texts) return [];
    // Seed texts first (they're hand-polished), then generated by age.
    return texts
      .filter((t) => !readIds.has(t.id))
      .sort((a, b) => (a.source === b.source ? 0 : a.source === "seed" ? -1 : 1));
  }, [texts, readIds]);

  const generate = useMutation({
    mutationFn: async () => {
      const res = await fetch("/api/generate", { method: "POST" });
      if (!res.ok) throw new Error((await res.json()).error ?? "generation failed");
      return res.json();
    },
    onSuccess: () => refetch(),
  });

  // Pool empty → ask the server to write a new text.
  const poolEmpty = !isLoading && !!readRows && unread.length === 0;
  useEffect(() => {
    if (poolEmpty && !generate.isPending && !generate.isError) {
      generate.mutate();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [poolEmpty]);

  if (isLoading || !profile || !readRows) {
    return <ReaderSkeleton />;
  }

  if (unread.length === 0) {
    return (
      <div className="flex flex-1 flex-col items-center justify-center py-32 text-center">
        <div className="flex size-14 items-center justify-center rounded-full bg-lapis-soft text-lapis">
          <BookOpen size={24} />
        </div>
        {generate.isError ? (
          <>
            <h2 className="mt-6 text-[20px] font-semibold">Couldn&apos;t write a new text</h2>
            <p className="mx-auto mt-2 max-w-xs text-[14px] text-ink-soft">
              {generate.error instanceof Error ? generate.error.message : "The AI writer is unavailable."}
            </p>
            <Button className="mt-8" onClick={() => generate.mutate()}>
              Try again
            </Button>
          </>
        ) : (
          <>
            <h2 className="mt-6 text-[20px] font-semibold">Writing your next text…</h2>
            <p className="mt-2 text-[14px] text-ink-soft">
              A fresh story with just the right new words.
            </p>
          </>
        )}
      </div>
    );
  }

  const current = unread[0];
  return (
    <TextReader
      doc={current.doc}
      onFinished={() => {
        void refetchRead();
        // Keep the pool warm for next time (fire-and-forget).
        void fetch("/api/generate", { method: "POST" });
      }}
    />
  );
}

function ReaderSkeleton() {
  return (
    <div className="animate-pulse pt-2">
      <div className="h-10 w-2/3 rounded-lg bg-line/60" />
      <div className="mt-2 h-4 w-1/3 rounded bg-line/50" />
      <div className="mt-10 space-y-7">
        {[...Array(4)].map((_, i) => (
          <div key={i} className="space-y-2">
            <div className="h-8 w-full rounded-lg bg-line/50" />
            <div className="h-8 w-4/5 rounded-lg bg-line/40" />
          </div>
        ))}
      </div>
    </div>
  );
}
