import json
import os

idioms = [
    ("fer l'orni", "to turn a blind eye / to play dumb", "idiom", "Quan li vaig preguntar pels diners, va fer l'orni i va canviar de tema.", "When I asked him about the money, he played dumb and changed the subject."),
    ("passar la nit en blanc", "to have a sleepless night", "idiom", "Vaig passar la nit en blanc pensant en l'examen de l'endemà.", "I had a sleepless night thinking about the exam the next day."),
    ("buscar tres peus al gat", "to look for trouble / to overcomplicate", "idiom", "No busquis tres peus al gat, la solució és molt més simple del que sembla.", "Don't overcomplicate things, the solution is much simpler than it seems."),
    ("ficar-hi cullerada", "to butt in / to interfere", "idiom", "Sempre li agrada ficar-hi cullerada en les converses alienes.", "He always likes to butt in on other people's conversations."),
    ("ser un cap de trons", "to be scatterbrained", "idiom", "Aquest noi és un cap de trons; ahir va perdre les claus de casa per segona vegada.", "This boy is scatterbrained; yesterday he lost his house keys for the second time."),
    ("anar a raure", "to end up", "idiom", "Després de moltes voltes, l'expedient va anar a raure a l'arxiu històric.", "After many turns, the file ended up in the historical archive."),
    ("anar-se'n en orris", "to go to ruin / to fail miserably", "idiom", "El projecte de construcció se'n va anar en orris per falta de pressupost.", "The construction project went to ruin due to lack of budget."),
    ("bufar i fer ampolles", "to be a piece of cake", "idiom", "Aprovar aquest examen no serà bufar i fer ampolles, caldrà estudiar molt.", "Passing this exam won't be a piece of cake, a lot of studying will be required."),
    ("cantar les quaranta", "to give someone a piece of one's mind", "idiom", "Si no canvia d'actitud, aviat li cantaré les quaranta.", "If he doesn't change his attitude, I will soon give him a piece of my mind."),
    ("costar un ull de la cara", "to cost an arm and a leg", "idiom", "La reparació del cotxe em va costar un ull de la cara.", "The car repair cost me an arm and a leg."),
    ("deixar amb un pam de nas", "to leave someone disappointed / empty-handed", "idiom", "La decisió del jutge ens va deixar amb un pam de nas.", "The judge's decision left us empty-handed."),
    ("descobrir la sopa d'all", "to state the obvious / to reinvent the wheel", "idiom", "Es pensa que ha descobert la sopa d'all, però aquesta teoria ja existia al segle dinou.", "He thinks he has reinvented the wheel, but this theory already existed in the nineteenth century."),
    ("embolicar la troca", "to complicate things further", "idiom", "En lloc d'ajudar, la seva intervenció només va servir per embolicar la troca.", "Instead of helping, his intervention only served to complicate things further."),
    ("ensenyar el llautó", "to show one's true colors", "idiom", "Amb aquelles declaracions intolerants va ensenyar el llautó ràpidament.", "With those intolerant statements he quickly showed his true colors."),
    ("fer campana", "to play truant / to skip class", "idiom", "Al batxillerat solíem fer campana per anar a prendre un cafè a la plaça.", "In high school we used to play truant to go have a coffee in the square."),
    ("fer dentetes", "to make someone's mouth water / to make someone jealous", "idiom", "Penja fotos de les vacances només per fer dentetes als seus companys.", "She posts vacation photos just to make her colleagues jealous."),
    ("fer el pes", "to be convincing", "idiom", "L'argumentació de l'advocat no em va acabar de fer el pes.", "The lawyer's argument didn't completely convince me."),
    ("fer els ulls grossos", "to turn a blind eye", "idiom", "L'inspector va fer els ulls grossos davant d'una infracció tan lleu.", "The inspector turned a blind eye to such a minor infraction."),
    ("fer farina blana", "to soften up / to yield", "idiom", "Després de molta insistència, el director va fer farina blana i va aprovar la sol·licitud.", "After much insistence, the director yielded and approved the request."),
    ("fer la guitza", "to annoy / to bother", "idiom", "El soroll de les obres no ha parat de fer-nos la guitza en tot el matí.", "The noise from the construction hasn't stopped annoying us all morning."),
    ("fer mans i mànigues", "to do everything possible", "idiom", "Vam fer mans i mànigues per arribar a temps, però l'avió ja s'havia enlairat.", "We did everything possible to arrive on time, but the plane had already taken off."),
    ("fer recular el riu", "to do the impossible", "idiom", "No li demanis que convenci el consell, no pot fer recular el riu.", "Don't ask him to convince the board, he cannot do the impossible."),
    ("filar prim", "to split hairs / to be meticulous", "idiom", "Si comencem a filar prim, trobarem defectes en qualsevol proposta.", "If we start splitting hairs, we will find flaws in any proposal."),
    ("girar cua", "to turn around and leave", "idiom", "Quan va veure l'embús a l'entrada, va girar cua i va tornar cap a casa.", "When he saw the traffic jam at the entrance, he turned around and headed back home."),
    ("haver begut oli", "to be done for / to be in big trouble", "idiom", "Si l'empresa no aconsegueix refinançar el deute, ja ha begut oli.", "If the company fails to refinance its debt, it's already done for."),
    ("llançar la tovallola", "to throw in the towel", "idiom", "Després de mesos de negociacions infructuoses, el sindicat va llançar la tovallola.", "After months of fruitless negotiations, the union threw in the towel."),
    ("matar el cuquet", "to have a snack / to take the edge off one's hunger", "idiom", "Abans de sopar, sempre menjo unes ametlles per matar el cuquet.", "Before dinner, I always eat some almonds to take the edge off my hunger."),
    ("no dir ase ni bèstia", "not to say a word", "idiom", "Durant tota la reunió es va quedar callat; no va dir ase ni bèstia.", "During the whole meeting he remained silent; he didn't say a word."),
    ("no entendre un borrall", "not to understand a single thing", "idiom", "La conferència era sobre física quàntica i no en vaig entendre un borrall.", "The conference was on quantum physics and I didn't understand a single thing."),
    ("no tenir pèls a la llengua", "to speak one's mind / to be outspoken", "idiom", "L'escriptora no té pèls a la llengua a l'hora de criticar el govern.", "The writer is outspoken when it comes to criticizing the government."),
    ("pagar els plats trencats", "to take the blame / to pay for others' mistakes", "idiom", "Sempre acaben pagant els plats trencats els treballadors amb menys antiguitat.", "The least senior workers always end up taking the blame."),
    ("parlar per parlar", "to talk for the sake of talking", "idiom", "A vegades fa l'efecte que els polítics al parlament només parlen per parlar.", "Sometimes it seems that politicians in parliament just talk for the sake of talking."),
    ("perdre el nord", "to lose one's bearings / to go astray", "idiom", "Amb tant de protagonisme mediàtic, l'artista ha perdut el nord.", "With so much media attention, the artist has lost his bearings."),
    ("picar ferro fred", "to waste one's breath / to labor in vain", "idiom", "Intentar que el meu pare canviï d'opinió és picar ferro fred.", "Trying to get my father to change his mind is wasting one's breath."),
    ("ploure a bots i barrals", "to rain cats and dogs", "idiom", "No podem sortir a fer la caminada avui perquè plou a bots i barrals.", "We can't go for the hike today because it's raining cats and dogs."),
    ("posar fil a l'agulla", "to get down to work", "idiom", "Ja és hora de posar fil a l'agulla i enllestir els preparatius del congrés.", "It's time to get down to work and finish the congress preparations."),
    ("posar tota la carn a la graella", "to pull out all the stops / to go all out", "idiom", "L'equip va posar tota la carn a la graella a la segona part del partit.", "The team pulled out all the stops in the second half of the match."),
    ("posar-se les piles", "to get one's act together", "idiom", "O et poses les piles amb l'anglès, o no aconseguiràs la feina.", "Either you get your act together with your English, or you won't get the job."),
    ("quedar-se de pedra", "to be stunned", "idiom", "Em vaig quedar de pedra quan em van anunciar que tancaven la sucursal.", "I was stunned when they announced that they were closing the branch."),
    ("remoure cel i terra", "to move heaven and earth", "idiom", "La família va remoure cel i terra per trobar el gos perdut.", "The family moved heaven and earth to find the lost dog."),
    ("saber greu", "to feel sorry / to regret", "idiom", "Em sap greu dir-t'ho, però t'has equivocat de cap a peus.", "I'm sorry to tell you this, but you are completely wrong."),
    ("ser figues d'un altre paner", "to be a different kettle of fish", "idiom", "Aprovar les matemàtiques és fàcil, però la física és figues d'un altre paner.", "Passing mathematics is easy, but physics is a different kettle of fish."),
    ("ser un clau", "to be punctual", "idiom", "La Marta és un clau, sempre arriba a l'oficina a les vuit en punt.", "Marta is punctual, she always arrives at the office at eight o'clock sharp."),
    ("sortir d'estudi", "to go off topic", "idiom", "El professor va sortir d'estudi i ens va explicar anècdotes de la seva joventut.", "The professor went off topic and told us anecdotes from his youth."),
    ("suar la cansalada", "to work up a sweat / to work hard", "idiom", "Hem suat la cansalada per poder lliurar aquest projecte dins del termini.", "We have worked up a sweat to be able to deliver this project on time."),
    ("tallar el bacallà", "to call the shots / to be in charge", "idiom", "En aquesta empresa familiar, qui talla el bacallà és la mare.", "In this family business, the one who calls the shots is the mother."),
    ("tocar el pirandó", "to take off / to scram", "idiom", "Quan va veure que s'acostava la policia, va tocar el pirandó immediatament.", "When he saw the police approaching, he took off immediately."),
    ("treure de polleguera", "to drive someone crazy", "idiom", "La seva lentitud a l'hora de prendre decisions em treu de polleguera.", "His slowness when making decisions drives me crazy."),
    ("veure les orelles al llop", "to see the danger coming", "idiom", "Quan l'empresa va fer retallades, molts van veure les orelles al llop.", "When the company made cuts, many saw the danger coming."),
    ("fer l'agost", "to make a killing / to make a good profit", "idiom", "Els venedors de gelats fan l'agost durant els mesos d'onada de calor.", "Ice cream vendors make a killing during the heatwave months.")
]

discourse = [
    ("a fi de", "in order to", "conjunction", "A fi d'evitar malentesos, la comissió va publicar un informe detallat.", "In order to avoid misunderstandings, the commission published a detailed report."),
    ("a l'inrevés", "on the contrary", "adverb", "No ens hem endarrerit; a l'inrevés, estem per davant del calendari previst.", "We haven't fallen behind; on the contrary, we are ahead of schedule."),
    ("al capdavall", "after all", "adverb", "Al capdavall, l'objectiu principal de la iniciativa és garantir el benestar de la ciutadania.", "After all, the main goal of the initiative is to ensure the wellbeing of the citizens."),
    ("al cap i a la fi", "at the end of the day", "adverb", "Al cap i a la fi, la decisió final dependrà del consell d'administració.", "At the end of the day, the final decision will depend on the board of directors."),
    ("amb tot", "nevertheless / yet", "adverb", "La proposta era arriscada; amb tot, vam decidir tirar-la endavant.", "The proposal was risky; nevertheless, we decided to move forward with it."),
    ("ans al contrari", "on the contrary", "adverb", "La seva resposta no ens va decebre; ans al contrari, va superar les expectatives.", "His response didn't disappoint us; on the contrary, it exceeded expectations."),
    ("ara bé", "however / now then", "adverb", "Totes les esmenes han estat acceptades. Ara bé, l'aprovació definitiva requereix majoria absoluta.", "All amendments have been accepted. However, final approval requires an absolute majority."),
    ("atès que", "given that / since", "conjunction", "Atès que s'ha superat el quòrum necessari, la sessió queda vàlidament constituïda.", "Given that the necessary quorum has been reached, the session is validly constituted."),
    ("ben mirat", "all things considered", "adverb", "Ben mirat, potser hauria estat més prudent esperar una resposta oficial.", "All things considered, perhaps it would have been wiser to wait for an official response."),
    ("cal dir que", "it must be said that", "phrase", "Cal dir que els resultats de l'estudi corroborarien la hipòtesi inicial de recerca.", "It must be said that the study's results would corroborate the initial research hypothesis."),
    ("com a regla general", "as a general rule", "adverb", "Com a regla general, els expedients administratius s'arxiven en un termini de sis mesos.", "As a general rule, administrative files are archived within six months."),
    ("com a resultat", "as a result", "adverb", "L'empresa va invertir en noves tecnologies i, com a resultat, la productivitat va augmentar notablement.", "The company invested in new technologies and, as a result, productivity increased significantly."),
    ("com s'ha dit", "as has been said", "phrase", "Com s'ha dit en els paràgrafs anteriors, la metodologia requereix una aplicació rigorosa.", "As has been said in previous paragraphs, the methodology requires rigorous application."),
    ("consegüentment", "consequently", "adverb", "S'ha incomplert el contracte i, consegüentment, s'aplicaran les penalitzacions pertinents.", "The contract has been breached and, consequently, the relevant penalties will be applied."),
    ("d'altra banda", "on the other hand", "adverb", "El mercat laboral millora; d'altra banda, la inflació continua sent un problema estructural.", "The labor market is improving; on the other hand, inflation remains a structural problem."),
    ("d'ara endavant", "from now on", "adverb", "S'ha establert que, d'ara endavant, totes les sol·licituds es tramitaran de forma exclusivament telemàtica.", "It has been established that, from now on, all applications will be processed exclusively electronically."),
    ("d'una banda", "on the one hand", "adverb", "D'una banda, la reforma fomenta l'ocupació juvenil; de l'altra, suposa un gran esforç fiscal.", "On the one hand, the reform encourages youth employment; on the other, it involves a major fiscal effort."),
    ("de conformitat amb", "in accordance with", "preposition", "Aquesta resolució s'emet de conformitat amb allò que disposa la llei vigent.", "This resolution is issued in accordance with the provisions of current law."),
    ("de fet", "in fact", "adverb", "La mesura no va ser impopular; de fet, bona part de l'oposició li va donar suport.", "The measure was not unpopular; in fact, a large part of the opposition supported it."),
    ("de la mateixa manera", "in the same way", "adverb", "El protocol s'aplicarà en l'àmbit docent i, de la mateixa manera, en l'àmbit investigador.", "The protocol will be applied in the teaching sphere and, in the same way, in the research sphere."),
    ("de manera que", "so that / in such a way that", "conjunction", "Es van distribuir les tasques equitativament de manera que tothom pogués acabar a temps.", "The tasks were distributed evenly so that everyone could finish on time."),
    ("deixant de banda", "setting aside", "phrase", "Deixant de banda les divergències ideològiques, el pacte d'estat era necessari.", "Setting aside ideological differences, the state pact was necessary."),
    ("doncs bé", "well then", "phrase", "S'han exposat els antecedents. Doncs bé, ara procedirem a analitzar-ne els efectes directes.", "The background has been presented. Well then, we will now proceed to analyze its direct effects."),
    ("en altres paraules", "in other words", "adverb", "El deute públic s'ha disparat; en altres paraules, el marge de maniobra financer és mínim.", "Public debt has skyrocketed; in other words, the financial room for maneuver is minimal."),
    ("en cas que", "in case", "conjunction", "El procediment preveu alternatives logístiques en cas que es produeixi una interrupció del subministrament.", "The procedure provides for logistical alternatives in case there is a supply interruption."),
    ("en comparació amb", "in comparison with", "phrase", "Aquest trimestre els beneficis han estat superiors en comparació amb l'exercici anterior.", "This quarter, profits have been higher in comparison with the previous year."),
    ("en conclusió", "in conclusion", "adverb", "En conclusió, l'assaig clínic demostra l'eficàcia del nou tractament a llarg termini.", "In conclusion, the clinical trial demonstrates the long-term efficacy of the new treatment."),
    ("en conseqüència", "consequently", "adverb", "La demanda del mercat va minvar bruscament i, en conseqüència, es va aturar la cadena de muntatge.", "Market demand dropped sharply and, consequently, the assembly line was halted."),
    ("en darrer lloc", "in the last place / finally", "adverb", "En darrer lloc, el ponent va voler agrair l'atenció de tots els presents a la sala.", "Finally, the speaker wanted to thank all those present in the room for their attention."),
    ("en definitiva", "ultimately / in short", "adverb", "En definitiva, el projecte de llei cerca harmonitzar la normativa europea amb la legislació autonòmica.", "Ultimately, the bill seeks to harmonize European regulations with regional legislation."),
    ("en efecte", "indeed", "adverb", "El tribunal va desestimar el recurs d'apel·lació; en efecte, no hi havia cap vici de forma.", "The court dismissed the appeal; indeed, there was no procedural defect."),
    ("en primer lloc", "in the first place", "adverb", "En primer lloc, cal definir clarament quins són els objectius estratègics de l'organització.", "In the first place, the strategic objectives of the organization must be clearly defined."),
    ("en qualsevol cas", "in any case", "adverb", "L'ajut pot denegar-se, però en qualsevol cas l'administració ha de motivar la seva resolució.", "The grant may be denied, but in any case the administration must justify its decision."),
    ("en relació amb", "in relation to", "phrase", "En relació amb la vostra instància del passat cinc de març, us informem que ha estat tramitada.", "In relation to your request of March fifth, we inform you that it has been processed."),
    ("en resolució", "in summary / lastly", "adverb", "En resolució, les dades no aporten prou evidència per modificar el marc teòric existent.", "In summary, the data does not provide enough evidence to modify the existing theoretical framework."),
    ("en resum", "in summary", "adverb", "El text era prolix i complex; en resum, proposava una refundació completa del sistema fiscal.", "The text was verbose and complex; in summary, it proposed a complete overhaul of the tax system."),
    ("en virtut de", "by virtue of", "preposition", "L'acord es va signar en virtut de les competències delegades pel rectorat de la universitat.", "The agreement was signed by virtue of the powers delegated by the university's rectorate."),
    ("és a dir", "that is to say", "phrase", "El vehicle és híbrid, és a dir, combina un motor de combustió amb un d'elèctric.", "The vehicle is a hybrid, that is to say, it combines a combustion engine with an electric one."),
    ("fins a cert punt", "to a certain extent", "phrase", "El raonament del filòsof és vàlid fins a cert punt, però oblida els condicionants socials actuals.", "The philosopher's reasoning is valid to a certain extent, but forgets current social conditioning factors."),
    ("heus aquí", "here is / behold", "phrase", "L'atur va repuntar sobtadament i, heus aquí, el govern va haver d'improvisar un pla de xoc.", "Unemployment spiked suddenly and, behold, the government had to improvise an emergency plan."),
    ("malgrat tot", "despite everything", "adverb", "Les condicions meteorològiques eren pèssimes; malgrat tot, l'expedició va fer el cim.", "The weather conditions were terrible; despite everything, the expedition reached the summit."),
    ("més aviat", "rather", "adverb", "La reacció del mercat no va ser de pànic, sinó més aviat de cautela.", "The market's reaction was not one of panic, but rather of caution."),
    ("no obstant això", "nevertheless", "adverb", "L'informe preliminar era optimista. No obstant això, es va recomanar realitzar auditories addicionals.", "The preliminary report was optimistic. Nevertheless, it was recommended to carry out additional audits."),
    ("pel que fa a", "regarding", "phrase", "Pel que fa a la gestió de residus urbans, l'ajuntament ha endurit les ordenances municipals.", "Regarding the management of urban waste, the city council has tightened municipal ordinances."),
    ("per consegüent", "therefore / as a consequence", "adverb", "La inversió s'havia esfumat; per consegüent, el pla de viabilitat va quedar en paper mullat.", "The investment had vanished; therefore, the feasibility plan became a dead letter."),
    ("per contra", "on the contrary", "adverb", "Els ingressos ordinaris van caure un cinc per cent; per contra, els beneficis atípics van augmentar.", "Ordinary revenues fell by five percent; on the contrary, non-recurring profits increased."),
    ("per descomptat", "of course", "adverb", "S'acceptaran esmenes, per descomptat, sempre que estiguin dins del termini i la forma escaients.", "Amendments will be accepted, of course, provided they are within the appropriate timeframe and format."),
    ("per tant", "therefore", "adverb", "El termini de presentació ja ha expirat i, per tant, la candidatura no serà admesa.", "The submission deadline has already expired and, therefore, the application will not be admitted."),
    ("per últim", "finally", "adverb", "Per últim, cal fer esment a la inestimable col·laboració del voluntariat en aquesta fira cultural.", "Finally, mention must be made of the invaluable collaboration of the volunteers in this cultural fair."),
    ("posat que", "given that / provided that", "conjunction", "S'acceptarà el projecte arquitectònic posat que compleixi estrictament les normatives d'eficiència energètica.", "The architectural project will be accepted provided that it strictly complies with energy efficiency regulations.")
]

def make_json(data_list, prefix_id, band):
    out = []
    for i, (word, gloss, pos, ex_t, ex_e) in enumerate(data_list[:50]):
        out.append({
            "id": f"{prefix_id}-{i+1}",
            "target": word,
            "targetNormalized": word,
            "glossEn": gloss,
            "pos": pos,
            "freqRank": 999,
            "freqBand": band,
            "register": "formal" if prefix_id == "lx-discourse" else "neutral",
            "variants": [],
            "exampleTarget": ex_t,
            "exampleEn": ex_e,
            "tags": ["idiom"] if prefix_id == "lx-idioms" else ["discourse_marker", "formal"],
            "word": word,
            "gloss": gloss,
            "example": ex_t
        })
    return out

os.makedirs('/Users/ferran/repositories/dariapp/temp/lexicon_domains', exist_ok=True)
with open('/Users/ferran/repositories/dariapp/temp/lexicon_domains/c1_idioms1.json', 'w') as f:
    json.dump({"entries": make_json(idioms, "lx-idioms", 9)}, f, indent=2, ensure_ascii=False)

with open('/Users/ferran/repositories/dariapp/temp/lexicon_domains/c1_discourse.json', 'w') as f:
    json.dump({"entries": make_json(discourse, "lx-discourse", 10)}, f, indent=2, ensure_ascii=False)
