import json
import os

os.makedirs('temp/lexicon_domains', exist_ok=True)

arch_words = [
    {"target": "tafonomia", "pos": "noun", "glossEn": "taphonomy", "exampleTarget": "La tafonomia del jaciment ha alterat significativament la preservació de les restes òssies prehistòriques.", "exampleEn": "The taphonomy of the site has significantly altered the preservation of prehistoric skeletal remains.", "tags": ["archaeology"]},
    {"target": "ostracó", "pos": "noun", "glossEn": "ostracon", "exampleTarget": "L'ostracó trobat a les excavacions conté inscripcions comptables cabdals de l'època ptolemaica.", "exampleEn": "The ostracon found in the excavations contains crucial accounting inscriptions from the Ptolemaic period.", "tags": ["archaeology"]},
    {"target": "glíptica", "pos": "noun", "glossEn": "glyptics", "exampleTarget": "La glíptica minoica assoleix el seu màxim esplendor en els minúsculs segells d'esteatita.", "exampleEn": "Minoan glyptics reaches its maximum splendor in the tiny steatite seals.", "tags": ["archaeology"]},
    {"target": "arcosoli", "pos": "noun", "glossEn": "arcosolium", "exampleTarget": "Les pintures paleocristianes decoren sumptuosament l'intradós de l'arcosoli d'aquesta catacumba romana.", "exampleEn": "Early Christian paintings sumptuously decorate the intrados of the arcosolium of this Roman catacomb.", "tags": ["archaeology"]},
    {"target": "estilòbata", "pos": "noun", "glossEn": "stylobate", "exampleTarget": "El majestuós temple dòric s'assenta fermament sobre un estilòbata de marbre pentèlic impol·lut.", "exampleEn": "The majestic Doric temple sits firmly on a stylobate of pristine Pentelic marble.", "tags": ["archaeology"]},
    {"target": "estereòbata", "pos": "noun", "glossEn": "stereobate", "exampleTarget": "L'estereòbata esglaonat eleva el santuari, atorgant-li una preeminència visual innegable en l'Acròpolis.", "exampleEn": "The stepped stereobate elevates the sanctuary, giving it undeniable visual preeminence on the Acropolis.", "tags": ["archaeology"]},
    {"target": "palimpsest", "pos": "noun", "glossEn": "palimpsest", "exampleTarget": "L'anàlisi multiespectral del palimpsest ha revelat un tractat matemàtic d'Arquimedes prèviament ignorat.", "exampleEn": "Multispectral analysis of the palimpsest has revealed a previously ignored mathematical treatise by Archimedes.", "tags": ["archaeology"]},
    {"target": "epigrafia", "pos": "noun", "glossEn": "epigraphy", "exampleTarget": "L'epigrafia d'aquesta llosa funerària ha estat determinant per reconstruir el llinatge reial oblidat.", "exampleEn": "The epigraphy of this headstone has been decisive in reconstructing the forgotten royal lineage.", "tags": ["archaeology"]},
    {"target": "numismàtica", "pos": "noun", "glossEn": "numismatics", "exampleTarget": "L'estudi de la numismàtica ibèrica permet traçar les antigues rutes comercials de la Mediterrània occidental.", "exampleEn": "The study of Iberian numismatics makes it possible to trace ancient trade routes in the western Mediterranean.", "tags": ["archaeology"]},
    {"target": "estratigrafia", "pos": "noun", "glossEn": "stratigraphy", "exampleTarget": "Una acurada estratigrafia permet datar amb precisió cadascuna de les fases d'ocupació del vilatge protohistòric.", "exampleEn": "Careful stratigraphy allows each of the occupation phases of the protohistoric village to be dated precisely.", "tags": ["archaeology"]},
    {"target": "megalitisme", "pos": "noun", "glossEn": "megalithism", "exampleTarget": "El megalitisme atlàntic es caracteritza per construccions colossals lligades a complexos rituals funeraris.", "exampleEn": "Atlantic megalithism is characterized by colossal constructions linked to complex funerary rituals.", "tags": ["archaeology"]},
    {"target": "edicle", "pos": "noun", "glossEn": "aedicula", "exampleTarget": "L'edicle conté una petita efígie de la divinitat tutelar que protegia la domus pompeiana.", "exampleEn": "The aedicula contains a small effigy of the tutelary deity that protected the Pompeian domus.", "tags": ["archaeology"]},
    {"target": "estela", "pos": "noun", "glossEn": "stele", "exampleTarget": "La cèlebre estela de Rosetta fou el punt d'inflexió decisiu per al desxiframent dels jeroglífics egipcis.", "exampleEn": "The famous Rosetta stone was the decisive turning point for the deciphering of Egyptian hieroglyphs.", "tags": ["archaeology"]},
    {"target": "cròmlec", "pos": "noun", "glossEn": "cromlech", "exampleTarget": "El cròmlec servia com a primitiu observatori astronòmic per determinar els solsticis i equinoccis.", "exampleEn": "The cromlech served as a primitive astronomical observatory to determine solstices and equinoxes.", "tags": ["archaeology"]},
    {"target": "menhir", "pos": "noun", "glossEn": "menhir", "exampleTarget": "Un imponent menhir de granit marca la frontera del territori sagrat dels antics pobles celtes.", "exampleEn": "An imposing granite menhir marks the border of the sacred territory of the ancient Celtic peoples.", "tags": ["archaeology"]},
    {"target": "cenotafi", "pos": "noun", "glossEn": "cenotaph", "exampleTarget": "Aquest cenotafi majestuós fou erigit per commemorar els herois caiguts que no pogueren ser enterrats a la pàtria.", "exampleEn": "This majestic cenotaph was erected to commemorate the fallen heroes who could not be buried in their homeland.", "tags": ["archaeology"]},
    {"target": "hipogeu", "pos": "noun", "glossEn": "hypogeum", "exampleTarget": "El complex laberint de l'hipogeu amagava innombrables cambres sepulcrals decorades amb frescos inèdits.", "exampleEn": "The complex labyrinth of the hypogeum hid countless sepulchral chambers decorated with previously unseen frescoes.", "tags": ["archaeology"]},
    {"target": "bifaç", "pos": "noun", "glossEn": "handaxe", "exampleTarget": "El bifaç acheulià mostra una simetria exquisida que denota la complexitat cognitiva de l'Homo heidelbergensis.", "exampleEn": "The Acheulean handaxe shows an exquisite symmetry that denotes the cognitive complexity of Homo heidelbergensis.", "tags": ["archaeology"]},
    {"target": "propulsor", "pos": "noun", "glossEn": "spear-thrower", "exampleTarget": "Aquest propulsor de banya de ren, finament tallat, augmentava exponencialment l'abast i la força del dard.", "exampleEn": "This finely carved reindeer antler spear-thrower exponentially increased the range and force of the dart.", "tags": ["archaeology"]},
    {"target": "petròglif", "pos": "noun", "glossEn": "petroglyph", "exampleTarget": "El petròglif gravat a la roca granítica representa un cérvol estilitzat en ple salt.", "exampleEn": "The petroglyph engraved on the granite rock represents a stylized deer in mid-leap.", "tags": ["archaeology"]},
    {"target": "ziggurat", "pos": "noun", "glossEn": "ziggurat", "exampleTarget": "El ziggurat d'Ur s'alçava imponent sobre la plana mesopotàmica, connectant el cel i la terra.", "exampleEn": "The ziggurat of Ur rose imposingly over the Mesopotamian plain, connecting heaven and earth.", "tags": ["archaeology"]},
    {"target": "obelisc", "pos": "noun", "glossEn": "obelisk", "exampleTarget": "El faraó va manar esculpir un obelisc monolític colossal per commemorar el seu jubileu.", "exampleEn": "The pharaoh ordered a colossal monolithic obelisk to be sculpted to commemorate his jubilee.", "tags": ["archaeology"]},
    {"target": "peristil", "pos": "noun", "glossEn": "peristyle", "exampleTarget": "El peristil de la vil·la senyorial estava adornat amb una varietat impressionant de flora autòctona i fonts brolladores.", "exampleEn": "The peristyle of the stately villa was adorned with an impressive variety of native flora and gushing fountains.", "tags": ["archaeology"]},
    {"target": "capitell", "pos": "noun", "glossEn": "capital", "exampleTarget": "El capitell corinti es distingeix per la seva ornamentació exuberant amb fulles d'acant finament esculpides.", "exampleEn": "The Corinthian capital is distinguished by its exuberant ornamentation with finely sculpted acanthus leaves.", "tags": ["archaeology"]},
    {"target": "arquitrau", "pos": "noun", "glossEn": "architrave", "exampleTarget": "L'arquitrau massís suportava tot el pes del fris i el frontó en la façana del temple.", "exampleEn": "The massive architrave supported the entire weight of the frieze and the pediment on the facade of the temple.", "tags": ["archaeology"]},
    {"target": "timpà", "pos": "noun", "glossEn": "tympanum", "exampleTarget": "El timpà del portal romànic mostra un Pantocràtor flanquejat per les figures del Tetramorf.", "exampleEn": "The tympanum of the Romanesque portal shows a Pantocrator flanked by the figures of the Tetramorph.", "tags": ["archaeology"]},
    {"target": "absis", "pos": "noun", "glossEn": "apse", "exampleTarget": "L'absis semicircular està orientat cap a l'est, seguint la rigorosa tradició arquitectònica de l'època.", "exampleEn": "The semicircular apse is oriented towards the east, following the strict architectural tradition of the time.", "tags": ["archaeology"]},
    {"target": "necròpolis", "pos": "noun", "glossEn": "necropolis", "exampleTarget": "L'extensa necròpolis ha proporcionat dades valuosíssimes sobre les pràctiques funeràries dels ibers.", "exampleEn": "The extensive necropolis has provided extremely valuable data on the funerary practices of the Iberians.", "tags": ["archaeology"]},
    {"target": "tessel·la", "pos": "noun", "glossEn": "tessera", "exampleTarget": "Cada tessel·la de pasta vítria fou col·locada meticulosament per conformar l'intrincat patró geomètric.", "exampleEn": "Each glass paste tessera was meticulously placed to form the intricate geometric pattern.", "tags": ["archaeology"]},
    {"target": "panteó", "pos": "noun", "glossEn": "pantheon", "exampleTarget": "El panteó romà és un miracle de l'enginyeria, coronat per una immensa cúpula de formigó amb un òcul central.", "exampleEn": "The Roman pantheon is a miracle of engineering, crowned by an immense concrete dome with a central oculus.", "tags": ["archaeology"]},
    {"target": "exvot", "pos": "noun", "glossEn": "ex-voto", "exampleTarget": "La figureta de bronze fou dipositada al santuari com a exvot agraint la miraculosa curació de la malaltia.", "exampleEn": "The bronze figurine was deposited in the sanctuary as an ex-voto thanking for the miraculous cure of the disease.", "tags": ["archaeology"]},
    {"target": "paleografia", "pos": "noun", "glossEn": "paleography", "exampleTarget": "El domini de la paleografia és imprescindible per transcriure correctament els pergamins carolingis del monestir.", "exampleEn": "Mastery of paleography is essential to correctly transcribe the Carolingian parchments of the monastery.", "tags": ["archaeology"]},
    {"target": "prosopografia", "pos": "noun", "glossEn": "prosopography", "exampleTarget": "La prosopografia de l'èlit senatorial permet entendre les xarxes clientelars que governaven la Roma tardana.", "exampleEn": "The prosopography of the senatorial elite makes it possible to understand the patron-client networks that governed late Rome.", "tags": ["archaeology"]},
    {"target": "copròlit", "pos": "noun", "glossEn": "coprolite", "exampleTarget": "L'anàlisi microscòpica d'un copròlit pot revelar detalls fascinants sobre la dieta i els paràsits de les poblacions extintes.", "exampleEn": "Microscopic analysis of a coprolite can reveal fascinating details about the diet and parasites of extinct populations.", "tags": ["archaeology"]},
    {"target": "sedimentologia", "pos": "noun", "glossEn": "sedimentology", "exampleTarget": "La sedimentologia de la cova indica canvis dràstics de paleoclima durant el plistocè superior.", "exampleEn": "The sedimentology of the cave indicates drastic paleoclimate changes during the Upper Pleistocene.", "tags": ["archaeology"]},
    {"target": "antropocè", "pos": "noun", "glossEn": "anthropocene", "exampleTarget": "Alguns geòlegs i arqueòlegs debaten aferrissadament quin és l'estrat precís que marca l'inici de l'antropocè.", "exampleEn": "Some geologists and archaeologists passionately debate which is the precise stratum that marks the beginning of the Anthropocene.", "tags": ["archaeology"]},
    {"target": "fíbula", "pos": "noun", "glossEn": "fibula", "exampleTarget": "Aquesta fíbula de bronze, incrustada amb esmalt alveolat, servia per subjectar la rica capa del cabdill.", "exampleEn": "This bronze fibula, inlaid with champlevé enamel, served to fasten the chieftain's rich cloak.", "tags": ["archaeology"]},
    {"target": "torca", "pos": "noun", "glossEn": "torc", "exampleTarget": "La torca d'or massís era un clar símbol de poder i estatus insígnia entre la noblesa cèltica.", "exampleEn": "The solid gold torc was a clear symbol of power and flagship status among the Celtic nobility.", "tags": ["archaeology"]},
    {"target": "escarabeu", "pos": "noun", "glossEn": "scarab", "exampleTarget": "L'escarabeu d'ametista duia gravat el nom de Tuthmosis III i servia com a amulet protector infal·lible.", "exampleEn": "The amethyst scarab bore the engraved name of Thutmose III and served as an infallible protective amulet.", "tags": ["archaeology"]},
    {"target": "cartutx", "pos": "noun", "glossEn": "cartouche", "exampleTarget": "El nom del faraó estava emmarcat dins d'un cartutx allargat que el protegia per a l'eternitat.", "exampleEn": "The pharaoh's name was framed within an elongated cartouche that protected it for eternity.", "tags": ["archaeology"]},
    {"target": "mastaba", "pos": "noun", "glossEn": "mastaba", "exampleTarget": "La monumental mastaba de maons de fang albergava el sarcòfag del visir de les primeres dinasties.", "exampleEn": "The monumental mud-brick mastaba housed the sarcophagus of the vizier of the early dynasties.", "tags": ["archaeology"]},
    {"target": "piló", "pos": "noun", "glossEn": "pylon", "exampleTarget": "El piló flanquejava l'entrada principal del temple, estant profusament decorat amb escenes bèl·liques.", "exampleEn": "The pylon flanked the main entrance of the temple, being profusely decorated with war scenes.", "tags": ["archaeology"]},
    {"target": "sarcòfag", "pos": "noun", "glossEn": "sarcophagus", "exampleTarget": "El sarcòfag antropomorf de fusta policromada conservava intacta la mòmia de la sacerdotessa d'Amon.", "exampleEn": "The anthropomorphic sarcophagus of polychrome wood preserved intact the mummy of the priestess of Amun.", "tags": ["archaeology"]},
    {"target": "àmfora", "pos": "noun", "glossEn": "amphora", "exampleTarget": "L'àmfora panatenaica estava omplerta de l'oli sagrat que es concedia als atletes victoriosos.", "exampleEn": "The Panathenaic amphora was filled with the sacred oil that was granted to the victorious athletes.", "tags": ["archaeology"]},
    {"target": "jaciment", "pos": "noun", "glossEn": "archaeological site", "exampleTarget": "Aquest jaciment subaquàtic amaga un vaixell púnic enfonsat durant la Primera Guerra Púnica.", "exampleEn": "This underwater archaeological site hides a Punic ship sunk during the First Punic War.", "tags": ["archaeology"]},
    {"target": "fresc", "pos": "noun", "glossEn": "fresco", "exampleTarget": "El fresc minoic mostra escenes idíl·liques de la vida cortesana amb una paleta cromàtica vibrant.", "exampleEn": "The Minoan fresco shows idyllic scenes of court life with a vibrant chromatic palette.", "tags": ["archaeology"]},
    {"target": "cripta", "pos": "noun", "glossEn": "crypt", "exampleTarget": "Sota l'altar major s'amaga una vasta cripta romànica amb voltes d'aresta d'una execució impecable.", "exampleEn": "Below the high altar hides a vast Romanesque crypt with groined vaults of impeccable execution.", "tags": ["archaeology"]},
    {"target": "basílica", "pos": "noun", "glossEn": "basilica", "exampleTarget": "La basílica civil romana funcionava com a lloc d'administració de justícia i centre d'intensa activitat comercial.", "exampleEn": "The Roman civil basilica functioned as a place of justice administration and a center of intense commercial activity.", "tags": ["archaeology"]},
    {"target": "aqüeducte", "pos": "noun", "glossEn": "aqueduct", "exampleTarget": "L'enginyeria romana assoleix el clímax en la construcció d'aquest aqüeducte de tres nivells d'arcades de mig punt.", "exampleEn": "Roman engineering reaches its climax in the construction of this aqueduct with three levels of semicircular arcades.", "tags": ["archaeology"]},
    {"target": "mosaic", "pos": "noun", "glossEn": "mosaic", "exampleTarget": "El mosaic romà, amb una filigrana quasi pictòrica, il·lustra l'apoteosi d'Hèrcules amb un realisme torbador.", "exampleEn": "The Roman mosaic, with an almost pictorial watermark, illustrates the apotheosis of Hercules with disturbing realism.", "tags": ["archaeology"]}
]

diplomacy_words = [
    {"target": "plenipotenciari", "pos": "noun", "glossEn": "plenipotentiary", "exampleTarget": "El plenipotenciari ha estat investit amb poders absoluts per forjar i segellar un tractat vinculant amb l'estat veí.", "exampleEn": "The plenipotentiary has been invested with absolute powers to forge and seal a binding treaty with the neighboring state.", "tags": ["diplomacy"]},
    {"target": "exequàtur", "pos": "noun", "glossEn": "exequatur", "exampleTarget": "L'estat receptor va atorgar l'exequàtur al nou cònsol honorari, permetent-li exercir oficialment les seves funcions administratives.", "exampleEn": "The receiving state granted the exequatur to the new honorary consul, allowing him to officially exercise his administrative functions.", "tags": ["diplomacy"]},
    {"target": "plàcet", "pos": "noun", "glossEn": "agrément", "exampleTarget": "Abans d'anunciar el nomenament, l'ambaixador proposat ha d'obtenir el plàcet imperatiu del cap d'estat acollidor.", "exampleEn": "Before announcing the appointment, the proposed ambassador must obtain the imperative agrément of the welcoming head of state.", "tags": ["diplomacy"]},
    {"target": "suzerania", "pos": "noun", "glossEn": "suzerainty", "exampleTarget": "L'imperi otomà va mantenir una fràgil suzerania sobre aquells principats autònoms abans de la seva emancipació definitiva.", "exampleEn": "The Ottoman Empire maintained a fragile suzerainty over those autonomous principalities before their definitive emancipation.", "tags": ["diplomacy"]},
    {"target": "extraterritorialitat", "pos": "noun", "glossEn": "extraterritoriality", "exampleTarget": "El principi d'extraterritorialitat blinda les missions diplomàtiques de la jurisdicció immediata del país amfitrió.", "exampleEn": "The principle of extraterritoriality shields diplomatic missions from the immediate jurisdiction of the host country.", "tags": ["diplomacy"]},
    {"target": "inviolabilitat", "pos": "noun", "glossEn": "inviolability", "exampleTarget": "La Convenció de Viena consagra la inviolabilitat absoluta de la persona de l'agent diplomàtic i del seu lloc de residència.", "exampleEn": "The Vienna Convention enshrines the absolute inviolability of the diplomatic agent's person and their place of residence.", "tags": ["diplomacy"]},
    {"target": "irredemptisme", "pos": "noun", "glossEn": "irredentism", "exampleTarget": "L'irredemptisme d'aquella nació va instigar un seguit de guerres limítrofes per annexionar els territoris ètnicament afins.", "exampleEn": "The irredentism of that nation instigated a series of border wars to annex ethnically related territories.", "tags": ["diplomacy"]},
    {"target": "abrogació", "pos": "noun", "glossEn": "abrogation", "exampleTarget": "L'abrogació unilateral del conveni aranzelari va desencadenar una perniciosa i dilatada guerra comercial a escala global.", "exampleEn": "The unilateral abrogation of the tariff agreement triggered a pernicious and prolonged commercial war on a global scale.", "tags": ["diplomacy"]},
    {"target": "retorsió", "pos": "noun", "glossEn": "retorsion", "exampleTarget": "El govern va prendre mesures de retorsió imposant quotes dràstiques a les importacions del país ofensor.", "exampleEn": "The government took measures of retorsion by imposing drastic quotas on imports from the offending country.", "tags": ["diplomacy"]},
    {"target": "finlandització", "pos": "noun", "glossEn": "finlandization", "exampleTarget": "El temor a una finlandització va portar els països escandinaus restants a alinear-se subreptíciament amb la superpotència oposada.", "exampleEn": "The fear of finlandization led the remaining Scandinavian countries to surreptitiously align themselves with the opposing superpower.", "tags": ["diplomacy"]},
    {"target": "balcanització", "pos": "noun", "glossEn": "balkanization", "exampleTarget": "Els analistes temen la imminent balcanització de la regió si les faccions separatistes no assoleixen un consens constitutiu durador.", "exampleEn": "Analysts fear the imminent balkanization of the region if separatist factions do not reach a lasting constitutive consensus.", "tags": ["diplomacy"]},
    {"target": "supranacionalitat", "pos": "noun", "glossEn": "supranationality", "exampleTarget": "La Unió Europea és el paradigma per excel·lència de la supranacionalitat, on els estats cedeixen parcel·les cabdals de sobirania.", "exampleEn": "The European Union is the paradigm par excellence of supranationality, where states cede crucial parcels of sovereignty.", "tags": ["diplomacy"]},
    {"target": "multilateralisme", "pos": "noun", "glossEn": "multilateralism", "exampleTarget": "En temps de crisi climàtica, el multilateralisme s'erigeix com l'única via plausible per forjar solucions mediambientals vinculants i holístiques.", "exampleEn": "In times of climate crisis, multilateralism stands as the only plausible way to forge binding and holistic environmental solutions.", "tags": ["diplomacy"]},
    {"target": "bilateralisme", "pos": "noun", "glossEn": "bilateralism", "exampleTarget": "Aquest país opta per un bilateralisme pragmàtic a fi de teixir acords comercials exclusius i altament lucratius.", "exampleEn": "This country opts for pragmatic bilateralism in order to weave exclusive and highly lucrative trade agreements.", "tags": ["diplomacy"]},
    {"target": "dissuasió", "pos": "noun", "glossEn": "deterrence", "exampleTarget": "La doctrina militar de la dissuasió nuclear es basa en la certesa irrevocable d'una anihilació mútua assegurada.", "exampleEn": "The military doctrine of nuclear deterrence is based on the irrevocable certainty of mutually assured annihilation.", "tags": ["diplomacy"]},
    {"target": "distensió", "pos": "noun", "glossEn": "détente", "exampleTarget": "La distensió entre les dues superpotències hegemòniques va culminar en la signatura efímera de memoràndums de desarmament històrics.", "exampleEn": "The détente between the two hegemonic superpowers culminated in the ephemeral signing of historic disarmament memorandums.", "tags": ["diplomacy"]},
    {"target": "hegemonia", "pos": "noun", "glossEn": "hegemony", "exampleTarget": "La nova potència emergent persegueix establir una hegemonia indiscutible sobre les rutes marítimes fonamentals del Pacífic.", "exampleEn": "The new emerging power seeks to establish indisputable hegemony over the fundamental maritime routes of the Pacific.", "tags": ["diplomacy"]},
    {"target": "bel·ligerància", "pos": "noun", "glossEn": "belligerence", "exampleTarget": "El reconeixement de la bel·ligerància per part d'estats tercers atorga legitimitat al moviment insurgent segons el dret internacional.", "exampleEn": "The recognition of belligerence by third states grants legitimacy to the insurgent movement according to international law.", "tags": ["diplomacy"]},
    {"target": "ingerència", "pos": "noun", "glossEn": "interference", "exampleTarget": "El Consell de Seguretat va condemnar qualsevol ingerència estrangera en els afers interns del país acabat de descolonitzar.", "exampleEn": "The Security Council condemned any foreign interference in the internal affairs of the newly decolonized country.", "tags": ["diplomacy"]},
    {"target": "fideïcomís", "pos": "noun", "glossEn": "trusteeship", "exampleTarget": "L'illa fou administrada sota el sistema de fideïcomís de les Nacions Unides fins a la seva tan anhelada independència.", "exampleEn": "The island was administered under the United Nations trusteeship system until its much-desired independence.", "tags": ["diplomacy"]},
    {"target": "protectorat", "pos": "noun", "glossEn": "protectorate", "exampleTarget": "L'establiment d'aquell extens protectorat va encobrir dècades d'espoli neocolonial i subordinació econòmica insostenible.", "exampleEn": "The establishment of that extensive protectorate concealed decades of neocolonial plunder and unsustainable economic subordination.", "tags": ["diplomacy"]},
    {"target": "moratòria", "pos": "noun", "glossEn": "moratorium", "exampleTarget": "La comunitat internacional va decretar una moratòria rigorosa sobre la caça de cetacis per intentar restablir-ne les poblacions delmades.", "exampleEn": "The international community decreed a strict moratorium on whaling to attempt to restore their decimated populations.", "tags": ["diplomacy"]},
    {"target": "condomini", "pos": "noun", "glossEn": "condominium", "exampleTarget": "Aquest territori insular funciona com un condomini singular co-governat per dues nacions sobiranes amb legislatures concurrents.", "exampleEn": "This island territory functions as a singular condominium co-governed by two sovereign nations with concurrent legislatures.", "tags": ["diplomacy"]},
    {"target": "legació", "pos": "noun", "glossEn": "legation", "exampleTarget": "El diplomàtic va hissar la bandera a la nova legació, senyalitzant el restabliment protocol·lari de les relacions truncades.", "exampleEn": "The diplomat hoisted the flag at the new legation, signaling the protocolary reestablishment of the truncated relations.", "tags": ["diplomacy"]},
    {"target": "valisa", "pos": "noun", "glossEn": "diplomatic pouch", "exampleTarget": "Els documents altament classificats van ser tramesos mitjançant una valisa diplomàtica hermètica, exent de tota inspecció duanera.", "exampleEn": "The highly classified documents were sent via a hermetic diplomatic pouch, exempt from any customs inspection.", "tags": ["diplomacy"]},
    {"target": "salconduit", "pos": "noun", "glossEn": "safe conduct", "exampleTarget": "El comissari humanitari va exhibir el salconduit emès per les Nacions Unides per tal de travessar la perillosa línia del front.", "exampleEn": "The humanitarian commissioner exhibited the safe conduct issued by the United Nations in order to cross the dangerous front line.", "tags": ["diplomacy"]},
    {"target": "statu quo", "pos": "noun", "glossEn": "status quo", "exampleTarget": "L'emissari busca desesperadament mantenir l'statu quo per evitar un conflicte obert en aquesta regió altament volàtil.", "exampleEn": "The emissary desperately seeks to maintain the status quo to avoid an open conflict in this highly volatile region.", "tags": ["diplomacy"]},
    {"target": "modus vivendi", "pos": "noun", "glossEn": "modus vivendi", "exampleTarget": "Ambdues nacions enemistades han establert un fràgil modus vivendi mentre es negocien els complexos termes de la pacificació definitiva.", "exampleEn": "Both estranged nations have established a fragile modus vivendi while the complex terms of definitive pacification are negotiated.", "tags": ["diplomacy"]},
    {"target": "casus belli", "pos": "noun", "glossEn": "casus belli", "exampleTarget": "La flagrant invasió de l'espai aeri va ser esgrimida pel dictador com a inequívoc casus belli per desencadenar les hostilitats bèl·liques.", "exampleEn": "The flagrant invasion of the airspace was wielded by the dictator as an unequivocal casus belli to unleash hostilities.", "tags": ["diplomacy"]},
    {"target": "casus foederis", "pos": "noun", "glossEn": "casus foederis", "exampleTarget": "L'atac no provocat contra un membre de l'aliança constitueix un casus foederis que obliga els altres aliats a intervenir militarment.", "exampleEn": "The unprovoked attack against an alliance member constitutes a casus foederis that obliges the other allies to intervene militarily.", "tags": ["diplomacy"]},
    {"target": "concordat", "pos": "noun", "glossEn": "concordat", "exampleTarget": "El govern secular va rubricar un polèmic concordat amb la Santa Seu per regularitzar el finançament de l'ensenyament confessional privatiu.", "exampleEn": "The secular government signed a controversial concordat with the Holy See to regularize the financing of private confessional education.", "tags": ["diplomacy"]},
    {"target": "memoràndum", "pos": "noun", "glossEn": "memorandum", "exampleTarget": "El ministre d'exteriors va divulgar un esclaridor memoràndum d'entesa que delinea minuciosament els preacords de cooperació energètica.", "exampleEn": "The foreign minister disclosed an enlightening memorandum of understanding that meticulously outlines the pre-agreements for energy cooperation.", "tags": ["diplomacy"]},
    {"target": "ultimàtum", "pos": "noun", "glossEn": "ultimatum", "exampleTarget": "El dictador va llançar un ultimàtum perentori a l'oposició, exigint una rendició incondicional abans de quaranta-vuit hores.", "exampleEn": "The dictator issued a peremptory ultimatum to the opposition, demanding unconditional surrender within forty-eight hours.", "tags": ["diplomacy"]},
    {"target": "prolegomen", "pos": "noun", "glossEn": "prolegomenon", "exampleTarget": "L'apassionada al·locució del canceller va servir de prolegomen eloqüent al cabdal tractat de reconciliació nacional.", "exampleEn": "The chancellor's impassioned address served as an eloquent prolegomenon to the crucial treaty of national reconciliation.", "tags": ["diplomacy"]},
    {"target": "arbitratge", "pos": "noun", "glossEn": "arbitration", "exampleTarget": "La ferotge disputa fronterera es va sotmetre finalment a un arbitratge internacional independent per tal de cloure-la sota pautes estrictament jurídiques.", "exampleEn": "The fierce border dispute was finally submitted to an independent international arbitration in order to close it under strictly legal guidelines.", "tags": ["diplomacy"]},
    {"target": "embargament", "pos": "noun", "glossEn": "embargo", "exampleTarget": "El consell ha ratificat l'estricte embargament d'armes sobre la zona en litigi per coartar l'escalada de violència sistèmica.", "exampleEn": "The council has ratified the strict arms embargo on the disputed zone to constrain the escalation of systemic violence.", "tags": ["diplomacy"]},
    {"target": "represàlia", "pos": "noun", "glossEn": "reprisal", "exampleTarget": "Com a represàlia contundent per l'espionatge cibernètic, es van expulsar un terç dels agregats militars de la missió.", "exampleEn": "As a forceful reprisal for the cyber espionage, a third of the mission's military attachés were expelled.", "tags": ["diplomacy"]},
    {"target": "mediació", "pos": "noun", "glossEn": "mediation", "exampleTarget": "La perseverant mediació del diplomàtic veterà va propiciar una tímida però palpable aproximació entre els bàndols acarnissats.", "exampleEn": "The persevering mediation of the veteran diplomat fostered a timid but palpable rapprochement between the fierce sides.", "tags": ["diplomacy"]},
    {"target": "conciliació", "pos": "noun", "glossEn": "conciliation", "exampleTarget": "Es va endegar un ardu procés de conciliació diplomàtica per apaivagar l'animositat creixent i restaurar una cordialitat perduda.", "exampleEn": "An arduous process of diplomatic conciliation was launched to appease the growing animosity and restore a lost cordiality.", "tags": ["diplomacy"]},
    {"target": "ratificació", "pos": "noun", "glossEn": "ratification", "exampleTarget": "La solemne ratificació del tractat pel Senat és el requeriment sine qua non per a la seva plena entrada en vigor.", "exampleEn": "The solemn ratification of the treaty by the Senate is the sine qua non requirement for its full entry into force.", "tags": ["diplomacy"]},
    {"target": "desmilitarització", "pos": "noun", "glossEn": "demilitarization", "exampleTarget": "L'acord preveu la progressiva desmilitarització de la península i l'establiment taxatiu d'una robusta zona d'amortiment pacificada.", "exampleEn": "The agreement provides for the progressive demilitarization of the peninsula and the strict establishment of a robust pacified buffer zone.", "tags": ["diplomacy"]},
    {"target": "proliferació", "pos": "noun", "glossEn": "proliferation", "exampleTarget": "La incontrolada proliferació de l'armament de destrucció massiva constitueix l'amenaça més esfereïdora per a la nostra arquitectura de seguretat col·lectiva.", "exampleEn": "The uncontrolled proliferation of weapons of mass destruction constitutes the most terrifying threat to our collective security architecture.", "tags": ["diplomacy"]},
    {"target": "salvaguarda", "pos": "noun", "glossEn": "safeguard", "exampleTarget": "El nou protocol addicional introdueix una salvaguarda inèdita per vetllar pels inalienables drets de les minories transnacionals oprimides.", "exampleEn": "The new additional protocol introduces an unprecedented safeguard to watch over the inalienable rights of oppressed transnational minorities.", "tags": ["diplomacy"]},
    {"target": "capitulació", "pos": "noun", "glossEn": "capitulation", "exampleTarget": "L'estrepitosa desfeta estratègica i el setge ferri no van deixar cap altra sortida plausible a l'exèrcit invasor que una vergonyosa capitulació.", "exampleEn": "The resounding strategic defeat and the iron siege left no other plausible way out for the invading army than a shameful capitulation.", "tags": ["diplomacy"]},
    {"target": "armistici", "pos": "noun", "glossEn": "armistice", "exampleTarget": "L'anhelat armistici signat de matinada al cèlebre vagó de tren va posar un punt final apressant a quatre anys de carnisseria despietada.", "exampleEn": "The much-desired armistice signed at dawn in the famous train carriage put an urgent end to four years of ruthless carnage.", "tags": ["diplomacy"]},
    {"target": "tractat", "pos": "noun", "glossEn": "treaty", "exampleTarget": "La convenció fou el preludi d'un magne tractat multilateral de no agressió mútua subscrit per gairebé totes les nacions.", "exampleEn": "The convention was the prelude to a grand multilateral treaty of mutual non-aggression subscribed by almost all nations.", "tags": ["diplomacy"]},
    {"target": "credencial", "pos": "noun", "glossEn": "credential", "exampleTarget": "El flamant ambaixador va presentar amb extrema sumissió protocol·lària la seva lletra credencial a l'emperador durant l'audiència oficial.", "exampleEn": "The brand-new ambassador presented his letter of credence to the emperor with extreme protocolary submission during the official audience.", "tags": ["diplomacy"]},
    {"target": "asil", "pos": "noun", "glossEn": "asylum", "exampleTarget": "L'eminent dissident polític va demanar immediat asil diplomàtic a l'ambaixada arran d'una onada d'arrestos extrajudicials al país.", "exampleEn": "The eminent political dissident requested immediate diplomatic asylum at the embassy following a wave of extrajudicial arrests in the country.", "tags": ["diplomacy"]},
    {"target": "protocol", "pos": "noun", "glossEn": "protocol", "exampleTarget": "La negligència del rígid protocol cerimonial durant el sopar de gala va suscitar un greu i punyent incident diplomàtic d'abast global.", "exampleEn": "The negligence of the rigid ceremonial protocol during the gala dinner sparked a serious and poignant diplomatic incident of global reach.", "tags": ["diplomacy"]},
    {"target": "geopolítica", "pos": "noun", "glossEn": "geopolitics", "exampleTarget": "La complexa geopolítica d'aquesta vall riquíssima en hidrocarburs determina inexorablement la pauta de les aliances internacionals d'aquest turbulent segle.", "exampleEn": "The complex geopolitics of this hydrocarbon-rich valley inexorably determines the pattern of international alliances of this turbulent century.", "tags": ["diplomacy"]}
]

def write_out(filename, words_list, prefix_id):
    entries = []
    for i, w in enumerate(words_list):
        entry = {
            "id": f"{prefix_id}-{i}",
            "word": w["target"],
            "target": w["target"],
            "targetNormalized": w["target"],
            "gloss": w["glossEn"],
            "glossEn": w["glossEn"],
            "pos": w["pos"],
            "freqRank": 999,
            "freqBand": 10,
            "register": "neutral",
            "variants": [],
            "example": w["exampleTarget"],
            "exampleTarget": w["exampleTarget"],
            "exampleEn": w["exampleEn"],
            "tags": w["tags"]
        }
        entries.append(entry)
        
    final_json = {"entries": entries}
    
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(final_json, f, ensure_ascii=False, indent=2)

write_out('temp/lexicon_domains/c2_archaeology.json', arch_words, "lx-TEMP-arch")
write_out('temp/lexicon_domains/c2_diplomacy.json', diplomacy_words, "lx-TEMP-dipl")
print("Files generated successfully.")
