import json
import os

os.makedirs('/Users/ferran/repositories/dariapp/temp/lexicon_domains', exist_ok=True)

data = {
    "a2_transport": [
        ("bitllet", "noun", "ticket", "He comprat un bitllet senzill per al metro.", "I bought a single ticket for the subway."),
        ("abonament", "noun", "pass", "Amb l'abonament mensual puc viatjar cada dia.", "With the monthly pass I can travel every day."),
        ("andana", "noun", "platform", "El tren cap a Barcelona surt per l'andana dos.", "The train to Barcelona leaves from platform two."),
        ("via", "noun", "track", "No baixeu a la via, és perillós.", "Do not go down to the track, it is dangerous."),
        ("transbordament", "noun", "transfer", "Has de fer transbordament a l'estació de Sants.", "You have to transfer at Sants station."),
        ("parada", "noun", "stop", "Aquesta és la meva parada, baixo aquí.", "This is my stop, I get off here."),
        ("conductor", "noun", "driver", "El conductor de l'autobús va ser molt amable.", "The bus driver was very kind."),
        ("revisor", "noun", "inspector", "El revisor ens va demanar els bitllets al tren.", "The ticket inspector asked for our tickets on the train."),
        ("passatger", "noun", "passenger", "Cada passatger ha de portar el seu equipatge.", "Every passenger must carry their luggage."),
        ("ruta", "noun", "route", "Aquesta ruta d'autobús passa per la Sagrada Família.", "This bus route passes by the Sagrada Família."),
        ("horari", "noun", "schedule", "Pots consultar l'horari dels trens de Rodalies a internet.", "You can check the Rodalies train schedule on the internet."),
        ("retard", "noun", "delay", "El tren porta un retard de quinze minuts.", "The train has a fifteen-minute delay."),
        ("freqüència", "noun", "frequency", "La freqüència de pas del metro és de tres minuts.", "The frequency of the subway is three minutes."),
        ("estació", "noun", "station", "L'estació d'autobusos és a prop del centre.", "The bus station is near the center."),
        ("vagó", "noun", "carriage", "El primer vagó està reservat per a bicicletes.", "The first carriage is reserved for bicycles."),
        ("metro", "noun", "subway", "Agafo el metro per anar a la feina cada dia.", "I take the subway to go to work every day."),
        ("tramvia", "noun", "tram", "El tramvia va per l'avinguda Diagonal.", "The tram goes along Diagonal avenue."),
        ("autobús", "noun", "bus", "L'autobús urbà és híbrid i contamina menys.", "The urban bus is hybrid and pollutes less."),
        ("tren", "noun", "train", "El tren de mitjana distància va cap a Girona.", "The medium-distance train goes to Girona."),
        ("viatjar", "verb", "to travel", "M'agrada viatjar en transport públic.", "I like to travel by public transport."),
        ("pujar", "verb", "to get on", "Has de pujar a l'autobús per la porta del davant.", "You must get on the bus through the front door."),
        ("baixar", "verb", "to get off", "Vull baixar a la propera parada.", "I want to get off at the next stop."),
        ("validar", "verb", "to validate", "No oblidis validar el títol de transport.", "Don't forget to validate the transport ticket."),
        ("seient", "noun", "seat", "Cedeix el seient a les persones grans.", "Give up your seat to the elderly."),
        ("maquinista", "noun", "train driver", "El maquinista va frenar a temps.", "The train driver braked in time."),
        ("targeta", "noun", "card", "Utilitzo la targeta T-Casual per moure'm per la ciutat.", "I use the T-Casual card to get around the city."),
        ("trajecte", "noun", "journey", "El trajecte fins al poble dura mitja hora.", "The journey to the village takes half an hour."),
        ("transbordar", "verb", "to transfer", "Hem de transbordar a la línia verda.", "We have to transfer to the green line."),
        ("destinació", "noun", "destination", "La destinació final d'aquest vol és l'aeroport del Prat.", "The final destination of this flight is El Prat airport."),
        ("passatge", "noun", "fare", "El preu del passatge ha pujat aquest any.", "The price of the fare has gone up this year.")
    ],
    "a2_animals": [
        ("gos", "noun", "dog", "El meu gos sempre borda quan arriba el carter.", "My dog always barks when the mailman arrives."),
        ("gat", "noun", "cat", "Aquest gat passa el dia dormint al sofà.", "This cat spends the day sleeping on the sofa."),
        ("ocell", "noun", "bird", "He vist un ocell blau al balcó.", "I saw a blue bird on the balcony."),
        ("peix", "noun", "fish", "Al mercat de la Boqueria venen molt bon peix.", "They sell very good fish at the Boqueria market."),
        ("cavall", "noun", "horse", "Vam fer una excursió a cavall pel Pirineu.", "We went on a horseback ride through the Pyrenees."),
        ("vaca", "noun", "cow", "La vaca dóna llet fresca a la granja.", "The cow gives fresh milk at the farm."),
        ("porc", "noun", "pig", "A Catalunya, del porc se n'aprofita tot per fer embotits.", "In Catalonia, all of the pig is used to make sausages."),
        ("ovella", "noun", "sheep", "El pastor guiava el ramat d'ovelles.", "The shepherd guided the flock of sheep."),
        ("cabra", "noun", "goat", "El formatge de cabra és molt saborós.", "Goat cheese is very tasty."),
        ("gallina", "noun", "hen", "La gallina ha post un ou aquest matí.", "The hen laid an egg this morning."),
        ("conill", "noun", "rabbit", "Hem cuinat arròs amb conill per dinar.", "We cooked rice with rabbit for lunch."),
        ("ratolí", "noun", "mouse", "El gat està buscant el ratolí.", "The cat is looking for the mouse."),
        ("lleó", "noun", "lion", "El lleó és considerat el rei de la selva.", "The lion is considered the king of the jungle."),
        ("tigre", "noun", "tiger", "El tigre té ratlles negres i taronges.", "The tiger has black and orange stripes."),
        ("elefant", "noun", "elephant", "L'elefant de zoològic menjava cacauets.", "The zoo elephant was eating peanuts."),
        ("mico", "noun", "monkey", "El mico saltava de branca en branca.", "The monkey was jumping from branch to branch."),
        ("ós", "noun", "bear", "Hi ha algun ós bru a les muntanyes pirinenques.", "There is some brown bear in the Pyrenean mountains."),
        ("llop", "noun", "wolf", "A la nit se sentia udolar un llop.", "At night a wolf could be heard howling."),
        ("guineu", "noun", "fox", "La guineu és un animal molt astut.", "The fox is a very cunning animal."),
        ("cérvol", "noun", "deer", "Vam veure un cérvol al bosc del Montseny.", "We saw a deer in the Montseny forest."),
        ("serp", "noun", "snake", "No m'agraden les serps, em fan por.", "I don't like snakes, they scare me."),
        ("granota", "noun", "frog", "La granota va saltar a l'aigua de la bassa.", "The frog jumped into the pond water."),
        ("aranya", "noun", "spider", "Hi ha una aranya al sostre de l'habitació.", "There is a spider on the bedroom ceiling."),
        ("mosca", "noun", "fly", "Una mosca no em deixava dormir la migdiada.", "A fly wouldn't let me sleep my nap."),
        ("abella", "noun", "bee", "L'abella volava al voltant de les flors de Montserrat.", "The bee flew around the flowers of Montserrat."),
        ("formiga", "noun", "ant", "Una formiga transportava una engruna de pa.", "An ant was carrying a breadcrumb."),
        ("papallona", "noun", "butterfly", "Quina papallona tan bonica, de colors vius!", "What a beautiful butterfly, with bright colors!"),
        ("oreneta", "noun", "swallow", "L'oreneta anuncia l'arribada de la primavera.", "The swallow announces the arrival of spring."),
        ("gavina", "noun", "seagull", "La gavina volava per sobre la platja de la Barceloneta.", "The seagull was flying over the Barceloneta beach."),
        ("dofí", "noun", "dolphin", "Vam veure un dofí nadant prop de la Costa Brava.", "We saw a dolphin swimming near the Costa Brava.")
    ],
    "a2_hobbies": [
        ("dibuix", "noun", "drawing", "Faig classes de dibuix els dimarts.", "I take drawing classes on Tuesdays."),
        ("pintura", "noun", "painting", "La pintura és la meva afició preferida.", "Painting is my favorite hobby."),
        ("fotografia", "noun", "photography", "El meu germà és un apassionat de la fotografia.", "My brother is passionate about photography."),
        ("lectura", "noun", "reading", "La lectura d'un bon llibre em relaxa molt.", "Reading a good book relaxes me a lot."),
        ("escriptura", "noun", "writing", "Dedica les tardes a l'escriptura de poemes.", "She dedicates her afternoons to writing poems."),
        ("cuina", "noun", "cooking", "M'agrada molt la cuina tradicional catalana.", "I really like traditional Catalan cooking."),
        ("jardineria", "noun", "gardening", "La jardineria l'ajuda a desconnectar de la feina.", "Gardening helps him disconnect from work."),
        ("costura", "noun", "sewing", "El curs de costura comença la setmana que ve.", "The sewing course starts next week."),
        ("punt", "noun", "knitting", "La meva àvia m'ha ensenyat a fer mitja i punt.", "My grandmother taught me how to knit and stitch."),
        ("ganxet", "noun", "crochet", "Estic fent una bufanda de ganxet per a l'hivern.", "I'm making a crochet scarf for winter."),
        ("ceràmica", "noun", "ceramics", "Ha fet un plat de ceràmica molt original.", "She has made a very original ceramic plate."),
        ("fusteria", "noun", "carpentry", "El taller de fusteria és al costat de casa.", "The carpentry workshop is next to my house."),
        ("col·leccionisme", "noun", "collecting", "El col·leccionisme de segells és una afició clàssica.", "Stamp collecting is a classic hobby."),
        ("música", "noun", "music", "La música en directe té molta màgia.", "Live music has a lot of magic."),
        ("cant", "noun", "singing", "Participo a la coral del barri, m'encanta el cant.", "I participate in the neighborhood choir, I love singing."),
        ("ball", "noun", "dance", "Ens hem apuntat a una escola de ball de saló.", "We signed up for a ballroom dance school."),
        ("teatre", "noun", "theater", "Aquest cap de setmana anem al teatre a veure una comèdia.", "This weekend we are going to the theater to see a comedy."),
        ("cinema", "noun", "cinema", "El cinema de terror és el seu gènere favorit.", "Horror cinema is his favorite genre."),
        ("escacs", "noun", "chess", "Jugo a escacs amb el meu pare cada diumenge.", "I play chess with my father every Sunday."),
        ("trencaclosques", "noun", "puzzle", "Hem acabat un trencaclosques de mil peces.", "We finished a thousand-piece puzzle."),
        ("bricolatge", "noun", "DIY", "El cap de setmana el dedico al bricolatge de casa.", "I dedicate the weekend to home DIY."),
        ("modelisme", "noun", "model making", "El modelisme ferroviari requereix molta paciència.", "Railway model making requires a lot of patience."),
        ("esport", "noun", "sport", "Fer esport tres cops per setmana és saludable.", "Doing sport three times a week is healthy."),
        ("senderisme", "noun", "hiking", "El senderisme pel parc nacional d'Aigüestortes és fantàstic.", "Hiking through Aigüestortes national park is fantastic."),
        ("pesca", "noun", "fishing", "Anem de pesca al riu Ebre ben d'hora al matí.", "We go fishing in the Ebro river early in the morning."),
        ("caça", "noun", "hunting", "Al poble hi ha molta tradició de caça del senglar.", "In the village there is a long tradition of wild boar hunting."),
        ("acampada", "noun", "camping", "La setmana passada vam anar d'acampada a la muntanya.", "Last week we went camping in the mountains."),
        ("viatge", "noun", "trip", "Estem organitzant el nostre viatge d'estiu a Menorca.", "We are organizing our summer trip to Menorca."),
        ("videojoc", "noun", "video game", "Aquest videojoc té uns gràfics espectaculars.", "This video game has spectacular graphics."),
        ("artesania", "noun", "craftsmanship", "Sempre compro artesania local quan viatjo.", "I always buy local craftsmanship when I travel.")
    ],
    "a2_tech": [
        ("ordinador", "noun", "computer", "Treballo amb un ordinador portàtil.", "I work with a laptop computer."),
        ("pantalla", "noun", "screen", "La pantalla d'aquest monitor és molt gran.", "The screen of this monitor is very large."),
        ("teclat", "noun", "keyboard", "Se m'ha trencat una tecla del teclat mecànic.", "A key broke on my mechanical keyboard."),
        ("ratolí", "noun", "mouse", "Necessito un ratolí sense fils més ràpid.", "I need a faster wireless mouse."),
        ("impressora", "noun", "printer", "La impressora no té tinta negra.", "The printer has no black ink."),
        ("mòbil", "noun", "mobile phone", "He de carregar el mòbil perquè no té bateria.", "I have to charge the mobile phone because it has no battery."),
        ("tauleta", "noun", "tablet", "La nena juga amb la tauleta al menjador.", "The girl plays with the tablet in the dining room."),
        ("bateria", "noun", "battery", "La bateria de l'ordinador em dura molt poc.", "My computer's battery lasts very little."),
        ("carregador", "noun", "charger", "M'has de deixar el teu carregador, si us plau.", "You have to lend me your charger, please."),
        ("cable", "noun", "cable", "Connecta aquest cable a l'endoll de la paret.", "Connect this cable to the wall socket."),
        ("connexió", "noun", "connection", "La connexió a internet avui va molt lenta.", "The internet connection is very slow today."),
        ("xarxa", "noun", "network", "El tècnic està arreglant la xarxa informàtica de l'oficina.", "The technician is fixing the office's computer network."),
        ("internet", "noun", "internet", "Busco informació a internet per al treball de l'escola.", "I search for information on the internet for my school project."),
        ("correu", "noun", "email", "T'he enviat un correu electrònic amb les instruccions.", "I sent you an email with the instructions."),
        ("arxiu", "noun", "file", "He guardat l'arxiu de text al disc dur.", "I saved the text file to the hard drive."),
        ("carpeta", "noun", "folder", "Posa tots els documents en una sola carpeta.", "Put all the documents in a single folder."),
        ("programa", "noun", "program", "Aquest programa serveix per editar fotografies.", "This program is used to edit photographs."),
        ("aplicació", "noun", "application", "He descarregat una aplicació per aprendre idiomes.", "I downloaded an application to learn languages."),
        ("usuari", "noun", "user", "Has d'introduir el teu nom d'usuari i la clau.", "You have to enter your username and password."),
        ("contrasenya", "noun", "password", "La contrasenya ha de tenir números i lletres.", "The password must have numbers and letters."),
        ("ciència", "noun", "science", "La ciència avança molt ràpidament avui en dia.", "Science advances very quickly nowadays."),
        ("investigació", "noun", "research", "El centre de recerca fa una investigació important.", "The research center is doing important research."),
        ("experiment", "noun", "experiment", "L'experiment al laboratori de química ha estat un èxit.", "The experiment in the chemistry lab was a success."),
        ("laboratori", "noun", "laboratory", "Treballa en un laboratori fent anàlisis de sang.", "He works in a laboratory doing blood tests."),
        ("microscopi", "noun", "microscope", "Observen els bacteris amb l'ajuda del microscopi.", "They observe the bacteria with the help of the microscope."),
        ("telescopi", "noun", "telescope", "Puc veure la lluna molt a prop amb aquest telescopi.", "I can see the moon very close with this telescope."),
        ("planeta", "noun", "planet", "Mart és conegut com el planeta vermell.", "Mars is known as the red planet."),
        ("estrella", "noun", "star", "Aquesta nit el cel és ple, es veu més d'una estrella.", "Tonight the sky is full, you can see more than one star."),
        ("cèl·lula", "noun", "cell", "La cèl·lula és la unitat bàsica de la vida.", "The cell is the basic unit of life."),
        ("energia", "noun", "energy", "Hem de fomentar l'ús d'energia renovable.", "We must promote the use of renewable energy.")
    ],
    "a2_politics": [
        ("govern", "noun", "government", "El govern de la Generalitat ha aprovat noves mesures.", "The government of the Generalitat has approved new measures."),
        ("estat", "noun", "state", "L'estat ha invertit molts diners en sanitat enguany.", "The state has invested a lot of money in healthcare this year."),
        ("país", "noun", "country", "A quin país viatjaràs les properes vacances?", "Which country will you travel to next holidays?"),
        ("nació", "noun", "nation", "Catalunya és una nació amb una cultura pròpia.", "Catalonia is a nation with its own culture."),
        ("ciutadà", "noun", "citizen", "Com a ciutadà tens dret a vot.", "As a citizen you have the right to vote."),
        ("dret", "noun", "right", "La llibertat d'expressió és un dret fonamental.", "Freedom of speech is a fundamental right."),
        ("deure", "noun", "duty", "Pagar els impostos és un deure de tothom.", "Paying taxes is everyone's duty."),
        ("llei", "noun", "law", "El parlament ha de debatre la nova llei.", "The parliament has to debate the new law."),
        ("constitució", "noun", "constitution", "La constitució garanteix els drets dels ciutadans.", "The constitution guarantees the rights of the citizens."),
        ("parlament", "noun", "parliament", "El parlament de Catalunya està situat al parc de la Ciutadella.", "The parliament of Catalonia is located in the Ciutadella park."),
        ("congrés", "noun", "congress", "El congrés ha refusat la proposta del partit.", "The congress has rejected the party's proposal."),
        ("senat", "noun", "senate", "La llei va passar al senat ahir a la tarda.", "The law went to the senate yesterday afternoon."),
        ("diputat", "noun", "deputy", "El diputat va fer un discurs molt emocionant.", "The deputy made a very emotional speech."),
        ("senador", "noun", "senator", "El senador va votar en contra de la moció.", "The senator voted against the motion."),
        ("ministre", "noun", "minister", "La ministre de cultura va inaugurar l'exposició d'art.", "The minister of culture inaugurated the art exhibition."),
        ("president", "noun", "president", "El president de la Generalitat donarà una roda de premsa.", "The president of the Generalitat will give a press conference."),
        ("alcalde", "noun", "mayor", "L'alcalde del poble va assistir a la festa major.", "The mayor of the town attended the main festival."),
        ("ajuntament", "noun", "city council", "L'ajuntament organitza activitats per als joves a la plaça.", "The city council organizes activities for the youth in the square."),
        ("elecció", "noun", "election", "Diumenge que ve tenim una elecció municipal important.", "Next Sunday we have an important municipal election."),
        ("vot", "noun", "vote", "Cada vot compta per decidir el futur del país.", "Every vote counts to decide the future of the country."),
        ("urna", "noun", "ballot box", "He introduït la papereta a l'urna aquest matí.", "I put the ballot in the ballot box this morning."),
        ("papereta", "noun", "ballot paper", "Tria la papereta del partit que prefereixis.", "Choose the ballot paper of the party you prefer."),
        ("campanya", "noun", "campaign", "La campanya electoral comença la setmana vinent.", "The electoral campaign starts next week."),
        ("partit", "noun", "party", "Quin partit polític creus que guanyarà les eleccions?", "Which political party do you think will win the elections?"),
        ("candidat", "noun", "candidate", "El candidat va respondre a les preguntes dels periodistes.", "The candidate answered the journalists' questions."),
        ("majoria", "noun", "majority", "El govern té majoria absoluta al parlament.", "The government has an absolute majority in the parliament."),
        ("minoria", "noun", "minority", "El seu partit es troba en minoria després de votar.", "His party is in the minority after voting."),
        ("oposició", "noun", "opposition", "El líder de l'oposició critica la nova mesura econòmica.", "The leader of the opposition criticizes the new economic measure."),
        ("democràcia", "noun", "democracy", "La democràcia es basa en el respecte a la voluntat del poble.", "Democracy is based on respect for the will of the people."),
        ("política", "noun", "politics", "S'ha interessat per la política des de ben jove.", "He has been interested in politics since he was very young.")
    ],
    "a2_internet": [
        ("web", "noun", "website", "Pots trobar tota la informació a la web oficial.", "You can find all the information on the official website."),
        ("pàgina", "noun", "page", "Aquesta pàgina triga massa a carregar.", "This page takes too long to load."),
        ("enllaç", "noun", "link", "Fes clic a l'enllaç per veure el vídeo sencer.", "Click on the link to see the full video."),
        ("cercador", "noun", "search engine", "Utilitzo aquest cercador per trobar notícies recents.", "I use this search engine to find recent news."),
        ("navegador", "noun", "browser", "He d'actualitzar el navegador per seguretat.", "I have to update the browser for security."),
        ("pestanya", "noun", "tab", "Tinc més de deu pestanyes obertes alhora.", "I have more than ten tabs open at once."),
        ("perfil", "noun", "profile", "He canviat la foto de perfil de les xarxes socials.", "I changed the profile picture on social media."),
        ("compte", "noun", "account", "M'han bloquejat el compte per un error de la contrasenya.", "My account was blocked due to a password error."),
        ("publicació", "noun", "post", "La teva última publicació ha tingut molt èxit.", "Your latest post has been very successful."),
        ("comentari", "noun", "comment", "He deixat un comentari al blog d'en Joan.", "I left a comment on Joan's blog."),
        ("m'agrada", "noun", "like", "La foto de la castanyada va rebre molts 'm'agrada'.", "The picture of the castanyada received many 'likes'."),
        ("seguidor", "noun", "follower", "Aquest artista té més d'un milió de seguidors.", "This artist has over a million followers."),
        ("influenciador", "noun", "influencer", "L'influenciador de moda ha parlat de la nostra marca.", "The fashion influencer talked about our brand."),
        ("blog", "noun", "blog", "Escriu un blog sobre viatges i gastronomia catalana.", "He writes a blog about travel and Catalan gastronomy."),
        ("fòrum", "noun", "forum", "Vaig fer la consulta en un fòrum d'informàtica.", "I asked the question in a computer forum."),
        ("xat", "noun", "chat", "Estem parlant pel xat d'amics de l'escola.", "We are talking in the school friends' chat."),
        ("missatge", "noun", "message", "T'he enviat un missatge de veu molt llarg.", "I sent you a very long voice message."),
        ("vídeo", "noun", "video", "Miro un vídeo per aprendre a fer pa amb tomàquet.", "I watch a video to learn how to make pa amb tomàquet."),
        ("foto", "noun", "photo", "M'agrada pujar una foto de cada lloc on viatjo.", "I like to upload a photo of every place I travel to."),
        ("etiqueta", "noun", "hashtag/tag", "No t'oblidis de posar l'etiqueta a la publicació d'Instagram.", "Don't forget to put the hashtag on the Instagram post."),
        ("tendència", "noun", "trend", "Aquest tema és tendència a Twitter avui.", "This topic is a trend on Twitter today."),
        ("viral", "noun", "viral", "El vídeo dels castellers s'ha fet viral a tot el món.", "The video of the castellers has gone viral worldwide."),
        ("connexió", "noun", "connection", "La connexió d'aquesta cafeteria és gratuïta.", "The connection in this cafeteria is free."),
        ("wifi", "noun", "wifi", "Em pots dir la contrasenya de la wifi de casa teva?", "Can you tell me the wifi password at your house?"),
        ("encaminador", "noun", "router", "He reiniciat l'encaminador perquè no tenia internet.", "I rebooted the router because I had no internet."),
        ("descarregar", "verb", "to download", "Vaig descarregar una aplicació per aprendre català.", "I downloaded an app to learn Catalan."),
        ("pujar", "verb", "to upload", "Estic a punt de pujar el document al servidor en l'arxiu.", "I'm about to upload the document to the server in the file."),
        ("compartir", "verb", "to share", "Gràcies per compartir la recepta de l'escudella amb nosaltres.", "Thank you for sharing the escudella recipe with us."),
        ("bloquejar", "verb", "to block", "Si m'envien correu brossa, vaig a bloquejar l'usuari.", "If they send me spam, I am going to block the user."),
        ("seguir", "verb", "to follow", "Vaig començar a seguir aquella banda de música ahir.", "I started to follow that music band yesterday.")
    ],
    "a2_cooking": [
        ("bullir", "verb", "to boil", "Hem de bullir l'aigua per fer la pasta.", "We have to boil the water to make the pasta."),
        ("fregir", "verb", "to fry", "M'agrada fregir les patates amb oli d'oliva verge extra.", "I like to fry the potatoes with extra virgin olive oil."),
        ("rostir", "verb", "to roast", "Diumenge solem rostir un pollastre per dinar.", "On Sunday we usually roast a chicken for lunch."),
        ("coure", "verb", "to cook/bake", "Has de coure el pa al forn durant trenta minuts.", "You have to bake the bread in the oven for thirty minutes."),
        ("fornejar", "verb", "to bake", "Va fornejar unes galetes molt dolces per berenar.", "She baked some very sweet cookies for a snack."),
        ("tallar", "verb", "to cut", "Recorda tallar el formatge i el fuet en llesques fines.", "Remember to cut the cheese and the fuet into thin slices."),
        ("pelar", "verb", "to peel", "M'ajudes a pelar les pomes per al pastís?", "Can you help me peel the apples for the pie?"),
        ("picar", "verb", "to chop", "Cal picar la ceba i l'all per fer el sofregit.", "You need to chop the onion and garlic to make the sofrito."),
        ("ratllar", "verb", "to grate", "M'agrada ratllar una mica de tomàquet pel pa.", "I like to grate a bit of tomato for the bread."),
        ("batre", "verb", "to beat/whisk", "Hem de batre els ous per fer la truita de patates.", "We have to beat the eggs to make the potato omelette."),
        ("remenar", "verb", "to stir", "Has de remenar la sopa perquè no s'enganxi a l'olla.", "You have to stir the soup so it doesn't stick to the pot."),
        ("amanir", "verb", "to dress/season", "Solc amanir l'amanida amb oli, sal i vinagre.", "I usually dress the salad with oil, salt, and vinegar."),
        ("salar", "verb", "to salt", "No t'oblidis de salar la carn abans de coure-la.", "Don't forget to salt the meat before cooking it."),
        ("endolcir", "verb", "to sweeten", "Pots endolcir el cafè amb sucre o mel.", "You can sweeten the coffee with sugar or honey."),
        ("cassola", "noun", "casserole/pot", "Fem un arròs a la cassola boníssim.", "We are making a delicious rice in the casserole."),
        ("olla", "noun", "pot", "Posaré l'aigua a bullir dins la gran olla.", "I will put the water to boil in the large pot."),
        ("paella", "noun", "frying pan", "Fregeix l'ou en aquesta paella petita.", "Fry the egg in this small frying pan."),
        ("forn", "noun", "oven", "Treu la pizza del forn que ja està feta.", "Take the pizza out of the oven, it's ready."),
        ("microones", "noun", "microwave", "Escalfa el got de llet al microones, si us plau.", "Heat the glass of milk in the microwave, please."),
        ("ganivet", "noun", "knife", "El ganivet de tallar carn està molt afilat.", "The meat-cutting knife is very sharp."),
        ("forquilla", "noun", "fork", "M'he oblidat de posar la forquilla a la taula.", "I forgot to put the fork on the table."),
        ("cullera", "noun", "spoon", "La sopa d'escudella es menja amb cullera.", "Escudella soup is eaten with a spoon."),
        ("plat", "noun", "plate/dish", "He trencat un plat rentant els plats.", "I broke a plate washing the dishes."),
        ("got", "noun", "glass", "Em pots donar un got d'aigua fresca?", "Can you give me a glass of cold water?"),
        ("tassa", "noun", "cup/mug", "Agafa una tassa per prendre el te de la tarda.", "Take a cup to have afternoon tea."),
        ("bol", "noun", "bowl", "Posarem els cereals en aquest bol blau.", "We will put the cereal in this blue bowl."),
        ("batedora", "noun", "blender/mixer", "La batedora ens servirà per fer el puré.", "The blender will serve us to make the puree."),
        ("escorredor", "noun", "colander", "Passa la pasta per l'escorredor ràpidament.", "Pass the pasta through the colander quickly."),
        ("taula", "noun", "table", "La família sencer es reuneix al voltant de la taula de Nadal.", "The whole family gathers around the Christmas table."),
        ("davantal", "noun", "apron", "Posa't el davantal perquè no t'embrutis la roba.", "Put on the apron so you don't dirty your clothes.")
    ],
    "a2_crime": [
        ("crim", "noun", "crime", "La policia investiga el crim que va passar ahir a la nit.", "The police are investigating the crime that happened last night."),
        ("delicte", "noun", "offense/crime", "Conduir begut és un delicte greu.", "Driving drunk is a serious offense."),
        ("robatori", "noun", "robbery", "Hi ha hagut un robatori al banc del centre de la ciutat.", "There has been a robbery at the bank in the city center."),
        ("assassinat", "noun", "murder", "El detectiu busca proves de l'assassinat.", "The detective is looking for evidence of the murder."),
        ("frau", "noun", "fraud", "L'empresa va ser acusada de frau fiscal.", "The company was accused of tax fraud."),
        ("agressió", "noun", "assault", "L'agressió al carrer va ser denunciada immediatament.", "The street assault was reported immediately."),
        ("víctima", "noun", "victim", "La víctima de l'accident es recupera a l'hospital.", "The victim of the accident is recovering in the hospital."),
        ("sospitós", "noun", "suspect", "El sospitós va ser vist prop de l'estació de tren.", "The suspect was seen near the train station."),
        ("culpable", "noun", "guilty", "El jutge el va declarar culpable del robatori.", "The judge declared him guilty of the robbery."),
        ("innocent", "noun", "innocent", "Tothom és innocent fins que es demostri el contrari.", "Everyone is innocent until proven otherwise."),
        ("testimoni", "noun", "witness", "El testimoni va explicar tot el que havia vist.", "The witness explained everything he had seen."),
        ("prova", "noun", "evidence", "La policia científica analitza cada prova trobada.", "The forensics police analyze every piece of evidence found."),
        ("policia", "noun", "police", "Vaig trucar a la policia quan vaig sentir crits.", "I called the police when I heard shouts."),
        ("agent", "noun", "officer", "Un agent de trànsit dirigia els cotxes.", "A traffic officer was directing the cars."),
        ("inspector", "noun", "inspector", "L'inspector en cap porta el cas principal.", "The chief inspector is leading the main case."),
        ("comissaria", "noun", "police station", "Has d'anar a la comissaria per posar la denúncia.", "You must go to the police station to file the report."),
        ("detenció", "noun", "arrest", "La detenció del sospitós es va fer de matinada.", "The arrest of the suspect took place at dawn."),
        ("presó", "noun", "prison", "El lladre complirà condemna a la presó de Lledoners.", "The thief will serve his sentence in Lledoners prison."),
        ("cel·la", "noun", "cell", "El presoner comparteix la cel·la amb un altre reclús.", "The prisoner shares the cell with another inmate."),
        ("jutjat", "noun", "court", "El jutjat va demanar noves proves per resoldre el cas.", "The court requested new evidence to solve the case."),
        ("tribunal", "noun", "court/tribunal", "El tribunal decidirà demà el resultat final del judici.", "The tribunal will decide tomorrow the final result of the trial."),
        ("jutge", "noun", "judge", "El jutge va escoltar els arguments de l'advocat.", "The judge listened to the lawyer's arguments."),
        ("advocat", "noun", "lawyer", "L'advocat defensor demanarà l'absolució.", "The defense lawyer will ask for acquittal."),
        ("fiscal", "noun", "prosecutor", "El fiscal considera que hi ha prou proves.", "The prosecutor considers that there is enough evidence."),
        ("jurat", "noun", "jury", "El jurat popular ha de prendre una decisió difícil.", "The popular jury has to make a difficult decision."),
        ("judici", "noun", "trial", "El judici començarà el mes vinent al tribunal suprem.", "The trial will start next month at the supreme court."),
        ("sentència", "noun", "sentence", "La sentència obliga a pagar els danys causats.", "The sentence obliges to pay the damages caused."),
        ("multa", "noun", "fine", "M'han posat una multa per aparcar malament.", "I got a fine for parking poorly."),
        ("condemna", "noun", "conviction/sentence", "La condemna va ser inferior a l'esperada per tothom.", "The conviction was lower than expected by everyone."),
        ("llibertat", "noun", "freedom", "El presoner va sortir en llibertat ahir a la tarda.", "The prisoner was released in freedom yesterday afternoon.")
    ]
}

for name, items in data.items():
    entries = []
    for word, pos, gloss, example, exampleEn in items:
        entries.append({
            "word": word,
            "pos": pos,
            "gloss": gloss,
            "example": example,
            "exampleEn": exampleEn
        })
    filename = f"/Users/ferran/repositories/dariapp/temp/lexicon_domains/{name}.json"
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump({"entries": entries}, f, ensure_ascii=False, indent=2)

print("Generated all files.")
