import { conjugationSurfaces } from "../src/lib/lang/ca/conjugate.ts";
import { IRREGULAR_VERBS } from "../src/lib/lang/ca/irregulars.ts";
import { nominalForms, verbSpec } from "../src/lib/lang/ca/lexicon-index.ts";
import { matchKey, normalizeCatalan, tokenizeCatalan } from "../src/lib/lang/ca/normalize.ts";

/**
 * Verification harness for Catalan lexicon entries.
 *
 * Content generated by a model is guilty until proven innocent. Every check
 * here is mechanical - it compares a candidate against the Catalan engine that
 * the app itself uses, so an entry can only ship if the reader would actually
 * be able to resolve and explain it. Nothing relies on the model's own claim
 * that a word is real.
 *
 * What this cannot check is whether a gloss is *semantically* right; that stays
 * a human review job, which is why the generator is constrained to common
 * everyday vocabulary where errors are obvious on a read-through.
 */

export interface CandidateEntry {
  word: string;
  pos: string;
  gloss: string;
  example: string;
  exampleEn: string;
}

/**
 * Catalan infinitives end in -ar/-er/-re/-ir, with a tiny closed set of
 * exceptions. `dur` (to carry) is the common one: it belongs to the second
 * conjugation but its infinitive shows none of the usual endings.
 */
const INFINITIVE_EXCEPTIONS = new Set(["dur"]);

/**
 * Verbs that legitimately lack most of their paradigm.
 *
 * `ploure` is impersonal and `caldre` exists only in the third person, so their
 * irregulars entries deliberately list a handful of forms. The usual "a verb
 * must yield at least 20 surfaces" floor is a check against a broken stem, and
 * would otherwise reject exactly the verbs whose paradigm is correctly small.
 * Generating *plovem or *calc to satisfy a threshold would teach forms no
 * Catalan speaker uses.
 */
const DEFECTIVE_VERBS = new Set(["ploure", "caldre", "nevar"]);

const POS_VALUES = new Set([
  "noun", "verb", "adjective", "adverb", "pronoun", "preposition",
  "conjunction", "particle", "numeral", "interjection", "determiner", "phrase",
]);

/** Catalan letters plus the marks that are part of the orthography. */
const CATALAN_ONLY = /^[a-zàèéíïòóúüç·'\- ]+$/i;

export function verifyEntry(
  c: CandidateEntry,
  seenKeys: Map<string, string>,
): string[] {
  const problems: string[] = [];
  const word = normalizeCatalan(c.word ?? "");

  if (!word) return ["empty headword"];
  if (!POS_VALUES.has(c.pos)) problems.push(`invalid pos "${c.pos}"`);
  if (!c.gloss?.trim()) problems.push("empty gloss");
  if (!c.example?.trim() || !c.exampleEn?.trim()) problems.push("missing example");

  // Reject anything that is not written in Catalan orthography. This is the
  // check that catches a model drifting into Spanish (ñ), French (ê) or worse.
  if (!CATALAN_ONLY.test(word)) problems.push(`non-Catalan characters in "${word}"`);
  if (/ñ|ê|â|î|ô|û|ã|õ|ø|ß/i.test(word + c.example)) {
    problems.push("characters from another language");
  }

  // One key maps to one lexeme, so any collision - including an exact repeat of
  // a word already in the lexicon - must be rejected. An earlier version
  // exempted `clash === word`, which let straight duplicates through.
  const key = matchKey(word);
  const clash = seenKeys.get(key);
  if (clash) problems.push(`duplicate of "${clash}"`);

  // A verb must be an infinitive the conjugator recognises, or the reader can
  // never resolve any of its inflected forms.
  if (c.pos === "verb") {
    if (!/(ar|er|re|ir)$/.test(word) && !INFINITIVE_EXCEPTIONS.has(word)) {
      problems.push(`verb "${word}" is not an infinitive (-ar/-er/-re/-ir)`);
    } else {
      const spec = verbSpec(word);
      if (!spec) problems.push(`verb "${word}" has no conjugation spec`);
      else {
        const forms = conjugationSurfaces(spec);
        const floor = DEFECTIVE_VERBS.has(word) ? 6 : 20;
        if (forms.length < floor) problems.push(`verb "${word}" yields only ${forms.length} forms`);
        // A regular paradigm built on a wrong stem shows up as forms that do
        // not start with the stem.
        if (!forms.includes(word)) problems.push(`verb "${word}" missing its own infinitive`);
      }
    }
  }

  // Dictionary form for an adjective is masculine singular. A model asked for
  // "married" readily returns `casada`; the feminine endings -ada/-ida/-osa
  // are the reliable tell, since the masculine counterparts are -at/-it/-ós.
  if (c.pos === "adjective" && /(ada|ida|osa|iva|ana|ina)$/.test(word)) {
    problems.push(`adjective "${word}" looks feminine; use the masculine singular`);
  }

  // Nouns and adjectives must pluralise into something plausible.
  if (c.pos === "noun" || c.pos === "adjective") {
    if (!word.includes(" ") && nominalForms(word, c.pos).length === 0) {
      problems.push(`"${word}" (${c.pos}) yields no inflected forms`);
    }
  }

  // The example must actually contain its own headword, in a form the engine
  // can produce - otherwise the SRS card shows a sentence that does not
  // demonstrate the word.
  if (c.example) {
    const tokens = tokenizeCatalan(c.example).map(matchKey);
    const headTokens = tokenizeCatalan(word).map(matchKey);
    const surfaces = new Set<string>([key]);
    if (c.pos === "verb") {
      const spec = verbSpec(word);
      if (spec) for (const f of conjugationSurfaces(spec)) surfaces.add(matchKey(f));
    } else {
      for (const f of nominalForms(word, c.pos)) surfaces.add(matchKey(f));
    }
    const contained =
      headTokens.length > 1
        ? tokens.some((_, i) => headTokens.every((h, j) => tokens[i + j] === h))
        : tokens.some((t) => surfaces.has(t));
    if (!contained) problems.push(`example does not contain "${word}"`);
    if (tokens.length > 12) problems.push(`example too long (${tokens.length} tokens)`);
    if (tokens.length < 3) problems.push("example is too short to be a sentence");
    problems.push(...apostropheProblems(c.example));
  }

  if (problems.length === 0) seenKeys.set(key, word);
  return problems;
}

/**
 * Catalan apostrophation, which is obligatory rather than stylistic:
 *
 *   el  + vowel/h-  ->  l'    (el home   -> l'home)
 *   la  + vowel/h-  ->  l'    (la aigua  -> l'aigua)
 *   de  + vowel/h-  ->  d'    (de aigua  -> d'aigua)
 *
 * With one real exception: `la` does NOT elide before an unstressed i-/u-/hi-/hu-,
 * so `la idea` and `la universitat` are correct while `l'illa` is too (stressed
 * i). Stress is not derivable from spelling, so this check skips i-/u- initial
 * words entirely rather than risk a false positive.
 *
 * A learning app that ships "la explicació" actively teaches an error, which is
 * why this is a hard failure and not a warning.
 */
export function apostropheProblems(sentence: string): string[] {
  const out: string[] = [];
  // Vowels that always trigger elision after el/la/de.
  const ELIDES = /^(h?[aeoàèéòó])/i;
  const words = sentence.split(/\s+/);
  for (let i = 0; i < words.length - 1; i++) {
    const w = words[i].toLowerCase().replace(/[^a-zàèéíïòóúüç']/gi, "");
    const next = words[i + 1].replace(/[^a-zàèéíïòóúüç·]/gi, "");
    if (!next) continue;
    if ((w === "el" || w === "la" || w === "de") && ELIDES.test(next)) {
      const contracted = w === "de" ? "d'" : "l'";
      out.push(`"${w} ${next}" must be "${contracted}${next}"`);
    }
  }
  return out;
}

/** Irregular verbs are authored, so assert the table itself stays coherent. */
export function verifyIrregulars(): string[] {
  const problems: string[] = [];
  for (const [inf, spec] of Object.entries(IRREGULAR_VERBS)) {
    if (spec.infinitive !== inf) problems.push(`${inf}: infinitive/key mismatch`);
    if (!/(ar|er|re|ir)$/.test(inf) && !INFINITIVE_EXCEPTIONS.has(inf)) {
      problems.push(`${inf}: not an infinitive`);
    }
    const forms = conjugationSurfaces(spec);
    if (!forms.includes(inf)) problems.push(`${inf}: paradigm omits the infinitive`);
    for (const [slot, list] of Object.entries(spec.overrides ?? {})) {
      if (!list.length) problems.push(`${inf}.${slot}: empty override deletes a tense`);
      for (const f of list) {
        if (!CATALAN_ONLY.test(f)) problems.push(`${inf}.${slot}: "${f}" is not Catalan`);
      }
    }
  }
  return problems;
}
