import { conjugationSurfaces } from "../src/lib/lang/ca/conjugate.ts";
import { IRREGULAR_VERBS } from "../src/lib/lang/ca/irregulars.ts";
import { nominalForms, verbSpec } from "../src/lib/lang/ca/lexicon-index.ts";
import { matchKey, normalizeCatalan, tokenizeCatalan } from "../src/lib/lang/ca/normalize.ts";
import type { LexiconIndex } from "../src/lib/lang/types.ts";

/**
 * Verification harness for Catalan lexicon entries.
 *
 * Content generated by a model is guilty until proven innocent. Every check
 * here is mechanical - it compares a candidate against the Catalan engine that
 * the app itself uses, so an entry can only ship if the reader would actually
 * be able to resolve and explain it. Nothing relies on the model's own claim
 * that a word is real.
 *
 * What this cannot check is whether a gloss is *semantically* right; that stays
 * a human review job, which is why the generator is constrained to common
 * everyday vocabulary where errors are obvious on a read-through.
 */

export interface CandidateEntry {
  word: string;
  pos: string;
  gloss: string;
  example: string;
  exampleEn: string;
}

/**
 * Catalan infinitives end in -ar/-er/-re/-ir, with a tiny closed set of
 * exceptions. `dur` (to carry) is the common one: it belongs to the second
 * conjugation but its infinitive shows none of the usual endings.
 */
const INFINITIVE_EXCEPTIONS = new Set(["dur"]);

/**
 * Verbs that legitimately lack most of their paradigm.
 *
 * `ploure` is impersonal and `caldre` exists only in the third person, so their
 * irregulars entries deliberately list a handful of forms. The usual "a verb
 * must yield at least 20 surfaces" floor is a check against a broken stem, and
 * would otherwise reject exactly the verbs whose paradigm is correctly small.
 * Generating *plovem or *calc to satisfy a threshold would teach forms no
 * Catalan speaker uses.
 */
const DEFECTIVE_VERBS = new Set(["ploure", "caldre", "nevar"]);

/**
 * Diacritics the 2017 *Ortografia catalana* abolished.
 *
 * The reform kept the accent on ~15 minimal pairs (`bé/be`, `és/es`, `sí/si`,
 * `té/te`, `sòl/sol`, `ús/us`…) and removed it everywhere else. These are the
 * survivors a model still produces, because most of the Catalan it was trained
 * on predates the reform. Shipping them teaches a spelling that has been wrong
 * for nine years - and it appeared in the lexicon entry for `ser` itself.
 *
 * `irregulars.ts` deliberately still *resolves* both spellings: a learner
 * meeting an older book should get an answer when they tap the word. What is
 * banned is displaying the old form as the model.
 */
const OBSOLETE_DIACRITICS: [RegExp, string][] = [
  [/(?<!\p{L})sóc(?!\p{L})/iu, "soc"],
  [/(?<!\p{L})dóna(?!\p{L})/iu, "dona"],
  [/(?<!\p{L})dóno(?!\p{L})/iu, "dono"],
  [/(?<!\p{L})véns(?!\p{L})/iu, "vens"],
  [/(?<!\p{L})vénen(?!\p{L})/iu, "venen"],
];

/** Post-2017 spelling check for any Catalan string the app displays. */
export function obsoleteSpellings(text: string): string[] {
  const out: string[] = [];
  for (const [re, modern] of OBSOLETE_DIACRITICS) {
    const m = text.match(re);
    if (m) out.push(`"${m[0]}" is pre-2017 spelling; write "${modern}"`);
  }
  return out;
}

const POS_VALUES = new Set([
  "noun", "verb", "adjective", "adverb", "pronoun", "preposition",
  "conjunction", "particle", "numeral", "interjection", "determiner", "phrase",
]);

/** Catalan letters plus the marks that are part of the orthography. */
const CATALAN_ONLY = /^[a-zàèéíïòóúüç·'\- ]+$/i;

export function verifyEntry(
  c: CandidateEntry,
  seenKeys: Map<string, string>,
): string[] {
  const problems: string[] = [];
  const word = normalizeCatalan(c.word ?? "");

  if (!word) return ["empty headword"];
  if (!POS_VALUES.has(c.pos)) problems.push(`invalid pos "${c.pos}"`);
  if (!c.gloss?.trim()) problems.push("empty gloss");
  if (!c.example?.trim() || !c.exampleEn?.trim()) problems.push("missing example");

  // Reject anything that is not written in Catalan orthography. This is the
  // check that catches a model drifting into Spanish (ñ), French (ê) or worse.
  if (!CATALAN_ONLY.test(word)) problems.push(`non-Catalan characters in "${word}"`);
  problems.push(...obsoleteSpellings(word));
  if (/ñ|ê|â|î|ô|û|ã|õ|ø|ß/i.test(word + c.example)) {
    problems.push("characters from another language");
  }

  // One key maps to one lexeme, so any collision - including an exact repeat of
  // a word already in the lexicon - must be rejected. An earlier version
  // exempted `clash === word`, which let straight duplicates through.
  const key = matchKey(word);
  const clash = seenKeys.get(key);
  if (clash) problems.push(`duplicate of "${clash}"`);

  // A verb must be an infinitive the conjugator recognises, or the reader can
  // never resolve any of its inflected forms.
  if (c.pos === "verb") {
    if (!/(ar|er|re|ir)$/.test(word) && !INFINITIVE_EXCEPTIONS.has(word)) {
      problems.push(`verb "${word}" is not an infinitive (-ar/-er/-re/-ir)`);
    } else {
      const spec = verbSpec(word);
      if (!spec) problems.push(`verb "${word}" has no conjugation spec`);
      else {
        const forms = conjugationSurfaces(spec);
        const floor = DEFECTIVE_VERBS.has(word) ? 6 : 20;
        if (forms.length < floor) problems.push(`verb "${word}" yields only ${forms.length} forms`);
        // A regular paradigm built on a wrong stem shows up as forms that do
        // not start with the stem.
        if (!forms.includes(word)) problems.push(`verb "${word}" missing its own infinitive`);
      }
    }
  }

  // Dictionary form for an adjective is masculine singular. A model asked for
  // "married" readily returns `casada`; the feminine endings -ada/-ida/-osa
  // are the reliable tell, since the masculine counterparts are -at/-it/-ós.
  if (c.pos === "adjective" && /(ada|ida|osa|iva|ana|ina)$/.test(word)) {
    problems.push(`adjective "${word}" looks feminine; use the masculine singular`);
  }

  // Nouns and adjectives must pluralise into something plausible.
  if (c.pos === "noun" || c.pos === "adjective") {
    if (!word.includes(" ") && nominalForms(word, c.pos).length === 0) {
      problems.push(`"${word}" (${c.pos}) yields no inflected forms`);
    }
  }

  // The example must actually contain its own headword, in a form the engine
  // can produce - otherwise the SRS card shows a sentence that does not
  // demonstrate the word.
  if (c.example) {
    const tokens = tokenizeCatalan(c.example).map(matchKey);
    const headTokens = tokenizeCatalan(word).map(matchKey);
    const surfaces = new Set<string>([key]);
    if (c.pos === "verb") {
      const spec = verbSpec(word);
      if (spec) for (const f of conjugationSurfaces(spec)) surfaces.add(matchKey(f));
    } else {
      for (const f of nominalForms(word, c.pos)) surfaces.add(matchKey(f));
    }
    const contained =
      headTokens.length > 1
        ? tokens.some((_, i) => headTokens.every((h, j) => tokens[i + j] === h))
        : tokens.some((t) => surfaces.has(t));
    if (!contained) problems.push(`example does not contain "${word}"`);
    problems.push(...obsoleteSpellings(c.example));
    if (tokens.length > 12) problems.push(`example too long (${tokens.length} tokens)`);
    if (tokens.length < 3) problems.push("example is too short to be a sentence");
    /**
     * A word sheet shows `exampleTarget` as *the* model sentence for the word,
     * so a fragment is worse than unhelpful. "Vaig anar-hi perquè." and "No
     * vaig anar sinó." are not merely incomplete, they are ungrammatical -
     * both conjunctions demand a following clause - and they were the only
     * Catalan a learner ever saw for those two words.
     */
    // Unicode-aware boundaries: JS \b is ASCII-only, so it fires inside
    // "dolça." - ç counts as a non-word character and the following a looks
    // like a word start.
    if (/(?<!\p{L})(perquè|però|sinó|que|mentre|quan|si|ni|i|o|amb|sense|de|a|en|per|com)[.!?]$/iu.test(c.example)) {
      problems.push("example stops on a word that needs a complement");
    }
    problems.push(...apostropheProblems(c.example));
  }

  if (problems.length === 0) seenKeys.set(key, word);
  return problems;
}

/**
 * Catalan apostrophation, which is obligatory rather than stylistic:
 *
 *   el  + vowel/h-  ->  l'    (el home   -> l'home)
 *   la  + vowel/h-  ->  l'    (la aigua  -> l'aigua)
 *   de  + vowel/h-  ->  d'    (de aigua  -> d'aigua)
 *
 * With one real exception: `la` does NOT elide before an unstressed i-/u-/hi-/hu-,
 * so `la idea` and `la universitat` are correct while `l'illa` is too (stressed
 * i). Stress is not derivable from spelling, so this check skips i-/u- initial
 * words entirely rather than risk a false positive.
 *
 * A learning app that ships "la explicació" actively teaches an error, which is
 * why this is a hard failure and not a warning.
 */
export function apostropheProblems(sentence: string): string[] {
  const out: string[] = [];
  // Vowels that always trigger elision after el/la/de.
  const ELIDES = /^(h?[aeoàèéòó])/i;
  const words = sentence.split(/\s+/);
  for (let i = 0; i < words.length - 1; i++) {
    const w = words[i].toLowerCase().replace(/[^a-zàèéíïòóúüç']/gi, "");
    const next = words[i + 1].replace(/[^a-zàèéíïòóúüç·]/gi, "");
    if (!next) continue;
    if ((w === "el" || w === "la" || w === "de") && ELIDES.test(next)) {
      const contracted = w === "de" ? "d'" : "l'";
      out.push(`"${w} ${next}" must be "${contracted}${next}"`);
    }
  }
  return out;
}

/** Irregular verbs are authored, so assert the table itself stays coherent. */
export function verifyIrregulars(): string[] {
  const problems: string[] = [];
  for (const [inf, spec] of Object.entries(IRREGULAR_VERBS)) {
    if (spec.infinitive !== inf) problems.push(`${inf}: infinitive/key mismatch`);
    if (!/(ar|er|re|ir)$/.test(inf) && !INFINITIVE_EXCEPTIONS.has(inf)) {
      problems.push(`${inf}: not an infinitive`);
    }
    const forms = conjugationSurfaces(spec);
    if (!forms.includes(inf)) problems.push(`${inf}: paradigm omits the infinitive`);
    for (const [slot, list] of Object.entries(spec.overrides ?? {})) {
      if (!list.length) problems.push(`${inf}.${slot}: empty override deletes a tense`);
      for (const f of list) {
        if (!CATALAN_ONLY.test(f)) problems.push(`${inf}.${slot}: "${f}" is not Catalan`);
      }
    }
  }
  return problems;
}

/**
 * Verbs that legally govern a bare infinitive, so `vull venir` is Catalan and
 * `vinguis venir` is not. Modals and the aspectual periphrases; anything else
 * followed by an infinitive is a mistake.
 */
const GOVERNS_INFINITIVE = new Set(
  (
    "poder puc pots pot podem podeu poden pugui puguis puguem pugueu puguin podia podies podíem podíeu podien podré podràs podrà podrem podreu podran podria podries podríem podríeu podrien " +
    "voler vull vols vol volem voleu volen vulgui vulguis vulguem vulgueu vulguin volia volies volíem volíeu volien voldria voldries voldríem voldríeu voldrien " +
    "saber sé saps sap sabem sabeu saben sàpiga sàpigues sapiguem sapigueu sàpiguen sabia sabies sabíem sabíeu sabien " +
    "haver he has ha hem heu han hagi hagis hàgim hàgiu hagin havia havies havíem havíeu havien hauré hauràs haurà haurem haureu hauran hauria hauries hauríem hauríeu haurien hagués haguessis haguéssim haguéssiu haguessin " +
    "anar vaig vas va vam vau van vagi vagis anem aneu vagin anava anaves anàvem anàveu anaven aniré aniràs anirà anirem anireu aniran " +
    "caldre cal calia caldrà caldria calgui " +
    "soler solc sols sol solem soleu solen solia solies solíem solíeu solien " +
    "deure dec deus deu devem deveu deuen " +
    "gosar gosa goso gosen fer feu fa faig"
  ).split(/\s+/),
);

/** A Catalan infinitive, by ending. */
const INFINITIVE = /^[a-zàèéíòóúïüç·'-]+(?:ar|er|re|ir)$/i;

/**
 * The blank was filled with a finite verb, but the infinitive it replaced was
 * left in the sentence.
 *
 * Found live in 25 of 82 B1 and 20 of 80 B2 fillBlanks. Rendered to a learner,
 * `"Vull que tu ___ venir amb mi"` answered `vinguis` reads
 * `"Vull que tu vinguis venir amb mi"` - which is not Catalan, and is the only
 * model of the subjunctive those lessons ever show. Nothing caught it because
 * every check ran on the template, which is well-formed, rather than on the
 * sentence the learner ends up reading.
 */
export function strayInfinitive(
  target: string,
  answer: string,
  index: LexiconIndex,
): string[] {
  const filled = target.replace("___", answer);
  const raw = filled.split(/\s+/);
  const words = raw.map((w) => w.replace(/^[^\p{L}]+|[^\p{L}]+$/gu, ""));
  const answerHead = answer.trim().split(/\s+/).pop() ?? answer;

  const at = words.findIndex((w) => matchKey(w) === matchKey(answerHead));
  if (at === -1 || at + 1 >= words.length) return [];

  // A parenthesised infinitive is the lemma hint the exercise is built around -
  // "que ella ___ (treballar) avui" asks for the right form of *treballar* and
  // is how the YAML sources write it. It is only a defect when the parentheses
  // are missing, which is what the YAML-to-JSON conversion did to 30 of them.
  if (/^[(\[]/.test(raw[at + 1])) return [];

  const next = words[at + 1];
  if (!INFINITIVE.test(next)) return [];

  // The ending alone is not enough: `llibre`, `carrer` and `pare` all look like
  // infinitives. Ask the lexicon whether it is one.
  const entry = index.resolve(next);
  if (!entry || entry.pos !== "verb") return [];
  if (matchKey(entry.targetNormalized) !== matchKey(next)) return [];

  // The legal cases: a modal or aspectual verb governing the infinitive
  // ("vull venir"), or the linking preposition of a periphrasis
  // ("torno a llegir", "acabo de sortir").
  if (GOVERNS_INFINITIVE.has(matchKey(answerHead))) return [];
  if (/^(a|de|d'|que|per|sense|en)$/i.test(matchKey(answerHead))) return [];

  // A finite verb of its own immediately before an infinitive with nothing
  // linking them is the defect: the blank replaced the finite form and the
  // infinitive it replaced was never removed.
  return [
    `filling the blank leaves a stray infinitive: "${filled}" ` +
      `(answer "${answer}" is followed by the infinitive "${next}")`,
  ];
}
