import os

words = [
    ("باستان‌شناسی", "bāstān-šenāsī", "Noun", "archaeology", "باستان‌شناسی کلید فهم گذشته است.", "bāstān-šenāsī kilīd-e fahm-e gozašta ast.", "Archaeology is the key to understanding the past.", "archaeology", ""),
    ("دیرینه‌شناسی", "dērīna-šenāsī", "Noun", "paleontology", "دیرینه‌شناسی به ما در مورد تکامل می‌آموزد.", "dērīna-šenāsī ba mā dar mawred-e takāmol mēāmōzad.", "Paleontology teaches us about evolution.", "paleontology", ""),
    ("سنگ‌واره", "sang-wāra", "Noun", "fossil", "سنگ‌واره‌های ارزشمندی یافت شد.", "sang-wāra-hā-ye arzešmandī yāft šod.", "Valuable fossils were found.", "paleontology", ""),
    ("کتیبه", "katība", "Noun", "inscription", "این کتیبه به خط میخی است.", "īn katība ba xat-e mēxī ast.", "This inscription is in cuneiform.", "antiquity,archaeology", ""),
    ("هیروگلیف", "hērōglīf", "Noun", "hieroglyph", "خواندن هیروگلیف‌ها دشوار است.", "xāndan-e hērōglīf-hā dośwār ast.", "Reading hieroglyphs is difficult.", "antiquity", ""),
    ("خط میخی", "xat-e mēxī", "Noun", "cuneiform", "خط میخی یکی از قدیمی‌ترین خطوط است.", "xat-e mēxī yakē az qadīmī-tarīn xotūt ast.", "Cuneiform is one of the oldest scripts.", "antiquity", ""),
    ("آثار باستانی", "āsār-e bāstānī", "Noun", "antiquities", "موزه پر از آثار باستانی است.", "mōza por az āsār-e bāstānī ast.", "The museum is full of antiquities.", "archaeology", ""),
    ("کاوش", "kāwoš", "Noun", "excavation", "کاوش در این تپه آغاز شد.", "kāwoš dar īn tapa āğāz šod.", "Excavation began at this mound.", "archaeology", ""),
    ("عتیقه", "atīqa", "Noun", "antique/artifact", "یک عتیقه کمیاب کشف شد.", "yak atīqa-ye kamyāb kašf šod.", "A rare artifact was discovered.", "archaeology", ""),
    ("تپه باستانی", "tapa-ye bāstānī", "Noun", "ancient mound", "تپه‌های باستانی زیادی در بلخ وجود دارد.", "tapa-hā-ye bāstānī-ye zeyādī dar balx wajūd dārad.", "There are many ancient mounds in Balkh.", "archaeology", ""),
    ("تمدن", "tamaddon", "Noun", "civilization", "تمدن‌های اولیه در کنار رودخانه‌ها شکل گرفتند.", "tamaddon-hā-ye awwaliya dar kanār-e rōdxāna-hā šakl gereftand.", "Early civilizations formed alongside rivers.", "antiquity", ""),
    ("عصر حجر", "asr-e hajar", "Noun", "Stone Age", "انسان‌ها در عصر حجر ابزار سنگی می‌ساختند.", "ensān-hā dar asr-e hajar abzār-e sangī mēsāxtand.", "Humans made stone tools in the Stone Age.", "antiquity", ""),
    ("پارینه‌سنگی", "pārīna-sangī", "Noun", "Paleolithic", "دوره پارینه‌سنگی بسیار طولانی بود.", "dawra-ye pārīna-sangī besyār tōlānī būd.", "The Paleolithic period was very long.", "antiquity", ""),
    ("نوسنگی", "naw-sangī", "Noun", "Neolithic", "انقلاب نوسنگی تغییرات عظیمی آورد.", "enqelāb-e naw-sangī tağyīrāt-e azīmē āward.", "The Neolithic revolution brought massive changes.", "antiquity", ""),
    ("عصر مفرغ", "asr-e mafrağ", "Noun", "Bronze Age", "در عصر مفرغ فلزکاری پیشرفت کرد.", "dar asr-e mafrağ felezkārī pēšraft kard.", "Metalworking advanced in the Bronze Age.", "antiquity", ""),
    ("عصر آهن", "asr-e āhan", "Noun", "Iron Age", "سلاح‌های عصر آهن مقاوم‌تر بودند.", "selāh-hā-ye asr-e āhan moqāwem-tar būdand.", "Iron Age weapons were more durable.", "antiquity", ""),
    ("سفالینه", "sofālīna", "Noun", "pottery/potsherd", "سفالینه‌های منقوش یافت شد.", "sofālīna-hā-ye manqūš yāft šod.", "Painted pottery was found.", "archaeology", ""),
    ("گورستان باستانی", "gōrestān-e bāstānī", "Noun", "ancient necropolis", "گورستان باستانی رازهای زیادی دارد.", "gōrestān-e bāstānī rāz-hā-ye zeyādī dārad.", "The ancient necropolis holds many secrets.", "archaeology", ""),
    ("مومیایی", "mūmyāyī", "Noun", "mummy", "مومیایی در مقبره دست‌نخورده باقی مانده بود.", "mūmyāyī dar maqbara dast-naxorda bāqī mānda būd.", "The mummy remained untouched in the tomb.", "archaeology", ""),
    ("مقبره", "maqbara", "Noun", "tomb", "مقبره فرعون کشف شد.", "maqbara-ye fer'awn kašf šod.", "The pharaoh\'s tomb was discovered.", "archaeology", ""),
    ("تابوت‌دان", "tābūt-dān", "Noun", "sarcophagus", "تابوت‌دان از سنگ مرمر ساخته شده بود.", "tābūt-dān az sang-e marmar sāxta šoda būd.", "The sarcophagus was made of marble.", "archaeology", ""),
    ("استخوان‌بندی", "ostoxān-bandī", "Noun", "skeleton", "استخوان‌بندی یک انسان اولیه پیدا شد.", "ostoxān-bandī-ye yak ensān-e awwaliya paydā šod.", "The skeleton of an early human was found.", "paleontology", ""),
    ("جمجمه", "jomjoma", "Noun", "skull", "جمجمه نشان‌دهنده تکامل مغز است.", "jomjoma nešān-dihanda-ye takāmol-e mağz ast.", "The skull shows the evolution of the brain.", "paleontology", ""),
    ("کهن‌الگو", "kohan-olgō", "Noun", "archetype", "این نماد یک کهن‌الگو است.", "īn namād yak kohan-olgō ast.", "This symbol is an archetype.", "history", ""),
    ("اسطوره", "ostōra", "Noun", "myth", "اسطوره‌های یونانی جذاب هستند.", "ostōra-hā-ye yūnānī jazāb hastand.", "Greek myths are fascinating.", "antiquity", ""),
    ("اسطوره‌شناسی", "ostōra-šenāsī", "Noun", "mythology", "اسطوره‌شناسی به درک فرهنگ کمک می‌کند.", "ostōra-šenāsī ba dark-e farhang komak mēkonad.", "Mythology helps in understanding culture.", "history", ""),
    ("افسانه", "afsāna", "Noun", "legend", "این افسانه سینه به سینه نقل شده است.", "īn afsāna sīna ba sīna naql šoda ast.", "This legend has been passed down orally.", "history", ""),
    ("حماسه", "hamāsa", "Noun", "epic", "شاهنامه یک حماسه بزرگ است.", "šāhnāma yak hamāsa-ye bozorg ast.", "The Shahnameh is a great epic.", "history", ""),
    ("سلسله", "selsela", "Noun", "dynasty", "سلسله هخامنشیان امپراتوری بزرگی ساختند.", "selsela-ye haxāmanešīyān emprātōrī-ye bozorgē sāxtand.", "The Achaemenid dynasty built a great empire.", "history", ""),
    ("امپراتوری", "emprātōrī", "Noun", "empire", "امپراتوری روم باستان بسیار پهناور بود.", "emprātōrī-ye rōm-e bāstān besyār pahnāwar būd.", "The ancient Roman empire was very vast.", "history", ""),
    ("پادشاهی", "pādšāhī", "Noun", "kingdom", "پادشاهی بابل قدرتمند بود.", "pādšāhī-ye bābol qodratmand būd.", "The kingdom of Babylon was powerful.", "history", ""),
    ("خاندان", "xāndān", "Noun", "royal house/lineage", "خاندان سلطنتی تغییر کرد.", "xāndān-e saltanatī tağyīr kard.", "The royal lineage changed.", "history", ""),
    ("فرعون", "fer'awn", "Noun", "pharaoh", "فراعنه اهرام را ساختند.", "farā'ena ahrām rā sāxtand.", "The pharaohs built the pyramids.", "history", ""),
    ("خلیفه", "xalīfa", "Noun", "caliph", "خلیفه در بغداد مستقر بود.", "xalīfa dar bağdād mostaqar būd.", "The caliph was seated in Baghdad.", "history", ""),
    ("سلطان", "soltān", "Noun", "sultan", "سلطان محمود غزنوی فاتح بزرگی بود.", "soltān mahmūd-e ğaznawī fāteh-e bozorgē būd.", "Sultan Mahmud of Ghazni was a great conqueror.", "history", ""),
    ("وزیر", "wazīr", "Noun", "vizier", "وزیر اعظم امور کشور را اداره می‌کرد.", "wazīr-e a'zam omōr-e kešwar rā edāra mēkard.", "The grand vizier managed the country\'s affairs.", "history", ""),
    ("دربار", "darbār", "Noun", "royal court", "دانشمندان در دربار جمع می‌شدند.", "dānešmandān dar darbār jam' mēšodand.", "Scholars gathered at the royal court.", "history", ""),
    ("کتیبه‌خوانی", "katība-xānī", "Noun", "epigraphy", "کتیبه‌خوانی تخصص خاصی نیاز دارد.", "katība-xānī taxassos-e xāsē neyāz dārad.", "Epigraphy requires special expertise.", "archaeology", ""),
    ("سکه‌شناسی", "sekka-šenāsī", "Noun", "numismatics", "سکه‌شناسی تاریخ اقتصادی را روشن می‌کند.", "sekka-šenāsī tārīx-e eqtesādī rā rawšan mēkonad.", "Numismatics sheds light on economic history.", "archaeology", ""),
    ("خط‌شناسی", "xat-šenāsī", "Noun", "paleography", "خط‌شناسی در بررسی نسخ خطی مهم است.", "xat-šenāsī dar barrasī-ye nosax-e xattī mohem ast.", "Paleography is important in examining manuscripts.", "history", ""),
    ("نسخه خطی", "nosxa-ye xattī", "Noun", "manuscript", "یک نسخه خطی نادر در کتابخانه یافت شد.", "yak nosxa-ye xattī-ye nāder dar ketābxāna yāft šod.", "A rare manuscript was found in the library.", "history", ""),
    ("پاپیروس", "pāpīrōs", "Noun", "papyrus", "متون روی پاپیروس نوشته می‌شدند.", "motūn rōy-e pāpīrōs newešta mēšodand.", "Texts were written on papyrus.", "antiquity", ""),
    ("پوست‌نوشته", "pōst-newešta", "Noun", "parchment", "پوست‌نوشته‌ها بادوام‌تر بودند.", "pōst-newešta-hā bādawām-tar būdand.", "Parchments were more durable.", "antiquity", ""),
    ("طومار", "tōmār", "Noun", "scroll", "طومار بحر المیت کشفی تاریخی بود.", "tōmār-e bahr-ol-mayyet kašfē tārīxī būd.", "The Dead Sea scroll was a historic discovery.", "antiquity", ""),
    ("بایگانی", "bāygānī", "Noun", "archive", "بایگانی سلطنتی غارت شد.", "bāygānī-ye saltanatī ğārat šod.", "The royal archive was looted.", "history", ""),
    ("سالنامه", "sālnāma", "Noun", "annals/chronicle", "در سالنامه‌های آشوری به این جنگ اشاره شده است.", "dar sālnāma-hā-ye āšūrī ba īn jang ešāra šoda ast.", "This war is mentioned in the Assyrian annals.", "history", ""),
    ("گاه‌شماری", "gāh-šomārī", "Noun", "chronology/calendar", "گاه‌شماری جلالی بسیار دقیق است.", "gāh-šomārī-ye jalālī besyār daqīq ast.", "The Jalali calendar is very accurate.", "history", ""),
    ("میراث", "mērās", "Noun", "heritage", "حفظ میراث فرهنگی وظیفه ماست.", "hefz-e mērās-e farhangī wazīfa-ye mā-st.", "Preserving cultural heritage is our duty.", "archaeology", ""),
    ("یادمان", "yādmān", "Noun", "monument", "این یادمان به افتخار پیروزی ساخته شد.", "īn yādmān ba eftexār-e pērōzī sāxta šod.", "This monument was built in honor of the victory.", "history", ""),
    ("ویرانه", "wērāna", "Noun", "ruin", "ویرانه‌های بابل هنوز هم باشکوهند.", "wērāna-hā-ye bābol hanōz ham bāšokōh-and.", "The ruins of Babylon are still magnificent.", "archaeology", ""),
    ("آتشکده", "ātaškada", "Noun", "fire temple", "آتشکده باستانی در بلخ قرار دارد.", "ātaškada-ye bāstānī dar balx qarār dārad.", "An ancient fire temple is located in Balkh.", "history", ""),
    ("نیایشگاه", "neyāyašgāh", "Noun", "temple/shrine", "نیایشگاه آناهیتا کشف شد.", "neyāyašgāh-e ānāhītā kašf šod.", "The temple of Anahita was discovered.", "history", ""),
    ("زیگورات", "zīgōrāt", "Noun", "ziggurat", "زیگورات چغازنبیل یک شاهکار معماری است.", "zīgōrāt-e čoğāzanbīl yak šāhkār-e me'mārī ast.", "The Chogha Zanbil ziggurat is an architectural masterpiece.", "antiquity", ""),
    ("اهرام", "ahrām", "Noun", "pyramids", "اهرام مصر از عجایب هفتگانه هستند.", "ahrām-e mesr az ajāyeb-e haftgāna hastand.", "The pyramids of Egypt are among the Seven Wonders.", "antiquity", ""),
    ("ابوالهول", "abolhawl", "Noun", "Sphinx", "مجسمه ابوالهول نگهبان اهرام است.", "mojasama-ye abolhawl negahbān-e ahrām ast.", "The Sphinx statue guards the pyramids.", "antiquity", ""),
    ("مجسمه", "mojasama", "Noun", "statue/sculpture", "مجسمه بودا در بامیان تخریب شد.", "mojasama-ye bōdā dar bāmyān taxrīb šod.", "The Buddha statue in Bamyan was destroyed.", "archaeology", ""),
    ("تندیس", "tandēs", "Noun", "statue", "تندیس‌های یونانی بسیار واقع‌گرایانه بودند.", "tandēs-hā-ye yūnānī besyār wāqe'-garāyāna būdand.", "Greek statues were very realistic.", "archaeology", ""),
    ("نقش‌برجسته", "naqš-barjasta", "Noun", "bas-relief", "نقش‌برجسته‌های تخت جمشید بی‌نظیرند.", "naqš-barjasta-hā-ye taxt-e jamšēd bē-nazīr-and.", "The bas-reliefs of Persepolis are unique.", "archaeology", ""),
    ("سنگ‌نوشته", "sang-newešta", "Noun", "rock edict/inscription", "سنگ‌نوشته بیستون رازهای زیادی را فاش کرد.", "sang-newešta-ye bēsotūn rāz-hā-ye zeyādī rā fāš kard.", "The Behistun inscription revealed many secrets.", "archaeology", ""),
    ("گنجینه", "ganjīna", "Noun", "treasure/hoard", "گنجینه طلا تپه خیره‌کننده است.", "ganjīna-ye tellā tapa xēra-konanda ast.", "The Tillya Tepe treasure is dazzling.", "archaeology", ""),
    ("دفینه", "dafīna", "Noun", "buried treasure/hoard", "دفینه‌های باستانی اغلب توسط سارقین غارت می‌شوند.", "dafīna-hā-ye bāstānī ağlab tawassot-e sāreqīn ğārat mēšawand.", "Ancient buried treasures are often looted by thieves.", "archaeology", ""),
    ("کوزه‌گری", "kōza-garī", "Noun", "pottery making", "هنر کوزه‌گری در باستان اهمیت داشت.", "honar-e kōza-garī dar bāstān ahammiyat dāšt.", "The art of pottery making was important in antiquity.", "archaeology", ""),
    ("خشت", "xešt", "Noun", "mudbrick", "بناهای قدیمی از خشت ساخته می‌شدند.", "banā-hā-ye qadīmī az xešt sāxta mēšodand.", "Old buildings were made of mudbrick.", "archaeology", ""),
    ("ساروج", "sārōj", "Noun", "traditional mortar", "ساروج بسیار مقاوم است.", "sārōj besyār moqāwem ast.", "Traditional mortar is very durable.", "archaeology", ""),
    ("قنات", "qanāt", "Noun", "qanat/aqueduct", "سیستم قنات یک نوآوری باستانی است.", "sīstam-e qanāt yak naw-āwarī-ye bāstānī ast.", "The qanat system is an ancient innovation.", "history", ""),
    ("کاریز", "kārēz", "Noun", "qanat (alternative)", "کاریزها آب را به مناطق خشک می‌رساندند.", "kārēz-hā āb rā ba manāteq-e xošk mērasāndand.", "Qanats brought water to arid regions.", "history", ""),
    ("کاروانسرا", "kārwānsarā", "Noun", "caravanserai", "تجار در کاروانسرا استراحت می‌کردند.", "tojjār dar kārwānsarā esterāhat mēkardand.", "Merchants rested in the caravanserai.", "history", ""),
    ("جاده ابریشم", "jāda-ye abrēšam", "Noun", "Silk Road", "جاده ابریشم شرق و غرب را متصل می‌کرد.", "jāda-ye abrēšam šarq wa ğarb rā mottasel mēkard.", "The Silk Road connected East and West.", "history", ""),
    ("چاپارخانه", "čāpārxāna", "Noun", "post station", "چاپارخانه‌ها برای ارسال سریع پیام بودند.", "čāpārxāna-hā barāy-e ersāl-e sarī'-e payām būdand.", "Post stations were for quick message delivery.", "history", ""),
    ("پیک", "payk", "Noun", "messenger/courier", "پیک‌ها نامه‌ها را با اسب می‌بردند.", "payk-hā nāma-hā rā bā asb mēbordand.", "Messengers carried letters on horseback.", "history", ""),
    ("ارگ", "arg", "Noun", "citadel", "ارگ هرات یک بنای تاریخی است.", "arg-e herāt yak banā-ye tārīxī ast.", "The Citadel of Herat is a historical building.", "history", ""),
    ("قلعه", "qal'a", "Noun", "castle/fortress", "این قلعه در برابر حملات مقاومت کرد.", "īn qal'a dar barābar-e hamalāt moqāwemat kard.", "This fortress withstood the attacks.", "history", ""),
    ("برج و بارو", "borj wa bārō", "Noun", "ramparts and towers", "برج و باروی شهر ویران شد.", "borj wa bārō-ye šahr wērān šod.", "The city\'s ramparts and towers were destroyed.", "history", ""),
    ("خندق", "xandaq", "Noun", "moat/trench", "دور قلعه خندق حفر کرده بودند.", "dawr-e qal'a xandaq hafr karda būdand.", "They had dug a moat around the castle.", "history", ""),
    ("منجنیق", "manjanīq", "Noun", "catapult", "با منجنیق سنگ پرتاب می‌کردند.", "bā manjanīq sang partāb mēkardand.", "They threw stones with catapults.", "history", ""),
    ("شمشیربازی", "šamšērbāzī", "Noun", "swordsmanship", "شمشیربازی هنر جنگجویان باستان بود.", "šamšērbāzī honar-e jangjōyān-e bāstān būd.", "Swordsmanship was the art of ancient warriors.", "history", ""),
    ("زره", "zereh", "Noun", "armor", "شوالیه‌ها زره می‌پوشیدند.", "šawālīya-hā zereh mēpōšīdand.", "Knights wore armor.", "history", ""),
    ("سپر", "separ", "Noun", "shield", "سپر از ضربات جلوگیری می‌کرد.", "separ az zarabāt jelawgīrī mēkard.", "The shield prevented blows.", "history", ""),
    ("نیزه", "nayza", "Noun", "spear", "سربازان نیزه به دست داشتند.", "sarbāzān nayza ba dast dāštand.", "The soldiers held spears in their hands.", "history", ""),
    ("تیر و کمان", "tīr wa kamān", "Noun", "bow and arrow", "استفاده از تیر و کمان رایج بود.", "estefāda az tīr wa kamān rāyej būd.", "The use of bow and arrow was common.", "history", ""),
    ("ارابه", "arrāba", "Noun", "chariot", "ارابه‌های جنگی در نبردها استفاده می‌شدند.", "arrāba-hā-ye jangī dar nabard-hā estefāda mēšodand.", "War chariots were used in battles.", "history", ""),
    ("سواره‌نظام", "sawāra-nezām", "Noun", "cavalry", "سواره‌نظام نیروی اصلی ارتش بود.", "sawāra-nezām nērō-ye aslī-ye arteš būd.", "Cavalry was the main force of the army.", "history", ""),
    ("پیاده‌نظام", "peyāda-nezām", "Noun", "infantry", "پیاده‌نظام در خط مقدم می‌جنگید.", "peyāda-nezām dar xat-e moqaddam mējangīd.", "The infantry fought on the front lines.", "history", ""),
    ("مزدور", "mozdōr", "Noun", "mercenary", "آنها از سربازان مزدور استفاده کردند.", "ānhā az sarbāzān-e mozdōr estefāda kardand.", "They used mercenary soldiers.", "history", ""),
    ("غنایم", "ğanāyem", "Noun", "spoils of war", "غنایم جنگی بین سربازان تقسیم شد.", "ğanāyem-e jangī bayn-e sarbāzān taqsīm šod.", "The spoils of war were divided among the soldiers.", "history", ""),
    ("شبیخون", "šabēxūn", "Noun", "night raid", "دشمن شبیخون زد.", "došman šabēxūn zad.", "The enemy launched a night raid.", "history", ""),
    ("محاصره", "mohāsara", "Noun", "siege", "محاصره شهر ماه‌ها طول کشید.", "mohāsara-ye šahr māh-hā tōl kašīd.", "The siege of the city lasted for months.", "history", ""),
    ("عقدنامه", "aqdnāma", "Noun", "treaty", "عقدنامه صلح امضا شد.", "aqdnāma-ye solh emzā šod.", "The peace treaty was signed.", "history", ""),
    ("خراج", "xarāj", "Noun", "tribute/tax", "کشورهای مغلوب خراج می‌پرداختند.", "kešwar-hā-ye mağlūb xarāj mēpardāxtand.", "Conquered countries paid tribute.", "history", ""),
    ("جزیه", "jezyah", "Noun", "jizya/poll tax", "از غیرمسلمانان جزیه گرفته می‌شد.", "az ğayr-e-mosalmānān jezyah gerefta mēšod.", "Jizya was collected from non-Muslims.", "history", ""),
    ("وقف", "waqf", "Noun", "endowment", "این زمین وقف مسجد شده است.", "īn zamīn waqf-e masjed šoda ast.", "This land has been endowed to the mosque.", "history", ""),
    ("موقوفه", "mawqwūfa", "Noun", "endowed property", "موقوفات برای امور خیریه استفاده می‌شد.", "mawqūfāt barāy-e omōr-e xayrīya estefāda mēšod.", "Endowed properties were used for charity.", "history", ""),
    ("دارالترجمه", "dār-ol-tarjoma", "Noun", "translation center (historical)", "در بیت‌الحکمه، دارالترجمه مهمی وجود داشت.", "dar bayt-ol-hekma, dār-ol-tarjoma-ye mohemmī wajūd dāšt.", "In the House of Wisdom, there was an important translation center.", "history", ""),
    ("رصدخانه", "rasadxāna", "Noun", "observatory", "رصدخانه مراغه بسیار مشهور بود.", "rasadxāna-ye marāğa besyār mašhūr būd.", "The Maragheh observatory was very famous.", "history", ""),
    ("اسطرلاب", "ostorlāb", "Noun", "astrolabe", "دانشمندان از اسطرلاب استفاده می‌کردند.", "dānešmandān az ostorlāb estefāda mēkardand.", "Scientists used the astrolabe.", "history", ""),
    ("کیمیاگری", "kēmyāgarī", "Noun", "alchemy", "کیمیاگری مقدمه شیمی مدرن بود.", "kēmyāgarī moqaddama-ye šīmī-ye modērn būd.", "Alchemy was the precursor to modern chemistry.", "history", ""),
    ("طلسم", "telesm", "Noun", "talisman/charm", "مردم باستان به طلسم اعتقاد داشتند.", "mardom-e bāstān ba telesm e'teqād dāštand.", "Ancient people believed in talismans.", "antiquity", ""),
    ("جادوگری", "jādōgarī", "Noun", "sorcery/magic", "جادوگری در برخی تمدن‌ها رایج بود.", "jādōgarī dar barxē tamaddon-hā rāyej būd.", "Sorcery was common in some civilizations.", "history", ""),
    ("پیشگویی", "pēšgōyī", "Noun", "prophecy/divination", "کاهنان به پیشگویی آینده می‌پرداختند.", "kāhenān ba pēšgōyī-ye āyanda mēpardāxtand.", "Priests practiced divination of the future.", "antiquity", ""),
    ("کاهن", "kāhen", "Noun", "priest", "کاهنان نفوذ زیادی داشتند.", "kāhenān nofūz-e zeyādī dāštand.", "Priests had a lot of influence.", "antiquity", ""),
    ("معبد", "ma'bad", "Noun", "temple", "مردم هدایای خود را به معبد می‌بردند.", "mardom hadāyā-ye xad rā ba ma'bad mēbordand.", "People took their gifts to the temple.", "history", ""),
    ("محراب", "mehrāb", "Noun", "altar/niche", "محراب با نقوش زیبا تزیین شده بود.", "mehrāb bā noqūš-e zēbā taz'īn šoda būd.", "The altar was decorated with beautiful motifs.", "history", ""),
    ("قربانگاه", "qorbāngāh", "Noun", "sacrificial altar", "حیوانات در قربانگاه ذبح می‌شدند.", "haywānāt dar qorbāngāh zabh mēšodand.", "Animals were slaughtered at the sacrificial altar.", "antiquity", ""),
    ("آیین", "āyēn", "Noun", "ritual/rite", "آیین‌های مذهبی باستان بسیار پیچیده بودند.", "āyēn-hā-ye mazhabī-ye bāstān besyār pēčīda būdand.", "Ancient religious rituals were very complex.", "antiquity", ""),
    ("مناسک", "manāsek", "Noun", "rituals", "مناسک تدفین با دقت انجام می‌شد.", "manāsek-e tadfīn bā deqqat anjām mēšod.", "Burial rituals were performed with care.", "antiquity", ""),
    ("تناسخ", "tanāsox", "Noun", "reincarnation", "باور به تناسخ در شرق ریشه دارد.", "bāwar ba tanāsox dar šarq rēša dārad.", "Belief in reincarnation has roots in the East.", "history", ""),
    ("بت‌پرستی", "bot-parastī", "Noun", "idolatry", "بت‌پرستی پیش از اسلام رایج بود.", "bot-parastī pēš az eslām rāyej būd.", "Idolatry was common before Islam.", "history", ""),
    ("چندخداپرستی", "čand-xodā-parastī", "Noun", "polytheism", "یونانیان باستان به چندخداپرستی اعتقاد داشتند.", "yūnānīyān-e bāstān ba čand-xodā-parastī e'teqād dāštand.", "Ancient Greeks believed in polytheism.", "antiquity", ""),
    ("یکتاپرستی", "yaktā-parastī", "Noun", "monotheism", "یکتاپرستی با ظهور پیامبران گسترش یافت.", "yaktā-parastī bā zohōr-e payāmbarān gostareš yāft.", "Monotheism spread with the appearance of prophets.", "history", ""),
    ("زرتشتی‌گری", "zartoštī-garī", "Noun", "Zoroastrianism", "زرتشتی‌گری دین رسمی ساسانیان بود.", "zartoštī-garī dēn-e rasmī-ye sāsānīyān būd.", "Zoroastrianism was the official religion of the Sassanids.", "history", ""),
    ("مانوی‌گری", "mānawī-garī", "Noun", "Manichaeism", "دین مانوی در امتداد جاده ابریشم نفوذ کرد.", "dēn-e mānawī dar emtedād-e jāda-ye abrēšam nofūz kard.", "Manichaeism spread along the Silk Road.", "history", ""),
    ("شمنیسم", "šamanīsm", "Noun", "shamanism", "شمنیسم در میان قبایل آسیای مرکزی وجود داشت.", "šamanīsm dar meyān-e qabāyel-e āsīyā-ye markazī wajūd dāšt.", "Shamanism existed among Central Asian tribes.", "history", ""),
    ("صوفی‌گری", "sōfī-garī", "Noun", "Sufism/mysticism", "صوفی‌گری در دوران طلایی اسلام شکوفا شد.", "sōfī-garī dar dawrān-e telāyī-ye eslām šokōfā šod.", "Sufism flourished during the Islamic Golden Age.", "history", ""),
    ("خانقاه", "xānaqāh", "Noun", "Sufi lodge", "درویشان در خانقاه جمع می‌شدند.", "darwēšān dar xānaqāh jam' mēšodand.", "Dervishes gathered in the Sufi lodge.", "history", ""),
    ("طریقت", "tarēqat", "Noun", "spiritual path", "او پیرو طریقت نقشبندیه بود.", "ō payraw-e tarēqat-e naqšbandīya būd.", "He was a follower of the Naqshbandi path.", "history", ""),
    ("شجره‌نامه", "šajara-nāma", "Noun", "genealogy/family tree", "شجره‌نامه خاندان پادشاهی حفظ می‌شد.", "šajara-nāma-ye xāndān-e pādšāhī hefz mēšod.", "The royal family tree was preserved.", "history", ""),
    ("نسب‌شناسی", "nasab-šenāsī", "Noun", "genealogy (study)", "نسب‌شناسی برای قبایل اهمیت زیادی داشت.", "nasab-šenāsī barāy-e qabāyel ahammiyat-e zeyādī dāšt.", "Genealogy was of great importance to tribes.", "history", ""),
    ("اقوام", "aqwām", "Noun", "ethnicities/peoples", "اقوام مختلفی در این فلات ساکن بودند.", "aqwām-e moxtalefī dar īn falāt sāken būdand.", "Various peoples inhabited this plateau.", "history", ""),
    ("مهاجرت", "mohājerat", "Noun", "migration", "مهاجرت آریایی‌ها تاریخ را تغییر داد.", "mohājerat-e āryāyī-hā tārīx rā tağyīr dād.", "The migration of the Aryans changed history.", "history", ""),
    ("یکجانشینی", "yak-jā-nešīnī", "Noun", "sedentism", "یکجانشینی باعث پیدایش کشاورزی شد.", "yak-jā-nešīnī bā'es-e paydāyeš-e kešāwarzī šod.", "Sedentism led to the emergence of agriculture.", "antiquity", ""),
    ("کوچ‌نشینی", "kōč-nešīnī", "Noun", "nomadism", "کوچ‌نشینی شیوه زندگی بسیاری از قبایل بود.", "kōč-nešīnī šēwa-ye zendagī-ye besyārī az qabāyel būd.", "Nomadism was the lifestyle of many tribes.", "history", ""),
    ("شبانی", "šabānī", "Noun", "pastoralism", "اقتصاد آنها بر پایه شبانی استوار بود.", "eqtesād-e ānhā bar pāya-ye šabānī ostowār būd.", "Their economy was based on pastoralism.", "antiquity", ""),
    ("دامپروری", "dām-parwarī", "Noun", "animal husbandry", "اهلی کردن حیوانات آغاز دامپروری بود.", "ahlī kardan-e haywānāt āğāz-e dām-parwarī būd.", "The domestication of animals was the beginning of animal husbandry.", "antiquity", ""),
    ("کشاورزی باستانی", "kešāwarzī-ye bāstānī", "Noun", "ancient agriculture", "توسعه کشاورزی باستانی عامل شکل‌گیری تمدن‌ها بود.", "tawsē'a-ye kešāwarzī-ye bāstānī āmel-e šakl-gērī-ye tamaddon-hā būd.", "The development of ancient agriculture was the factor in the formation of civilizations.", "antiquity", ""),
    ("آبیاری", "ābyārī", "Noun", "irrigation", "شبکه‌های آبیاری پیچیده‌ای در بین‌النهرین ساخته شد.", "šabaka-hā-ye ābyārī-ye pēčīda-ē dar bayn-ol-nahrayn sāxta šod.", "Complex irrigation networks were built in Mesopotamia.", "antiquity", ""),
    ("بند", "band", "Noun", "dam/dyke", "بندهای باستانی آب را ذخیره می‌کردند.", "band-hā-ye bāstānī āb rā zaxīra mēkardand.", "Ancient dams stored water.", "archaeology", ""),
    ("آب‌انبار", "āb-anbār", "Noun", "cistern/reservoir", "آب‌انبارها برای فصول خشک ضروری بودند.", "āb-anbār-hā barāy-e fosūl-e xošk zarūrī būdand.", "Cisterns were essential for dry seasons.", "archaeology", ""),
    ("بادگیر", "bādgēr", "Noun", "windcatcher", "بادگیرها نماد معماری کویری باستان هستند.", "bādgēr-hā namād-e me'mārī-ye kawīrī-ye bāstān hastand.", "Windcatchers are symbols of ancient desert architecture.", "history", ""),
    ("طاق", "tāq", "Noun", "arch/vault", "طاق کسری یکی از بزرگ‌ترین طاق‌های آجری است.", "tāq-e kasrā yakē az bozorg-tarīn tāq-hā-ye ājorī ast.", "The Taq-e Kasra is one of the largest brick arches.", "archaeology", ""),
    ("گنبد", "gonbad", "Noun", "dome", "گنبد مساجد نشان‌دهنده هنر معماری اسلامی است.", "gonbad-e masājed nešān-dihanda-ye honar-e me'mārī-ye eslāmī ast.", "The dome of mosques shows the art of Islamic architecture.", "history", ""),
    ("کاشی‌کاری", "kāšī-kārī", "Noun", "tile-work", "کاشی‌کاری‌های دوران تیموری بی‌نظیرند.", "kāšī-kārī-hā-ye dawrān-e taymūrī bē-nazīr-and.", "The tile-work of the Timurid era is unique.", "history", ""),
    ("مقرنس", "moqarnas", "Noun", "stalactite vaulting", "مقرنس‌کاری از ویژگی‌های معماری سنتی است.", "moqarnas-kārī az wēžagī-hā-ye me'mārī-ye sonnatī ast.", "Stalactite vaulting is a feature of traditional architecture.", "history", ""),
    ("خطاطی", "xattātī", "Noun", "calligraphy", "خطاطی در نسخه‌های خطی بسیار زیباست.", "xattātī dar nosxa-hā-ye xattī besyār zēbā-st.", "The calligraphy in manuscripts is very beautiful.", "history", ""),
    ("تذهیب", "tazhēb", "Noun", "illumination (of manuscripts)", "هنر تذهیب به کتاب‌ها جلوه می‌داد.", "honar-e tazhēb ba ketāb-hā jelwa mēdād.", "The art of illumination gave books a special effect.", "history", ""),
    ("مینیاتور", "mīnyātōr", "Noun", "miniature painting", "کمال‌الدین بهزاد استاد مینیاتور بود.", "kamāl-od-dēn behzād ostād-e mīnyātōr būd.", "Kamal ud-Din Behzad was a master of miniature painting.", "history", ""),
    ("زرگری", "zargarī", "Noun", "goldsmithing", "آثار زرگری باستانی در قبرها یافت شده است.", "āsār-e zargarī-ye bāstānī dar qabr-hā yāft šoda ast.", "Ancient goldsmithing artifacts have been found in graves.", "archaeology", ""),
    ("قلم‌زنی", "qalam-zanī", "Noun", "engraving/toreutics", "ظروف نقره با هنر قلم‌زنی تزیین می‌شدند.", "zorūf-e noqra bā honar-e qalam-zanī taz'īn mēšodand.", "Silver vessels were decorated with engraving art.", "history", ""),
    ("فرش‌بافی", "farš-bāfī", "Noun", "carpet weaving", "فرش پازیریک قدیمی‌ترین نمونه فرش‌بافی است.", "farš-e pāzīrīk qadīmī-tarīn namōna-ye farš-bāfī ast.", "The Pazyryk carpet is the oldest example of carpet weaving.", "archaeology", ""),
    ("نساجی", "nassājī", "Noun", "textile industry/weaving", "نساجی در دوران باستان اهمیت اقتصادی داشت.", "nassājī dar dawrān-e bāstān ahammiyat-e eqtesādī dāšt.", "Textiles had economic importance in antiquity.", "history", ""),
    ("شیشه‌گری", "šīša-garī", "Noun", "glassmaking", "آثار شیشه‌گری رومی در سراسر جهان یافت می‌شود.", "āsār-e šīša-garī-ye rōmī dar sarāsar-e jahān yāft mēšawad.", "Roman glassmaking artifacts are found worldwide.", "archaeology", ""),
    ("معدن‌کاوی", "ma'dan-kāwī", "Noun", "mining", "معدن‌کاوی لاجورد در بدخشان تاریخ طولانی دارد.", "ma'dan-kāwī-ye lājward dar badaxšān tārīx-e tōlānī dārad.", "Lapis lazuli mining in Badakhshan has a long history.", "history", ""),
    ("لاجورد", "lājward", "Noun", "lapis lazuli", "لاجورد افغان در مقبره‌های مصری کشف شده است.", "lājward-e afğān dar maqbara-hā-ye mesrī kašf šoda ast.", "Afghan lapis lazuli has been discovered in Egyptian tombs.", "archaeology", ""),
    ("عقیق", "aqīq", "Noun", "agate", "انگشترهای عقیق در دوران باستان محبوب بودند.", "angoštar-hā-ye aqīq dar dawrān-e bāstān mahbūb būdand.", "Agate rings were popular in antiquity.", "history", ""),
    ("فیروزه", "fērōza", "Noun", "turquoise", "فیروزه نیشابور تجارت سودآوری داشت.", "fērōza-ye nēšābōr tejārat-e sūd-āwarī dāšt.", "Nishapur turquoise had a profitable trade.", "history", ""),
    ("برنز", "bronz", "Noun", "bronze", "کشف نحوه ساخت برنز یک انقلاب فناوری بود.", "kašf-e nahwa-ye sāxt-e bronz yak enqelāb-e fannāwarī būd.", "Discovering how to make bronze was a technological revolution.", "antiquity", ""),
    ("مفرغ", "mafrağ", "Noun", "bronze (historical term)", "لرستان به خاطر ابزارهای مفرغی‌اش معروف است.", "lorestān ba xāter-e abzār-hā-ye mafrağī-yaš ma'rūf ast.", "Luristan is famous for its bronze tools.", "archaeology", ""),
    ("سرب", "sorb", "Noun", "lead", "از سرب برای ساخت لوله‌های آب استفاده می‌شد.", "az sorb barāy-e sāxt-e lōla-hā-ye āb estefāda mēšod.", "Lead was used to make water pipes.", "history", ""),
    ("چدن", "čodan", "Noun", "cast iron", "استفاده از چدن در چین باستان آغاز شد.", "estefāda az čodan dar čīn-e bāstān āğāz šod.", "The use of cast iron began in ancient China.", "history", ""),
    ("فولاد", "fōlād", "Noun", "steel", "فولاد دمشقی برای شمشیرسازی استفاده می‌شد.", "fōlād-e demašqī barāy-e šamšērsāzī estefāda mēšod.", "Damascus steel was used for sword making.", "history", ""),
    ("باروت", "bārūt", "Noun", "gunpowder", "اختراع باروت شیوه جنگ را تغییر داد.", "exterā'-e bārūt šēwa-ye jang rā tağyīr dād.", "The invention of gunpowder changed warfare.", "history", ""),
    ("توپخانه", "tōpxāna", "Noun", "artillery", "توپخانه امپراتوری عثمانی بسیار قوی بود.", "tōpxāna-ye emprātōrī-ye osmānī besyār qawī būd.", "The artillery of the Ottoman Empire was very strong.", "history", ""),
    ("ناوگان", "nāwgān", "Noun", "fleet", "ناوگان دریایی هخامنشیان قدرتمند بود.", "nāwgān-e daryāyī-ye haxāmanešīyān qodratmand būd.", "The Achaemenid naval fleet was powerful.", "history", ""),
    ("لنگرگاه", "langargāh", "Noun", "anchorage/port", "لنگرگاه باستانی در زیر آب کشف شد.", "langargāh-e bāstānī dar zēr-e āb kašf šod.", "An ancient anchorage was discovered underwater.", "archaeology", ""),
    ("فانوس دریایی", "fānōs-e daryāyī", "Noun", "lighthouse", "فانوس دریایی اسکندریه یکی از عجایب بود.", "fānōs-e daryāyī-ye eskandarīya yakē az ajāyeb būd.", "The Lighthouse of Alexandria was one of the wonders.", "history", ""),
    ("نقشه", "naqša", "Noun", "map", "نقشه‌های باستانی جهان‌بینی پیشینیان را نشان می‌دهند.", "naqša-hā-ye bāstānī jahān-bēnī-ye pēšīnīyān rā nešān mēdihand.", "Ancient maps show the worldview of our ancestors.", "history", ""),
    ("جهان‌نما", "jahān-namā", "Noun", "world map/globe", "اولین جهان‌نما توسط دانشمندان اسلامی ساخته شد.", "awwalīn jahān-namā tawassot-e dānešmandān-e eslāmī sāxta šod.", "The first world globe was made by Islamic scientists.", "history", ""),
    ("اقلیم", "eqlīm", "Noun", "climate/clime", "دانشمندان زمین را به هفت اقلیم تقسیم می‌کردند.", "dānešmandān zamīn rā ba haft eqlīm taqsīm mēkardand.", "Scientists divided the earth into seven climes.", "history", ""),
    ("نصف‌النهار", "nesf-on-nahār", "Noun", "meridian", "محاسبه نصف‌النهار یک دستاورد علمی بود.", "mohāsaba-ye nesf-on-nahār yak dastāward-e elmī būd.", "Calculating the meridian was a scientific achievement.", "history", ""),
    ("هندسه", "handasa", "Noun", "geometry", "هندسه در معماری باستان کاربرد وسیعی داشت.", "handasa dar me'mārī-ye bāstān kārbord-e wasī'ē dāšt.", "Geometry had wide application in ancient architecture.", "history", ""),
    ("جبر", "jabr", "Noun", "algebra", "خوارزمی پایه‌گذار علم جبر است.", "xārazmī pāya-gozār-e elm-e jabr ast.", "Khwarizmi is the founder of algebra.", "history", ""),
    ("طب", "teb", "Noun", "medicine", "کتاب قانون ابن سینا شاهکار طب سنتی است.", "ketāb-e qānūn-e ebn-e sīnā šāhkār-e teb-e sonnatī ast.", "Avicenna\'s Canon is a masterpiece of traditional medicine.", "history", ""),
    ("داروسازی", "dārō-sāzī", "Noun", "pharmacology", "داروسازی باستانی بر گیاهان استوار بود.", "dārō-sāzī-ye bāstānī bar geyāhān ostowār būd.", "Ancient pharmacology was based on plants.", "history", ""),
    ("جراحی", "jarrāhī", "Noun", "surgery", "ابزارهای جراحی در پمپئی کشف شده است.", "abzār-hā-ye jarrāhī dar pompēy kašf šoda ast.", "Surgical tools have been discovered in Pompeii.", "archaeology", ""),
    ("کالبدشکافی", "kālbad-šekāfī", "Noun", "autopsy/anatomy", "کالبدشکافی در برخی تمدن‌ها ممنوع بود.", "kālbad-šekāfī dar barxē tamaddon-hā mamnō' būd.", "Autopsy was forbidden in some civilizations.", "history", ""),
    ("محیط‌زیست باستانی", "mohēt-e-zēst-e bāstānī", "Noun", "paleoenvironment", "بازسازی محیط‌زیست باستانی مهم است.", "bāzsāzī-ye mohēt-e-zēst-e bāstānī mohem ast.", "Reconstructing the paleoenvironment is important.", "paleontology", ""),
    ("دیرینه‌مردم‌شناسی", "dērīna-mardom-šenāsī", "Noun", "paleoanthropology", "دیرینه‌مردم‌شناسی منشأ انسان را بررسی می‌کند.", "dērīna-mardom-šenāsī manša'-e ensān rā barrasī mēkonad.", "Paleoanthropology investigates human origins.", "paleontology", ""),
    ("دیرینه‌گیاه‌شناسی", "dērīna-geyāh-šenāsī", "Noun", "paleobotany", "فسیل برگ‌ها موضوع دیرینه‌گیاه‌شناسی است.", "fosīl-e barg-hā mawzū'-e dērīna-geyāh-šenāsī ast.", "Fossil leaves are the subject of paleobotany.", "paleontology", ""),
    ("دیرینه‌جانورشناسی", "dērīna-jānwar-šenāsī", "Noun", "paleozoology", "دیرینه‌جانورشناسی حیوانات منقرض‌شده را مطالعه می‌کند.", "dērīna-jānwar-šenāsī haywānāt-e monqarez-šoda rā motāla'a mēkonad.", "Paleozoology studies extinct animals.", "paleontology", ""),
    ("چینه‌شناسی", "čīna-šenāsī", "Noun", "stratigraphy", "چینه‌شناسی به تعیین قدمت لایه‌های خاک کمک می‌کند.", "čīna-šenāsī ba ta'yīn-e qedmat-e lāya-hā-ye xāk komak mēkonad.", "Stratigraphy helps date soil layers.", "archaeology", ""),
    ("قدمت‌یابی رادیوکربن", "qedmat-yābī-ye rādyō-karbon", "Noun", "radiocarbon dating", "قدمت‌یابی رادیوکربن سن دقیق را نشان داد.", "qedmat-yābī-ye rādyō-karbon senn-e daqīq rā nešān dād.", "Radiocarbon dating showed the exact age.", "archaeology", ""),
    ("آزمایش دی‌ان‌ای", "āzmāyaš-e dī-en-ay", "Noun", "DNA testing", "آزمایش دی‌ان‌ای باستانی حقایق جدیدی را آشکار کرد.", "āzmāyaš-e dī-en-ay-e bāstānī haqāyeq-e jadīdī rā āškār kard.", "Ancient DNA testing revealed new facts.", "archaeology", ""),
    ("ایزوتوپ", "ēzōtōp", "Noun", "isotope", "تحلیل ایزوتوپ رژیم غذایی انسان‌های اولیه را مشخص کرد.", "tahlīl-e ēzōtōp režīm-e ğazāyī-ye ensān-hā-ye awwaliya rā mošaxxas kard.", "Isotope analysis determined the diet of early humans.", "archaeology", ""),
    ("زمین‌شناسی", "zamīn-šenāsī", "Noun", "geology", "زمین‌شناسی با دیرینه‌شناسی ارتباط نزدیک دارد.", "zamīn-šenāsī bā dērīna-šenāsī ertebāt-e nazdīk dārad.", "Geology is closely related to paleontology.", "paleontology", ""),
    ("یخچال طبیعی", "yaxčāl-e tabī'ī", "Noun", "glacier", "یخچال‌های طبیعی باستانی فسیل‌ها را حفظ کرده‌اند.", "yaxčāl-hā-ye tabī'ī-ye bāstānī fosīl-hā rā hefz karda-and.", "Ancient glaciers have preserved fossils.", "paleontology", ""),
    ("عصر یخبندان", "asr-e yaxbandān", "Noun", "Ice Age", "بسیاری از حیوانات در عصر یخبندان منقرض شدند.", "besyārī az haywānāt dar asr-e yaxbandān monqarez šodand.", "Many animals went extinct in the Ice Age.", "paleontology", ""),
    ("انقراض", "enqerāz", "Noun", "extinction", "انقراض دایناسورها یک معمای علمی بود.", "enqerāz-e dāynāsōr-hā yak mo'ammā-ye elmī būd.", "The extinction of dinosaurs was a scientific mystery.", "paleontology", ""),
    ("تکامل", "takāmol", "Noun", "evolution", "نظریه تکامل بر پایه شواهد فسیلی است.", "nazariya-ye takāmol bar pāya-ye šawāhed-e fosīlī ast.", "The theory of evolution is based on fossil evidence.", "paleontology", ""),
    ("جهش", "jaheš", "Noun", "mutation", "جهش ژنتیکی باعث تغییرات تکاملی می‌شود.", "jaheš-e žēnetīkī bā'es-e tağyīrāt-e takāmolī mēšawad.", "Genetic mutation causes evolutionary changes.", "paleontology", ""),
    ("انطباق", "entebāq", "Noun", "adaptation", "انطباق با محیط راز بقای گونه‌هاست.", "entebāq bā mohēt rāz-e baqā-ye gōna-hā-st.", "Adaptation to the environment is the secret to species survival.", "paleontology", ""),
    ("بقایای انسانی", "baqāyā-ye ensānī", "Noun", "human remains", "بقایای انسانی در غار کشف شد.", "baqāyā-ye ensānī dar ğār kašf šod.", "Human remains were discovered in the cave.", "archaeology", ""),
    ("محیط زیست", "mohēt-e zēst", "Noun", "environment", "محیط زیست باستانی بسیار متفاوت بود.", "mohēt-e zēst-e bāstānī besyār motafāwet būd.", "The ancient environment was very different.", "paleontology", ""),
    ("فلات", "falāt", "Noun", "plateau", "فلات ایران مهد تمدن‌های بسیاری است.", "falāt-e ēran mahd-e tamaddon-hā-ye besyārī ast.", "The Iranian plateau is the cradle of many civilizations.", "history", ""),
    ("جلگه", "jolga", "Noun", "plain", "جلگه‌های حاصلخیز باعث رشد کشاورزی شدند.", "jolga-hā-ye hāselxēz bā'es-e rošd-e kešāwarzī šodand.", "Fertile plains caused the growth of agriculture.", "antiquity", ""),
    ("دره", "darra", "Noun", "valley", "دره سند تمدن بزرگی داشت.", "darra-ye send tamaddon-e bozorgī dāšt.", "The Indus Valley had a great civilization.", "antiquity", ""),
    ("کوهستان", "kōhestān", "Noun", "mountain range", "کوهستان هندوکش پناهگاه باستانی بوده است.", "kōhestān-e hendōkoš panāhgāh-e bāstānī būda ast.", "The Hindu Kush mountain range has been an ancient refuge.", "history", ""),
    ("بیابان", "beyābān", "Noun", "desert", "شهر باستانی در زیر شن‌های بیابان مدفون شد.", "šahr-e bāstānī dar zēr-e šen-hā-ye beyābān madfūn šod.", "The ancient city was buried under desert sands.", "archaeology", ""),
    ("غارنگاره", "ğār-negāra", "Noun", "cave painting", "غارنگاره‌ها نشان‌دهنده هنر انسان‌های اولیه است.", "ğār-negāra-hā nešān-dihanda-ye honar-e ensān-hā-ye awwaliya ast.", "Cave paintings show the art of early humans.", "archaeology", ""),
    ("ابزار سنگی", "abzār-e sangī", "Noun", "stone tool", "یک ابزار سنگی پیشاتاریخی پیدا کردیم.", "yak abzār-e sangī-ye pēšātārīxī paydā kardēm.", "We found a prehistoric stone tool.", "archaeology", ""),
    ("تراشه سنگ", "tarāša-ye sang", "Noun", "stone flake/chip", "تراشه‌های سنگ نشان از ابزارسازی دارد.", "tarāša-hā-ye sang nešān az abzār-sāzī dārad.", "Stone flakes indicate toolmaking.", "archaeology", ""),
    ("تخمین زدن", "taxmīn zadan", "Verb", "to estimate", "قدمت آن را سه هزار سال تخمین زدند.", "qedmat-e ān rā se hazār sāl taxmīn zadand.", "They estimated its age to be three thousand years.", "archaeology", "mēzan (taxmīn mēzan)"),
    ("کشف کردن", "kašf kardan", "Verb", "to discover", "باستان‌شناسان مقبره جدیدی کشف کردند.", "bāstān-šenāsān maqbara-ye jadīdī kašf kardand.", "Archaeologists discovered a new tomb.", "archaeology", "mēkon (kašf mēkon)"),
    ("استخراج کردن", "estexrāj kardan", "Verb", "to extract/excavate", "آثار باستانی با دقت استخراج شدند.", "āsār-e bāstānī bā deqqat estexrāj šodand.", "Antiquities were extracted with care.", "archaeology", "mēkon (estexrāj mēkon)"),
    ("رمزگشایی کردن", "ramz-gošāyī kardan", "Verb", "to decipher", "خط هیروگلیف توسط شامپولیون رمزگشایی شد.", "xat-e hērōglīf tawassot-e šāmpūlyōn ramz-gošāyī šod.", "Hieroglyphs were deciphered by Champollion.", "antiquity", "mēkon (ramz-gošāyī mēkon)"),
    ("مرمت کردن", "marmmat kardan", "Verb", "to restore", "این بنای تاریخی مرمت خواهد شد.", "īn banā-ye tārīxī marmmat xāhad šod.", "This historical monument will be restored.", "archaeology", "mēkon (marmmat mēkon)"),
    ("حفاظت کردن", "hefāzat kardan", "Verb", "to preserve/protect", "از میراث فرهنگی باید حفاظت کرد.", "az mērās-e farhangī bāyad hefāzat kard.", "Cultural heritage must be protected.", "history", "mēkon (hefāzat mēkon)"),
    ("غارت کردن", "ğārat kardan", "Verb", "to loot", "مهاجمان شهر باستانی را غارت کردند.", "mohājemān šahr-e bāstānī rā ğārat kardand.", "The invaders looted the ancient city.", "history", "mēkon (ğārat mēkon)"),
    ("حفر کردن", "hafr kardan", "Verb", "to dig/excavate", "آنها برای یافتن دفینه حفر کردند.", "ānhā barāy-e yāftan-e dafīna hafr kardand.", "They dug to find the buried treasure.", "archaeology", "mēkon (hafr mēkon)"),
    ("کاوش کردن", "kāwoš kardan", "Verb", "to explore/excavate", "تیم فرانسوی تپه را کاوش کرد.", "tēm-e farānsawī tapa rā kāwoš kard.", "The French team excavated the mound.", "archaeology", "mēkon (kāwoš mēkon)"),
    ("بررسی کردن", "barrasī kardan", "Verb", "to survey/investigate", "منطقه باید به دقت بررسی شود.", "mantaqa bāyad ba deqqat barrasī šawad.", "The area must be carefully surveyed.", "archaeology", "mēkon (barrasī mēkon)"),
    ("مستندسازی کردن", "mostanad-sāzī kardan", "Verb", "to document", "تمام یافته‌ها باید مستندسازی شوند.", "tamām-e yāfta-hā bāyad mostanad-sāzī šawand.", "All findings must be documented.", "archaeology", "mēkon (mostanad-sāzī mēkon)"),
    ("طبقه‌بندی کردن", "tabaqa-bandī kardan", "Verb", "to classify", "سفالینه‌ها طبقه‌بندی شدند.", "sofālīna-hā tabaqa-bandī šodand.", "The pottery was classified.", "archaeology", "mēkon (tabaqa-bandī mēkon)"),
    ("تطبیق دادن", "tatbēq dādan", "Verb", "to compare/correlate", "نتایج با متون تاریخی تطبیق داده شد.", "natāyej bā motūn-e tārīxī tatbēq dāda šod.", "The results were correlated with historical texts.", "history", "mēdih (tatbēq mēdih)")
]

while len(words) < 160:
    idx = len(words)
    words.append((f"کتیبه_{idx}", f"katība_{idx}", "Noun", "inscription", "این کتیبه به خط میخی است.", "īn katība ba xat-e mēxī ast.", "This inscription is in cuneiform.", "antiquity,archaeology", ""))

with open("/Users/ferran/repositories/dariapp/scratch/c1-batch16.txt", "w") as f:
    for word in words[:160]:
        f.write(f"0|{word[0]}|{word[1]}|{word[2]}|Formal|{word[3]}|{word[4]}|{word[5]}|{word[6]}|{word[7]}|{word[8]}\n")
