import sys
import math

words = """0|جامعه‌شناسی|jami'a-shenasi|noun|formal|sociology|جامعه‌شناسی به تحلیل ساختارهای قدرت کمک می‌کند.|jami'a-shenasi ba tahlil-e sakhtar-ha-ye qudrat kumak mekunad.|Sociology aids in analyzing power structures.|ComplexSociology|
0|انسان‌شناسی|insan-shenasi|noun|formal|anthropology|انسان‌شناسی به بررسی تکامل جوامع می‌پردازد.|insan-shenasi ba barrasi-e takamul-e jawami' mepardazad.|Anthropology deals with the evolution of societies.|AnthropologicalConcepts|
0|جمعیت‌شناسی|jam'iyat-shenasi|noun|formal|demographics|جمعیت‌شناسی اقتصادی یک شاخه مهم است.|jam'iyat-shenasi-e iqtisadi yak shakha-e muhimm ast.|Economic demographics is an important branch.|Demographics|
0|فرهنگ‌سازی|farhang-sazi|noun|formal|culture building|فرهنگ‌سازی برای حفاظت از محیط زیست الزامی است.|farhang-sazi baraye hifazat az muhit-e zist ilzami ast.|Culture building is mandatory for environmental protection.|CulturalStudies|
0|همسان‌سازی|hamsan-sazi|noun|formal|assimilation|سیاست‌های همسان‌سازی غالباً با مقاومت روبرو می‌شوند.|siyasat-ha-ye hamsan-sazi ghaliban ba muqawamat rubaru meshawand.|Assimilation policies often face resistance.|ComplexSociology|
0|بیگانه‌گرایی|begana-garayi|noun|formal|xenocentrism|بیگانه‌گرایی به مصرف‌گرایی غربی دامن می‌زند.|begana-garayi ba masraf-garayi-e gharbi daman mezanad.|Xenocentrism fuels Western consumerism.|CulturalStudies|
0|قوم‌مداری|qawm-madari|noun|formal|ethnocentrism|قوم‌مداری در تضاد با کثرت‌گرایی فرهنگی است.|qawm-madari dar tazad ba kasrat-garayi-e farhangi ast.|Ethnocentrism is in conflict with cultural pluralism.|AnthropologicalConcepts|
0|هنجارشکنی|hanjar-shekani|noun|formal|norm-breaking|هنجارشکنی می‌تواند کاتالیزور تغییر اجتماعی باشد.|hanjar-shekani metawanad katalizor-e taghir-e ijtima'i bashad.|Norm-breaking can be a catalyst for social change.|ComplexSociology|
0|طبقه اجتماعی|tabaqa-e ijtima'i|noun|formal|social class|تبعیض بر اساس طبقه اجتماعی هنوز وجود دارد.|tab'iz bar asas-e tabaqa-e ijtima'i hanoz wujud darad.|Discrimination based on social class still exists.|ComplexSociology|
0|تحرک اجتماعی|taharruk-e ijtima'i|noun|formal|social mobility|آموزش کلید تحرک اجتماعی است.|amuzish kilid-e taharruk-e ijtima'i ast.|Education is the key to social mobility.|ComplexSociology|
0|نابرابری|na-barabari|noun|formal|inequality|نابرابری اقتصادی منجر به شکاف طبقاتی می‌شود.|na-barabari-e iqtisadi munjir ba shikaf-e tabaqati meshawad.|Economic inequality leads to a class divide.|ComplexSociology|
0|تبعیض ساختاری|tab'iz-e sakhtari|noun|formal|structural discrimination|تبعیض ساختاری نیازمند اصلاحات نهادی است.|tab'iz-e sakhtari niyazmand-e islahat-e nahadi ast.|Structural discrimination requires institutional reforms.|ComplexSociology|
0|حاشیه‌نشینی|hashiya-neshini|noun|formal|marginalization|حاشیه‌نشینی از پیامدهای توسعه نامتوازن است.|hashiya-neshini az payamad-ha-ye tawsi'a-e na-mutawazin ast.|Marginalization is a consequence of uneven development.|Demographics|
0|همبستگی|hambastagi|noun|formal|solidarity|همبستگی ملی در مواقع بحران تقویت می‌شود.|hambastagi-e milli dar mawaqi'-e buhran taqwiyat meshawad.|National solidarity is strengthened during crises.|ComplexSociology|
0|گسست نسل‌ها|gusast-e nasl-ha|noun|formal|generation gap|گسست نسل‌ها باعث سوءتفاهم می‌شود.|gusast-e nasl-ha ba'is-e su-e tafahum meshawad.|The generation gap causes misunderstanding.|CulturalStudies|
0|تضاد طبقاتی|tazad-e tabaqati|noun|formal|class conflict|تضاد طبقاتی ریشه در توزیع ناعادلانه ثروت دارد.|tazad-e tabaqati resha dar tawzi'-e na-adilana-e sarwat darad.|Class conflict is rooted in unequal wealth distribution.|ComplexSociology|
0|سرمایه فرهنگی|sarmaya-e farhangi|noun|formal|cultural capital|سرمایه فرهنگی در موفقیت تحصیلی نقش دارد.|sarmaya-e farhangi dar muwaffaqiyat-e tahsili naqsh darad.|Cultural capital plays a role in academic success.|CulturalStudies|
0|کلان‌شهر|kalan-shahr|noun|formal|metropolis|زندگی در کلان‌شهرها چالش‌های روانی دارد.|zindagi dar kalan-shahr-ha chalish-ha-ye rawani darad.|Life in metropolises has psychological challenges.|Demographics|
0|شهرنشینی|shahr-neshini|noun|formal|urbanization|سرعت شهرنشینی در کشورهای در حال توسعه بالا است.|sur'at-e shahr-neshini dar kishwar-ha-ye dar hal-e tawsi'a bala ast.|The rate of urbanization is high in developing countries.|Demographics|
0|مهاجرت نخبگان|mohajirat-e nukhbagan|noun|formal|brain drain|مهاجرت نخبگان یک معضل جدی است.|mohajirat-e nukhbagan yak mu'zal-e jiddi ast.|Brain drain is a serious dilemma.|Demographics|
0|بافت جمعیتی|baft-e jam'iyati|noun|formal|demographic structure|بافت جمعیتی کشور در حال پیر شدن است.|baft-e jam'iyati-e kishwar dar hal-e per shudan ast.|The country's demographic structure is aging.|Demographics|
0|امید به زندگی|umed ba zindagi|noun|formal|life expectancy|امید به زندگی با بهبود بهداشت افزایش یافته است.|umed ba zindagi ba bihbudi-e bihdasht afzayish yafta ast.|Life expectancy has increased with better healthcare.|Demographics|
0|مرگ‌ومیر|marg-o-mir|noun|formal|mortality|نرخ مرگ‌ومیر نوزادان کاهش یافته است.|nirkh-e marg-o-mir-e nawzadan kahish yafta ast.|The infant mortality rate has decreased.|Demographics|
0|زادولد|zad-o-walad|noun|formal|birth rate|کاهش زادولد یک بحران جمعیتی است.|kahish-e zad-o-walad yak buhran-e jam'iyati ast.|The decline in birth rate is a demographic crisis.|Demographics|
0|باروری|bar-wari|noun|formal|fertility|نرخ باروری در مناطق روستایی بیشتر است.|nirkh-e bar-wari dar manatiq-e rustayi beshtar ast.|The fertility rate is higher in rural areas.|Demographics|
0|سالمندی|salmandi|noun|formal|aging|پدیده سالمندی نیازمند برنامه‌ریزی دقیق است.|padida-e salmandi niyazmand-e barnama-rezi-e daqiq ast.|The aging phenomenon requires careful planning.|Demographics|
0|ساختارگرایی|sakhtar-garayi|noun|formal|structuralism|ساختارگرایی در زبان‌شناسی نیز کاربرد دارد.|sakhtar-garayi dar zaban-shenasi nez karburd darad.|Structuralism is also applied in linguistics.|AnthropologicalConcepts|
0|کارکردگرایی|karkard-garayi|noun|formal|functionalism|کارکردگرایی به نقش نهادها توجه می‌کند.|karkard-garayi ba naqsh-e nahad-ha tawajjuh mekunad.|Functionalism pays attention to the role of institutions.|ComplexSociology|
0|پدیدارشناسی|padidar-shenasi|noun|formal|phenomenology|پدیدارشناسی به تجربه زیسته می‌پردازد.|padidar-shenasi ba tajruba-e zesta mepardazad.|Phenomenology deals with lived experience.|AnthropologicalConcepts|
0|نشانه‌شناسی|neshana-shenasi|noun|formal|semiotics|نشانه‌شناسی فرهنگی برای درک هنر محلی مهم است.|neshana-shenasi-e farhangi baraye dark-e hunar-e mahalli muhimm ast.|Cultural semiotics is important for understanding local art.|CulturalStudies|
0|اسطوره‌شناسی|ustura-shenasi|noun|formal|mythology|اسطوره‌شناسی باورهای کهن را بازتاب می‌دهد.|ustura-shenasi bawar-ha-ye kuhan ra baztab medahad.|Mythology reflects ancient beliefs.|AnthropologicalConcepts|
0|آیین گذار|ayin-e guzar|noun|formal|rite of passage|آیین گذار مرحله‌ای مهم در زندگی جوانان است.|ayin-e guzar marhala-e muhimm dar zindagi-e jawanan ast.|The rite of passage is an important stage in young people's lives.|AnthropologicalConcepts|
0|تابو|tabu|noun|formal|taboo|شکستن این تابو شهامت می‌خواهد.|shekastan-e in tabu shahamat mekhwahad.|Breaking this taboo requires courage.|CulturalStudies|
0|توتم‌پرستی|totam-parasti|noun|formal|totemism|توتم‌پرستی در قبایل باستانی رایج بود.|totam-parasti dar qabayil-e bastani rayij bud.|Totemism was common in ancient tribes.|AnthropologicalConcepts|
0|نیاکان‌پرستی|niyakan-parasti|noun|formal|ancestor worship|نیاکان‌پرستی هنوز در برخی جوامع دیده می‌شود.|niyakan-parasti hanoz dar barkhi jawami' deda meshawad.|Ancestor worship is still seen in some societies.|AnthropologicalConcepts|
0|مادرسالاری|madar-salari|noun|formal|matriarchy|شواهد اندکی از جوامع مادرسالاری در تاریخ وجود دارد.|shawahid-e andaki az jawami'-e madar-salari dar tarikh wujud darad.|There is little evidence of matriarchal societies in history.|AnthropologicalConcepts|
0|پدرسالاری|padar-salari|noun|formal|patriarchy|ساختار پدرسالاری مانع پیشرفت زنان است.|sakhtar-e padar-salari mani'-e peshraft-e zanan ast.|The patriarchal structure hinders women's progress.|ComplexSociology|
0|خویشاوندی|kheshawandi|noun|formal|kinship|روابط خویشاوندی در افغانستان بسیار مستحکم است.|rawabit-e kheshawandi dar afghanistan bisyar mustahkam ast.|Kinship ties are very strong in Afghanistan.|AnthropologicalConcepts|
0|چندهمسری|chand-hamsari|noun|formal|polygamy|چندهمسری در برخی مناطق هنوز قانوناً مجاز است.|chand-hamsari dar barkhi manatiq hanoz qanunan mujaz ast.|Polygamy is still legally permitted in some regions.|AnthropologicalConcepts|
0|تک‌همسری|tak-hamsari|noun|formal|monogamy|تک‌همسری الگوی غالب تشکیل خانواده است.|tak-hamsari olgu-ye ghalib-e tashkil-e khanawada ast.|Monogamy is the dominant pattern of family formation.|ComplexSociology|
0|مردم‌نگاری|mardum-negari|noun|formal|ethnography|مردم‌نگاری نیازمند حضور میدانی پژوهشگر است.|mardum-negari niyazmand-e huzur-e maydani-e pazhohishgar ast.|Ethnography requires the researcher's fieldwork presence.|AnthropologicalConcepts|
0|خرده‌فرهنگ|khurda-farhang|noun|formal|subculture|هر خرده‌فرهنگ هنجارهای خاص خود را دارد.|har khurda-farhang hanjar-ha-ye khas-e khud ra darad.|Each subculture has its own specific norms.|CulturalStudies|
0|ضدفرهنگ|zidd-e farhang|noun|formal|counterculture|جنبش‌های ضدفرهنگ ارزش‌های حاکم را به چالش می‌کشند.|jumbish-ha-ye zidd-e farhang arzish-ha-ye hakim ra ba chalish mekeshand.|Counterculture movements challenge the prevailing values.|CulturalStudies|
0|نسبیت فرهنگی|nisbiyat-e farhangi|noun|formal|cultural relativism|نسبیت فرهنگی به درک متقابل کمک می‌کند.|nisbiyat-e farhangi ba dark-e mutaqabil kumak mekunad.|Cultural relativism helps with mutual understanding.|CulturalStudies|
0|شوک فرهنگی|shok-e farhangi|noun|formal|culture shock|مهاجران معمولاً در ابتدا دچار شوک فرهنگی می‌شوند.|muhajiran ma'mulan dar ibtida duchar-e shok-e farhangi meshawand.|Immigrants usually experience culture shock initially.|CulturalStudies|
0|جهان‌بینی|jahan-bini|noun|formal|worldview|جهان‌بینی افراد تحت تاثیر تربیت آنهاست.|jahan-bini-e afrad taht-e tasir-e tarbiyat-e anha-st.|People's worldview is influenced by their upbringing.|CulturalStudies|
0|ایدئولوژی|idi'olozhi|noun|formal|ideology|هیچ ایدئولوژی نباید با زور تحمیل شود.|hech idi'olozhi nabayad ba zor tahmil shawad.|No ideology should be imposed by force.|ComplexSociology|
0|سکولاریسم|sekularism|noun|formal|secularism|سکولاریسم بر جدایی دین از سیاست تاکید دارد.|sekularism bar judayi-e din az siyasat takid darad.|Secularism emphasizes the separation of religion from politics.|ComplexSociology|
0|عرفی‌شدن|urfi-shudan|noun|formal|secularization|روند عرفی‌شدن در جوامع مدرن اجتناب‌ناپذیر است.|rawand-e urfi-shudan dar jawami'-e mudern ijtinab-napazir ast.|The process of secularization is inevitable in modern societies.|ComplexSociology|
0|سنت‌گرایی|sunnat-garayi|noun|formal|traditionalism|سنت‌گرایی افراطی مانع نوسازی می‌شود.|sunnat-garayi-e ifrati mani'-e naw-sazi meshawad.|Extreme traditionalism hinders modernization.|CulturalStudies|
0|تجدد|tajaddud|noun|formal|modernity|رویارویی سنت و تجدد همواره چالش‌برانگیز بوده است.|ruyaruyi-e sunnat wa tajaddud hamwara chalish-barangez buda ast.|The confrontation of tradition and modernity has always been challenging.|CulturalStudies|
0|پسااستعمارگرایی|pasa-isti'mar-garayi|noun|formal|postcolonialism|ادبیات پسااستعمارگرایی به هویت‌های سرکوب‌شده می‌پردازد.|adabiyat-e pasa-isti'mar-garayi ba huwiyat-ha-ye sarkub-shuda mepardazad.|Postcolonial literature addresses suppressed identities.|ComplexSociology|
0|جهانی‌شدن|jahani-shudan|noun|formal|globalization|جهانی‌شدن مرزهای فرهنگی را کمرنگ کرده است.|jahani-shudan marz-ha-ye farhangi ra kam-rang karda ast.|Globalization has blurred cultural boundaries.|CulturalStudies|
0|بومی‌سازی|bumi-sazi|noun|formal|localization|بومی‌سازی فناوری نیازمند زیرساخت است.|bumi-sazi-e fanawari niyazmand-e zer-sakht ast.|The localization of technology requires infrastructure.|CulturalStudies|
0|تنوع فرهنگی|tanawwo-e farhangi|noun|formal|cultural diversity|تنوع فرهنگی غنای یک جامعه محسوب می‌شود.|tanawwo-e farhangi ghina-ye yak jami'a mahsub meshawad.|Cultural diversity is considered the richness of a society.|CulturalStudies|
0|چندفرهنگی|chand-farhangi|noun|formal|multiculturalism|سیاست چندفرهنگی حقوق اقلیت‌ها را تضمین می‌کند.|siyasat-e chand-farhangi huquq-e aqalliyat-ha ra tazmin mekunad.|The policy of multiculturalism guarantees the rights of minorities.|CulturalStudies|
0|هویت ملی|huwiyat-e milli|noun|formal|national identity|زبان مشترک یکی از ارکان هویت ملی است.|zaban-e mushtarak yaki az arkan-e huwiyat-e milli ast.|A common language is one of the pillars of national identity.|CulturalStudies|
0|بحران هویت|buhran-e huwiyat|noun|formal|identity crisis|جوانان مهاجر اغلب با بحران هویت مواجه‌اند.|jawanan-e muhajir aghlab ba buhran-e huwiyat muwaji-and.|Immigrant youth often face an identity crisis.|ComplexSociology|
0|بیگانگی|beganagi|noun|formal|alienation|بیگانگی اجتماعی منجر به انزوا می‌شود.|beganagi-e ijtima'i munjir ba inzwa meshawad.|Social alienation leads to isolation.|ComplexSociology|
0|آنومی|anomi|noun|formal|anomie|در شرایط آنومی، قواعد اجتماعی بی‌اعتبار می‌شوند.|dar sharayit-e anomi, qawa'id-e ijtima'i be-i'tibar meshawand.|In a state of anomie, social rules become invalid.|ComplexSociology|
0|سرمایه‌داری|sarmaya-dari|noun|formal|capitalism|نظام سرمایه‌داری بر اساس بازار آزاد عمل می‌کند.|nizam-e sarmaya-dari bar asas-e bazar-e azad amal mekunad.|The capitalist system operates based on a free market.|ComplexSociology|
0|سوسیالیسم|sosiyalism|noun|formal|socialism|ایده‌های سوسیالیسم در پی عدالت اقتصادی هستند.|ida-ha-ye sosiyalism dar pay-e adalat-e iqtisadi hastand.|Socialist ideas pursue economic justice.|ComplexSociology|
0|پرولتاریا|proletariya|noun|formal|proletariat|طبقه پرولتاریا در انقلاب‌های صنعتی نقش داشت.|tabaqa-e proletariya dar inqilab-ha-ye san'ati naqsh dasht.|The proletariat class played a role in industrial revolutions.|ComplexSociology|
0|بورژوازی|burzhwazi|noun|formal|bourgeoisie|ارزش‌های بورژوازی بر فردگرایی تاکید دارند.|arzish-ha-ye burzhwazi bar fard-garayi takid darand.|Bourgeois values emphasize individualism.|ComplexSociology|
0|استثمار|istismar|noun|formal|exploitation|استثمار کارگران در کارخانه‌های غیرقانونی رایج است.|istismar-e kargar-an dar karkhana-ha-ye ghayr-e qanuni rayij ast.|Exploitation of workers is common in illegal factories.|ComplexSociology|
0|ازخودبیگانگی|az-khud-beganagi|noun|formal|self-alienation|کار ماشینی باعث ازخودبیگانگی انسان می‌شود.|kar-e mashini ba'is-e az-khud-beganagi-e insan meshawad.|Mechanical labor causes self-alienation of human beings.|ComplexSociology|
0|رفاه اجتماعی|rifah-e ijtima'i|noun|formal|social welfare|تامین رفاه اجتماعی از وظایف دولت است.|tamin-e rifah-e ijtima'i az wazayif-e dawlat ast.|Providing social welfare is among the government's duties.|ComplexSociology|
0|فقر مطلق|faqr-e mutlaq|noun|formal|absolute poverty|ریشه‌کن کردن فقر مطلق یک هدف جهانی است.|resha-kan kardan-e faqr-e mutlaq yak hadaf-e jahani ast.|Eradicating absolute poverty is a global goal.|Demographics|
0|خط فقر|khatt-e faqr|noun|formal|poverty line|بسیاری از خانوارها زیر خط فقر زندگی می‌کنند.|bisyari az khanawar-ha zer-e khatt-e faqr zindagi mekunand.|Many households live below the poverty line.|Demographics|
0|محرومیت|mahrumiyat|noun|formal|deprivation|محرومیت از تحصیل یک نقض حقوق بشر است.|mahrumiyat az tahsil yak naqz-e huquq-e bashar ast.|Deprivation of education is a human rights violation.|ComplexSociology|
0|نخبگان|nukhbagan|noun|formal|elites|نخبگان سیاسی در تصمیم‌گیری‌ها نفوذ دارند.|nukhbagan-e siyasi dar tasmimgiri-ha nufuz darand.|Political elites have influence in decision-making.|ComplexSociology|
0|عوام‌گرایی|awam-garayi|noun|formal|populism|عوام‌گرایی در دموکراسی‌های شکننده رشد می‌کند.|awam-garayi dar demokrasi-ha-ye shikananda rushd mekunad.|Populism grows in fragile democracies.|ComplexSociology|
0|توده‌گرایی|tuda-garayi|noun|formal|massification|توده‌گرایی فرهنگی باعث افت کیفیت هنر می‌شود.|tuda-garayi-e farhangi ba'is-e uft-e kayfiyat-e hunar meshawad.|Cultural massification causes a decline in art quality.|CulturalStudies|
0|جامعه مدنی|jami'a-e madani|noun|formal|civil society|نهادهای جامعه مدنی در نظارت بر قدرت مهم‌اند.|nahad-ha-ye jami'a-e madani dar nizarat bar qudrat muhimm-and.|Civil society institutions are important in monitoring power.|ComplexSociology|
0|افکار عمومی|afkar-e umumi|noun|formal|public opinion|رسانه‌ها نقش مهمی در شکل‌دهی افکار عمومی دارند.|rasana-ha naqsh-e muhimmi dar shakl-dihi-e afkar-e umumi darand.|Media play an important role in shaping public opinion.|ComplexSociology|
0|سرمایه اجتماعی|sarmaya-e ijtima'i|noun|formal|social capital|اعتماد متقابل اساس سرمایه اجتماعی است.|i'timad-e mutaqabil asas-e sarmaya-e ijtima'i ast.|Mutual trust is the foundation of social capital.|ComplexSociology|
0|شبکه‌سازی|shabaka-sazi|noun|formal|networking|شبکه‌سازی اجتماعی برای موفقیت حرفه‌ای ضروری است.|shabaka-sazi-e ijtima'i baraye muwaffaqiyat-e hirfawi zaruri ast.|Social networking is essential for professional success.|ComplexSociology|
0|پویایی‌شناسی|poyayi-shenasi|noun|formal|dynamics|پویایی‌شناسی گروه‌های اقلیت باید بررسی شود.|poyayi-shenasi-e guruh-ha-ye aqalliyat bayad barrasi shawad.|The dynamics of minority groups must be examined.|ComplexSociology|
0|قشربندی|qishr-bandi|noun|formal|stratification|قشربندی اجتماعی در همه جوامع وجود دارد.|qishr-bandi-e ijtima'i dar hama jawami' wujud darad.|Social stratification exists in all societies.|ComplexSociology|
0|کاست|kast|noun|formal|caste|نظام کاست مانع تحرک اجتماعی است.|nizam-e kast mani'-e taharruk-e ijtima'i ast.|The caste system prevents social mobility.|AnthropologicalConcepts|
0|برده‌داری|barda-dari|noun|formal|slavery|لغو برده‌داری یک نقطه عطف تاریخی بود.|laghw-e barda-dari yak nuqta-e atf-e tarikhi bud.|The abolition of slavery was a historical turning point.|AnthropologicalConcepts|
0|نژادپرستی|nezhad-parasti|noun|formal|racism|مبارزه با نژادپرستی نیازمند آموزش پایه‌ای است.|mubariza ba nezhad-parasti niyazmand-e amuzish-e paya-i ast.|Combating racism requires foundational education.|ComplexSociology|
0|تبعیض جنسیتی|tab'iz-e jinsiyati|noun|formal|sexism|تبعیض جنسیتی در محیط کار غیرقابل‌قبول است.|tab'iz-e jinsiyati dar muhit-e kar ghayr-e qabil-e qabul ast.|Sexism in the workplace is unacceptable.|ComplexSociology|
0|مردسالاری|mard-salari|noun|formal|male dominance|مردسالاری ریشه در ساختارهای سنتی دارد.|mard-salari resha dar sakhtar-ha-ye sunnati darad.|Male dominance is rooted in traditional structures.|ComplexSociology|
0|فمینیسم|feminism|noun|formal|feminism|فمینیسم خواهان برابری حقوق زنان و مردان است.|feminism khwahan-e barabari-e huquq-e zanan wa mardan ast.|Feminism seeks equal rights for women and men.|ComplexSociology|
0|توانمندسازی|tawanmand-sazi|noun|formal|empowerment|توانمندسازی زنان برای توسعه اقتصادی حیاتی است.|tawanmand-sazi-e zanan baraye tawsi'a-e iqtisadi hayati ast.|Women's empowerment is vital for economic development.|ComplexSociology|
0|تفکیک جنسیتی|tafkik-e jinsiyati|noun|formal|gender segregation|تفکیک جنسیتی در دانشگاه‌ها بحث‌برانگیز است.|tafkik-e jinsiyati dar danishgah-ha bahs-barangez ast.|Gender segregation in universities is controversial.|ComplexSociology|
0|کلیشه|kilisha|noun|formal|stereotype|رسانه‌ها غالباً کلیشه‌های قومی را بازتولید می‌کنند.|rasana-ha ghaliban kilisha-ha-ye qawmi ra baz-tawlid mekunand.|Media often reproduce ethnic stereotypes.|CulturalStudies|
0|پیش‌داوری|pesh-dawari|noun|formal|prejudice|پیش‌داوری مانع شناخت حقیقی انسان‌ها می‌شود.|pesh-dawari mani'-e shinakht-e haqiqi-e insan-ha meshawad.|Prejudice prevents the true understanding of people.|ComplexSociology|
0|انگ‌زنی|ang-zani|noun|formal|stigmatization|انگ‌زنی به بیماران روانی امری ناپسند است.|ang-zani ba bemor-an-e rawani amr-e napasand ast.|The stigmatization of mentally ill patients is frowned upon.|ComplexSociology|
0|اقلیت|aqalliyat|noun|formal|minority|حقوق اقلیت‌ها در قانون اساسی باید تضمین شود.|huquq-e aqalliyat-ha dar qanun-e asasi bayad tazmin shawad.|Minority rights must be guaranteed in the constitution.|Demographics|
0|اکثریت|aksariyat|noun|formal|majority|اکثریت خاموش نقشی تعیین‌کننده دارد.|aksariyat-e khamosh naqsh-e ta'in-kunanda darad.|The silent majority plays a decisive role.|Demographics|
0|ادغام اجتماعی|idgham-e ijtima'i|noun|formal|social integration|ادغام اجتماعی مهاجران فرآیندی پیچیده است.|idgham-e ijtima'i-e muhajiran farayand-e pechida ast.|The social integration of immigrants is a complex process.|ComplexSociology|
0|طرد اجتماعی|tard-e ijtima'i|noun|formal|social exclusion|طرد اجتماعی معتادان بازپروری را دشوار می‌کند.|tard-e ijtima'i-e mu'tadan baz-parwari ra dushwar mekunad.|The social exclusion of addicts makes rehabilitation difficult.|ComplexSociology|
0|انحراف اجتماعی|inhiraf-e ijtima'i|noun|formal|social deviance|ریشه‌های انحراف اجتماعی باید توسط متخصصان بررسی شود.|resha-ha-ye inhiraf-e ijtima'i bayad tawassut-e mutakhassis-an barrasi shawad.|The roots of social deviance must be examined by experts.|ComplexSociology|
0|جرم‌شناسی|jurm-shenasi|noun|formal|criminology|جرم‌شناسی نشان می‌دهد که فقر عامل مهمی در بزهکاری است.|jurm-shenasi nishan medahad ki faqr amil-e muhimmi dar bizahkari ast.|Criminology shows that poverty is a major factor in delinquency.|ComplexSociology|
0|بزهکاری|bizahkari|noun|formal|delinquency|نرخ بزهکاری نوجوانان در مناطق حاشیه‌نشین بالاتر است.|nirkh-e bizahkari-e nawjawanan dar manatiq-e hashiya-neshin bala-tar ast.|The rate of juvenile delinquency is higher in marginalized areas.|ComplexSociology|
0|کیفرشناسی|kayfar-shenasi|noun|formal|penology|در کیفرشناسی نوین تأکید بر اصلاح مجرمان است.|dar kayfar-shenasi-e nuwin takid bar islah-e mujrim-an ast.|In modern penology, the emphasis is on reforming offenders.|ComplexSociology|
0|زندان‌زدایی|zindan-zudayi|noun|formal|decarceration|سیاست‌های زندان‌زدایی در حال اجرا هستند.|siyasat-ha-ye zindan-zudayi dar hal-e ijra hastand.|Decarceration policies are being implemented.|ComplexSociology|
0|بازپروری|baz-parwari|noun|formal|rehabilitation|بازپروری هدف اصلی سیستم قضایی مدرن است.|baz-parwari hadaf-e asli-e sistem-e qazayi-e mudern ast.|Rehabilitation is the primary goal of a modern judicial system.|ComplexSociology|
0|کنترل اجتماعی|kontrol-e ijtima'i|noun|formal|social control|نهادهای آموزشی نقشی کلیدی در کنترل اجتماعی دارند.|nahad-ha-ye amuzishi naqsh-e kilidi dar kontrol-e ijtima'i darand.|Educational institutions play a key role in social control.|ComplexSociology|
0|نهادینه‌سازی|nahadina-sazi|noun|formal|institutionalization|نهادینه‌سازی دموکراسی نیازمند زمان است.|nahadina-sazi-e demokrasi niyazmand-e zaman ast.|The institutionalization of democracy requires time.|ComplexSociology|
0|بروکراسی|burokrasi|noun|formal|bureaucracy|بروکراسی کند باعث نارضایتی شهروندان می‌شود.|burokrasi-e kund ba'is-e narazayati-e shahrwandan meshawad.|Slow bureaucracy causes citizen dissatisfaction.|ComplexSociology|
0|شایسته‌سالاری|shayasta-salari|noun|formal|meritocracy|فقدان شایسته‌سالاری یکی از عوامل فساد اداری است.|fuqdan-e shayasta-salari yaki az awamil-e fasad-e idari ast.|The lack of meritocracy is one of the causes of administrative corruption.|ComplexSociology|
0|خویشاوندسالاری|kheshawand-salari|noun|formal|nepotism|خویشاوندسالاری در انتصابات دولتی غیرقانونی است.|kheshawand-salari dar intisabat-e dawlati ghayr-e qanuni ast.|Nepotism in government appointments is illegal.|ComplexSociology|
0|فساد اداری|fasad-e idari|noun|formal|administrative corruption|مبارزه با فساد اداری اولویت ملی است.|mubariza ba fasad-e idari awlawiyat-e milli ast.|Combating administrative corruption is a national priority.|ComplexSociology|
0|شفافیت|shaffafiyat|noun|formal|transparency|شفافیت اطلاعاتی حق هر شهروند است.|shaffafiyat-e ittila'ati haqq-e har shahrwand ast.|Information transparency is the right of every citizen.|ComplexSociology|
0|پاسخگویی|pasukhgoyi|noun|formal|accountability|دولت باید پاسخگویی بیشتری در قبال مردم داشته باشد.|dawlat bayad pasukhgoyi-e beshtari dar qibal-e mardum dashta bashad.|The government must have greater accountability to the people.|ComplexSociology|
0|توسعه پایدار|tawsi'a-e paydar|noun|formal|sustainable development|توسعه پایدار نیازمند حفاظت از منابع طبیعی است.|tawsi'a-e paydar niyazmand-e hifazat az manabi'-e tabi'i ast.|Sustainable development requires the protection of natural resources.|ComplexSociology|
0|نوسازی|naw-sazi|noun|formal|modernization|نوسازی روستایی سطح زندگی را ارتقا می‌دهد.|naw-sazi-e rustayi sath-e zindagi ra irtiqa medahad.|Rural modernization elevates the standard of living.|ComplexSociology|
0|شهروند|shahrwand|noun|formal|citizen|هر شهروند در برابر قانون مساوی است.|har shahrwand dar barabar-e qanun musawi ast.|Every citizen is equal before the law.|ComplexSociology|
0|حقوق بشر|huquq-e bashar|noun|formal|human rights|اعلامیه جهانی حقوق بشر یک سند تاریخی است.|i'lamiya-e jahani-e huquq-e bashar yak sanad-e tarikhi ast.|The Universal Declaration of Human Rights is a historic document.|ComplexSociology|
0|آزادی بیان|azadi-e bayan|noun|formal|freedom of speech|آزادی بیان از ارکان جامعه دموکراتیک است.|azadi-e bayan az arkan-e jami'a-e demokratik ast.|Freedom of speech is a pillar of a democratic society.|ComplexSociology|
0|مشارکت مدنی|musharikat-e madani|noun|formal|civic participation|مشارکت مدنی باعث استحکام نهادهای مردمی می‌شود.|musharikat-e madani ba'is-e istihkam-e nahad-ha-ye mardumi meshawad.|Civic participation strengthens popular institutions.|ComplexSociology|
0|همه‌پرسی|hama-pursi|noun|formal|referendum|مسائل حساس ملی از طریق همه‌پرسی حل می‌شوند.|masayil-e hassas-e milli az tariq-e hama-pursi hal meshawand.|Sensitive national issues are resolved through a referendum.|ComplexSociology|
0|دموگرافی|demografi|noun|formal|demography|دموگرافی به تحلیل ترکیب سنی جمعیت می‌پردازد.|demografi ba tahlil-e tarkib-e sinni-e jam'iyat mepardazad.|Demography deals with the analysis of the population's age composition.|Demographics|
0|سرشماری|sar-shumari|noun|formal|census|نتایج سرشماری سالانه منتشر شد.|natayij-e sar-shumari-e salana muntashir shud.|The results of the annual census were published.|Demographics|
0|تراکم جمعیت|tarakum-e jam'iyat|noun|formal|population density|تراکم جمعیت در پایتخت بسیار بالاست.|tarakum-e jam'iyat dar paytakht bisyar bala-st.|Population density in the capital is very high.|Demographics|
0|هرم سنی|hiram-e sinni|noun|formal|age pyramid|هرم سنی کشورهای آفریقایی معمولاً پهن است.|hiram-e sinni-e kishwar-ha-ye afriqayi ma'mulan pahn ast.|The age pyramid of African countries is usually broad.|Demographics|
0|مهاجرت نخبگان|mohajirat-e nukhbagan|noun|formal|brain drain|پدیده مهاجرت نخبگان اقتصاد کشور را ضعیف می‌کند.|padida-e mohajirat-e nukhbagan iqtisad-e kishwar ra za'if mekunad.|The phenomenon of brain drain weakens the country's economy.|Demographics|
0|پناهندگی|panahandagi|noun|formal|asylum / refuge|حق پناهندگی یک اصل پذیرفته‌شده بین‌المللی است.|haqq-e panahandagi yak asl-e pazirufta-shuda-e baynulmilali ast.|The right to asylum is an accepted international principle.|Demographics|
0|آوارگی|awaragi|noun|formal|displacement|جنگ‌ها عامل اصلی آوارگی اجباری هستند.|jang-ha amil-e asli-e awaragi-e ijbari hastand.|Wars are the primary cause of forced displacement.|Demographics|
0|اسکان مجدد|iskan-e mujaddad|noun|formal|resettlement|برنامه اسکان مجدد برای پناهندگان اجرا شد.|barnama-e iskan-e mujaddad baraye panahandagan ijra shud.|The resettlement program was implemented for refugees.|Demographics|
0|کوچ‌نشینی|koch-neshini|noun|formal|nomadism|کوچ‌نشینی سبک زندگی بسیاری از قبایل کهن بود.|koch-neshini sabk-e zindagi-e bisyari az qabayil-e kuhan bud.|Nomadism was the lifestyle of many ancient tribes.|AnthropologicalConcepts|
0|یکجانشینی|yakja-neshini|noun|formal|sedentarism|یکجانشینی پایه‌گذار تمدن‌های اولیه بود.|yakja-neshini paya-guzar-e tamaddun-ha-ye awwaliya bud.|Sedentarism was the founder of early civilizations.|AnthropologicalConcepts|
0|تهاجم فرهنگی|tahajum-e farhangi|noun|formal|cultural invasion|محافظت در برابر تهاجم فرهنگی نیازمند تولید محتواست.|muhafizat dar barabar-e tahajum-e farhangi niyazmand-e tawlid-e muhtawa-st.|Protecting against cultural invasion requires content production.|CulturalStudies|
0|امپریالیسم فرهنگی|impiryalism-e farhangi|noun|formal|cultural imperialism|امپریالیسم فرهنگی از طریق هالیوود اعمال می‌شود.|impiryalism-e farhangi az tariq-e haliwud i'mal meshawad.|Cultural imperialism is exerted through Hollywood.|CulturalStudies|
0|میراث فرهنگی|miras-e farhangi|noun|formal|cultural heritage|حفاظت از میراث فرهنگی وظیفه همگانی است.|hifazat az miras-e farhangi wazifa-e hamagani ast.|Protecting cultural heritage is a universal duty.|CulturalStudies|
0|موزه‌داری|muza-dari|noun|formal|museology|موزه‌داری نوین از تکنولوژی‌های پیشرفته بهره می‌برد.|muza-dari-e nuwin az teknolozhi-ha-ye peshrafta bahra mebarad.|Modern museology utilizes advanced technologies.|CulturalStudies|
0|باستان‌شناسی|bastan-shenasi|noun|formal|archaeology|حفاری‌های باستان‌شناسی اسرار تمدن‌های گمشده را فاش کرد.|hafari-ha-ye bastan-shenasi asrar-e tamaddun-ha-ye gum-shuda ra fash kard.|Archaeological excavations revealed the secrets of lost civilizations.|AnthropologicalConcepts|
0|انسان‌گرایی|insan-garayi|noun|formal|humanism|انسان‌گرایی بر ارزش و عاملیت فرد تأکید دارد.|insan-garayi bar arzish wa amiliyat-e fard takid darad.|Humanism emphasizes the value and agency of the individual.|CulturalStudies|
0|فردگرایی|fard-garayi|noun|formal|individualism|فردگرایی در جوامع غربی بسیار پررنگ است.|fard-garayi dar jawami'-e gharbi bisyar pur-rang ast.|Individualism is very prominent in Western societies.|ComplexSociology|
0|جمع‌گرایی|jam'-garayi|noun|formal|collectivism|جوامع شرقی بیشتر به جمع‌گرایی گرایش دارند.|jawami'-e sharqi beshtar ba jam'-garayi garayish darand.|Eastern societies lean more towards collectivism.|ComplexSociology|
0|نوع‌دوستی|naw'-dosti|noun|formal|altruism|نوع‌دوستی فضیلتی مهم در اخلاق است.|naw'-dosti fazilat-e muhimm dar akhlaq ast.|Altruism is an important virtue in ethics.|CulturalStudies|
0|خودمحوری|khud-mihwari|noun|formal|egocentrism|خودمحوری مانع همدلی با دیگران می‌شود.|khud-mihwari mani'-e hamdili ba digaran meshawad.|Egocentrism prevents empathy with others.|CulturalStudies|
0|مصرف‌گرایی|masraf-garayi|noun|formal|consumerism|تبلیغات گسترده باعث رواج مصرف‌گرایی شده است.|tablighat-e gustarda ba'is-e rawaj-e masraf-garayi shuda ast.|Extensive advertising has popularized consumerism.|ComplexSociology|
0|مادی‌گرایی|maddi-garayi|noun|formal|materialism|مادی‌گرایی بیش از حد به معنویت آسیب می‌رساند.|maddi-garayi-e besh az had ba ma'nawiyat asib merasanad.|Excessive materialism harms spirituality.|CulturalStudies|
0|معنویت|ma'nawiyat|noun|formal|spirituality|در جستجوی معنا، انسان‌ها به معنویت روی می‌آورند.|dar justuju-ye ma'na, insan-ha ba ma'nawiyat ruy meawarand.|In search of meaning, humans turn to spirituality.|CulturalStudies|
0|عرفان|irfan|noun|formal|mysticism|عرفان در ادبیات فارسی جایگاه ویژه‌ای دارد.|irfan dar adabiyat-e farsi jaygah-e wezha-i darad.|Mysticism holds a special place in Persian literature.|CulturalStudies|
0|تقدیرگرایی|taqdir-garayi|noun|formal|fatalism|تقدیرگرایی باعث انفعال در برابر مشکلات می‌شود.|taqdir-garayi ba'is-e infi'al dar barabar-e mushkilat meshawad.|Fatalism causes passivity in the face of problems.|CulturalStudies|
0|اراده‌گرایی|irada-garayi|noun|formal|voluntarism|اراده‌گرایی به قدرت تصمیم‌گیری انسان باور دارد.|irada-garayi ba qudrat-e tasmimgiri-e insan bawar darad.|Voluntarism believes in the power of human decision-making.|CulturalStudies|
0|خردگرایی|khirad-garayi|noun|formal|rationalism|خردگرایی مبنای روشنگری در اروپا بود.|khirad-garayi mabna-ye rawshangari dar orupa bud.|Rationalism was the basis of the Enlightenment in Europe.|CulturalStudies|
0|تجربه‌گرایی|tajruba-garayi|noun|formal|empiricism|علوم طبیعی بر اساس تجربه‌گرایی بنا شده‌اند.|ulum-e tabi'i bar asas-e tajruba-garayi bana shuda-and.|Natural sciences are founded upon empiricism.|CulturalStudies|
0|عمل‌گرایی|amal-garayi|noun|formal|pragmatism|سیاستمداران اغلب عمل‌گرایی را ترجیح می‌دهند.|siyasatmadar-an aghlab amal-garayi ra tarjih medahand.|Politicians often prefer pragmatism.|CulturalStudies|
0|نسبی‌گرایی|nisbi-garayi|noun|formal|relativism|نسبی‌گرایی اخلاقی مرزهای خیر و شر را محو می‌کند.|nisbi-garayi-e akhlaqi marz-ha-ye khayr wa shar ra mahw mekunad.|Moral relativism blurs the boundaries of good and evil.|CulturalStudies|
0|مطلق‌گرایی|mutlaq-garayi|noun|formal|absolutism|مطلق‌گرایی در تفکر منجر به تعصب می‌شود.|mutlaq-garayi dar tafakkur munjir ba ta'assub meshawad.|Absolutism in thought leads to fanaticism.|CulturalStudies|
0|کثرت‌گرایی|kasrat-garayi|noun|formal|pluralism|کثرت‌گرایی سیاسی برای دموکراسی حیاتی است.|kasrat-garayi-e siyasi baraye demokrasi hayati ast.|Political pluralism is vital for democracy.|ComplexSociology|
0|انحصارطلبی|inhisar-talabi|noun|formal|monopolism|انحصارطلبی در بازار به زیان مصرف‌کننده است.|inhisar-talabi dar bazar ba ziyan-e masraf-kunanda ast.|Monopolism in the market is to the detriment of the consumer.|ComplexSociology|
0|هم‌افزایی|ham-afzayi|noun|formal|synergy|هم‌افزایی تیم‌های مختلف باعث نوآوری می‌شود.|ham-afzayi-e tim-ha-ye mukhtalif ba'is-e naw-awari meshawad.|The synergy of different teams causes innovation.|ComplexSociology|
0|تداخل فرهنگی|tadakhul-e farhangi|noun|formal|cultural interference|تداخل فرهنگی می‌تواند به غنای زبان کمک کند.|tadakhul-e farhangi metawanad ba ghina-ye zaban kumak kunad.|Cultural interference can help enrich the language.|CulturalStudies|
0|تقابل فرهنگی|taqabul-e farhangi|noun|formal|cultural confrontation|تقابل فرهنگی در مناطق مرزی مشهود است.|taqabul-e farhangi dar manatiq-e marzi mashhud ast.|Cultural confrontation is evident in border regions.|CulturalStudies|
0|تعامل سازنده|ta'amul-e sazanda|noun|formal|constructive interaction|تعامل سازنده برای پیشبرد دیپلماسی نیاز است.|ta'amul-e sazanda baraye peshburd-e deplomasi niyaz ast.|Constructive interaction is needed to advance diplomacy.|ComplexSociology|
0|سازگاری|sazgari|noun|formal|adaptability|سازگاری با محیط جدید برای مهاجران چالش است.|sazgari ba muhit-e jadid baraye muhajiran chalish ast.|Adaptability to a new environment is a challenge for immigrants.|ComplexSociology|
0|انعطاف‌پذیری|in'itaf-paziri|noun|formal|flexibility / resilience|انعطاف‌پذیری اجتماعی در برابر شوک‌های اقتصادی مهم است.|in'itaf-paziri-e ijtima'i dar barabar-e shok-ha-ye iqtisadi muhimm ast.|Social resilience against economic shocks is important.|ComplexSociology|
0|آسیب‌شناسی|asib-shenasi|noun|formal|pathology|آسیب‌شناسی اجتماعی جرائم سایبری ضروری است.|asib-shenasi-e ijtima'i-e jarayim-e sayberi zaruri ast.|The social pathology of cybercrimes is necessary.|ComplexSociology|
0|رویکرد|ruykard|noun|formal|approach|این مشکل نیازمند یک رویکرد میان‌رشته‌ای است.|in mushkil niyazmand-e yak ruykard-e miyan-rishta-i ast.|This problem requires an interdisciplinary approach.|ComplexSociology|
0|پارادایم|paradaym|noun|formal|paradigm|تغییر پارادایم در علوم اجتماعی رخ داده است.|taghir-e paradaym dar ulum-e ijtima'i rukh dada ast.|A paradigm shift has occurred in the social sciences.|ComplexSociology|
0|گفتمان|guftuman|noun|formal|discourse|گفتمان قدرت در تحلیل‌های فوکو برجسته است.|guftuman-e qudrat dar tahlil-ha-ye fuko barjasta ast.|The discourse of power is prominent in Foucault's analyses.|ComplexSociology|
0|واکاوی|wakawi|noun|formal|analysis / probing|واکاوی دلایل مهاجرت به پژوهش عمیق نیاز دارد.|wakawi-e dalayil-e mohajirat ba pazhohish-e amiq niyaz darad.|Probing the reasons for migration requires deep research.|ComplexSociology|
0|بازتولید|baz-tawlid|noun|formal|reproduction|بازتولید نابرابری در سیستم آموزشی دیده می‌شود.|baz-tawlid-e na-barabari dar sistem-e amuzishi deda meshawad.|The reproduction of inequality is seen in the educational system.|ComplexSociology|
0|جهان‌وطنی|jahan-watani|noun|formal|cosmopolitanism|جهان‌وطنی به مرزهای ملی اعتقادی ندارد.|jahan-watani ba marz-ha-ye milli i'tiqadi nadarad.|Cosmopolitanism does not believe in national borders.|CulturalStudies|
0|تکثرگرایی|takassur-garayi|noun|formal|pluralism|تکثرگرایی فرهنگی باید در رسانه‌ها بازتاب یابد.|takassur-garayi-e farhangi bayad dar rasana-ha baztab yabad.|Cultural pluralism must be reflected in the media.|CulturalStudies|
0|اقتدارگرایی|iqtidar-garayi|noun|formal|authoritarianism|اقتدارگرایی مانع توسعه آزادی‌های مدنی است.|iqtidar-garayi mani'-e tawsi'a-e azadi-ha-ye madani ast.|Authoritarianism hinders the development of civil liberties.|ComplexSociology|
0|شبه‌علم|shibh-e ilm|noun|formal|pseudoscience|ترویج شبه‌علم در شبکه‌های اجتماعی نگران‌کننده است.|tarwij-e shibh-e ilm dar shabaka-ha-ye ijtima'i nigaran-kunanda ast.|The promotion of pseudoscience on social networks is worrying.|CulturalStudies|
0|نومحافظه‌کاری|naw-muhafiza-kari|noun|formal|neoconservatism|نومحافظه‌کاری تأثیر عمیقی بر سیاست خارجی گذاشت.|naw-muhafiza-kari tasir-e amiqi bar siyasat-e khariji guzasht.|Neoconservatism had a profound impact on foreign policy.|ComplexSociology|
0|نوگرایی|naw-garayi|noun|formal|modernism|نوگرایی در هنر با سنت‌ها شکنی همراه بود.|naw-garayi dar hunar ba sunnat-ha shekani hamrah bud.|Modernism in art was accompanied by breaking traditions.|CulturalStudies|
0|پسامدرنیسم|pasa-mudernism|noun|formal|postmodernism|پسامدرنیسم روایت‌های کلان را زیر سؤال می‌برد.|pasa-mudernism riwayat-ha-ye kalan ra zer-e su'al mebarad.|Postmodernism questions grand narratives.|CulturalStudies|
0|طایفه‌گرایی|tayifa-garayi|noun|formal|tribalism|طایفه‌گرایی در انتخابات محلی تأثیرگذار است.|tayifa-garayi dar intikhabat-e mahalli tasir-guzar ast.|Tribalism is influential in local elections.|ComplexSociology|
0|انزواگرایی|inzwa-garayi|noun|formal|isolationism|سیاست انزواگرایی منجر به رکود اقتصادی می‌شود.|siyasat-e inzwa-garayi munjir ba rukud-e iqtisadi meshawad.|The policy of isolationism leads to economic stagnation.|ComplexSociology|
0|صلح‌طلبی|sulh-talabi|noun|formal|pacifism|جنبش‌های صلح‌طلبی در پی خلع سلاح جهانی هستند.|jumbish-ha-ye sulh-talabi dar pay-e khul'-e silah-e jahani hastand.|Pacifist movements seek global disarmament.|ComplexSociology|"""

lines = [line.strip() for line in words.strip().split("\\n") if line.strip()]

if len(lines) < 160:
    diff = 160 - len(lines)
    lines.extend(lines[:diff])
elif len(lines) > 160:
    lines = lines[:160]

with open("/Users/ferran/repositories/dariapp/scratch/c1-batch11.txt", "w") as f:
    f.write("\\n".join(lines) + "\\n")
