-- ---------------------------------------------------------------------------
-- Where an exercise came from
-- ---------------------------------------------------------------------------
--
-- Practice exercises are now built from seed text with no model call: every
-- word in a seed text is already linked to a lexeme by the build, so an
-- exercise cut out of one is in-vocabulary by construction. Those are served
-- before the generator runs, and the generator is called only when they are
-- exhausted.
--
-- Without this column the two are indistinguishable in the table, and the one
-- question worth asking - what share of practice now costs nothing, given five
-- free-tier provider quotas shared by every learner of the deployment - cannot
-- be answered. Defaults to 'ai' so every existing row keeps its true origin.

alter table public.exercises
  add column source text not null default 'ai'
  check (source in ('ai', 'seed-text'));

comment on column public.exercises.source is
  'ai = generated by the provider chain; seed-text = cut from an authored text, no model call.';

create index exercises_source_idx on public.exercises (source);
