-- ---------------------------------------------------------------------------
-- Drop columns nothing reads
-- ---------------------------------------------------------------------------
--
-- Each of these was confirmed unused by reading what the application actually
-- selects and writes, not by searching for the column's name: a name like
-- `questions` appears all over the codebase in unrelated contexts, and an
-- earlier sweep that trusted name matches reported "no ghost columns" while
-- all of these were sitting here.
--
-- The code that wrote them was deployed first, so there was never a moment
-- where the live app wrote to a column that did not exist.

-- texts.questions: added for comprehension questions generated by a model on
-- first read. That design was replaced; questions are authored content that
-- lives inside `texts.doc`. Never read or written since.
alter table public.texts drop column if exists questions;

-- texts.vocab_hash: written for every generated text, read by nothing. Its
-- index goes with it - nothing ever queried by (level, vocab_hash).
drop index if exists public.texts_level_vocab_idx;
alter table public.texts drop column if exists vocab_hash;

-- lexemes: everything except `id`.
--
-- The app never reads this table; it builds its dictionary from the bundled
-- lexicon.json. The table exists so `assert_lexeme_ref` can reject a
-- flashcard pointing at a word the app does not ship, and that trigger reads
-- `lexemes.id` only.
--
-- The rest was a full copy of the dictionary, and a copy kept in step by hand
-- is one that drifts: it once held 6,033 rows against 5,997 in the file, and a
-- learner had flashcards that could never be reviewed. With only ids stored,
-- there is nothing left to disagree with the file.
drop index if exists public.lexemes_freq_band_idx;
alter table public.lexemes
  drop column if exists target,
  drop column if exists target_normalized,
  drop column if exists translit,
  drop column if exists gloss_en,
  drop column if exists pos,
  drop column if exists freq_rank,
  drop column if exists freq_band,
  drop column if exists register,
  drop column if exists variants,
  drop column if exists example_target,
  drop column if exists example_translit,
  drop column if exists example_en,
  drop column if exists audio_url,
  drop column if exists tags;
